### ISSUE TITLE
MCU案例总是提示找不到文件

### ISSUE THREAD

**Issue by JiaDuo** [qilingframework/qiling#1002]
***Describe the bug**
尝试了不同的路径去运行，但是STM32F4的案例总是提示错误：
~/temp/qiling-1.4.0/examples/mcu$ python3 stm32f4_led.py 
Traceback (most recent call last):
  File "stm32f4_led.py", line 16, in <module>
    stm32f4_led()
  File "stm32f4_led.py", line 9, in stm32f4_led
    ql = Qiling(["../rootfs/mcu/stm32f411/rand_blink.hex"],                    
  File "/usr/local/lib/python3.8/dist-packages/qiling/core.py", line 144, in __init__
    raise QlErrorFileNotFound("Target binary not found: %s" %(self._argv[0]))
qiling.exception.QlErrorFileNotFound: Target binary not found: qilingcode

**Comment by JiaDuo** [comment]
rootfs的文件已经下载了也

**Comment by cla7aye15I4nd** [comment]
在我本地似乎没有发生这样的情况，但我的猜测是python运行了你安装的qiling而不是文件夹qiling-1.4.0下的，也许尝试用pip先卸载掉旧的qiling？

**Comment by JiaDuo** [comment]
路径确实有问题，卸载后，运行又出现未定义的问题。
~/temp/qiling-1.4.0/examples/mcu$ python3 stm32f4_led.py 
[+]	Profile: stm32f411
Traceback (most recent call last):
  File "stm32f4_led.py", line 16, in <module>
    stm32f4_led()
  File "stm32f4_led.py", line 9, in stm32f4_led
    ql = Qiling(["../rootfs/mcu/stm32f411/rand_blink.hex"],                    
  File "/home/zer0usn/temp/qiling-1.4.0/examples/mcu/../../qiling/core.py", line 213, in __init__
    self._hw  = component_setup("hw", "hw", self)
  File "/home/zer0usn/temp/qiling-1.4.0/examples/mcu/../../qiling/utils.py", line 425, in component_setup
    return ql_get_module_function(f"qiling.{component_type}.{component_name}", function_name)(ql)
  File "/home/zer0usn/temp/qiling-1.4.0/examples/mcu/../../qiling/utils.py", line 244, in ql_get_module_function
    imp_module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zer0usn/temp/qiling-1.4.0/examples/mcu/../../qiling/hw/__init__.py", line 10, in <module>
    from .intc import *
  File "/home/zer0usn/temp/qiling-1.4.0/examples/mcu/../../qiling/hw/intc/__init__.py", line 6, in <module>
    from .cm4_nvic import CortexM4Nvic
  File "/home/zer0usn/temp/qiling-1.4.0/examples/mcu/../../qiling/hw/intc/cm4_nvic.py", line 9, in <module>
    from qiling.arch.arm_const import IRQ
  File "/home/zer0usn/temp/qiling-1.4.0/examples/mcu/../../qiling/arch/arm_const.py", line 29, in <module>
    "xpsr": UC_ARM_REG_XPSR,
NameError: name 'UC_ARM_REG_XPSR' is not defined

**Comment by cla7aye15I4nd** [comment]
请安装uc2

**Comment by JiaDuo** [comment]
已经安装uc2，还是一样的错误，我检索了下 UC_ARM_REG_XPSR 这个字符串，发现uc2中竟然没有。是版本问题吗？
直接从https://github.com/unicorn-engine/unicorn安装的。

**Comment by cla7aye15I4nd** [comment]
pip3 install unicorn==2.0.0-rc3

**Comment by cla7aye15I4nd** [comment]
> 已经安装uc2，还是一样的错误，我检索了下 UC_ARM_REG_XPSR 这个字符串，发现uc2中竟然没有。是版本问题吗？ 直接从[https://github.com/unicorn-engine/unicorn安装的。](https://github.com/unicorn-engine/unicorn%E5%AE%89%E8%A3%85%E7%9A%84%E3%80%82)

在dev分支里

**Comment by JiaDuo** [comment]
按您的帮助操作已解决，感谢！
