### ISSUE TITLE
Qiling gdb fails with gdb internal error

### ISSUE THREAD

**Issue by srobertjames** [qilingframework/qiling#1092]
**Describe the bug**
`ql.debugger = True` fails with gdb error

**Sample Code**
```python
ql.debugger = True
```
```
...
[=]	Done with loading rootfs/x8664_windows/Windows/System32/api-ms-win-crt-locale-l1-1-0.dll
[=]	gdb> Stop at entry point: 0x402680
[=]	gdb> Listening on 127.0.01:9999
```
```
$ gdb-multiarch 
pwndbg: loaded 197 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
pwndbg> set remotetimeout 100
pwndbg> target remote 127.0.0.1:9999
Remote debugging using 127.0.0.1:9999
/build/gdb-123VQR/gdb-10.1/gdb/target-descriptions.c:1151: internal-error: void tdesc_use_registers(gdbarch*, const target_desc*, tdesc_arch_data*, tdesc_unknown_register_ftype): Assertion `data->arch_regs.size () <= num_regs' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.

This is a bug, please report it.  For instructions, see:
<https://www.gnu.org/software/gdb/bugs/>.

Aborted (core dumped)
```
**Similar error occurred** when I ran gdb with pwndb disabled

**Additional context**

Other errors in trying to use the debugger:

```
ql.debugger = 'qdb'
...
  File "/home/srj/.local/lib/python3.9/site-packages/qiling/debugger/qdb/utils.py", line 49, in dump_regs
    return {reg_name: getattr(ql.reg, reg_name) for reg_name in _reg_order}
UnboundLocalError: local variable '_reg_order' referenced before assignment
```

```
ql.debugger = 'gdb:rr:0.0.0.0:1234'
...
    return obj(ql, *args)
TypeError: __init__() takes from 2 to 4 positional arguments but 5 were given

```

```
ql.debugger = 'gdb:rr'
...
[=]	gdb> Listening on rr:9999
Traceback (most recent call last):
...
  File "/home/srj/.local/lib/python3.9/site-packages/qiling/debugger/gdb/gdb.py", line 141, in setup_server
    sock.bind((self.ip, self.port))
socket.gaierror: [Errno -3] Temporary failure in name resolution
```

**Comment by srobertjames** [comment]
Thank you for your help.  I retried as said, and got the same gdb error:
```
ql.debugger = 'gdb:127.0.0.1:4444'
...
[=]	gdb> Stop at entry point: 0x402680
[=]	gdb> Listening on 127.0.0.1:4444
```

```
# In separate terminal:
~$ gdb-multiarch 
pwndbg: loaded 197 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
pwndbg> target remote 127.0.0.1:4444
Remote debugging using 127.0.0.1:4444
/build/gdb-123VQR/gdb-10.1/gdb/target-descriptions.c:1151: internal-error: void tdesc_use_registers(gdbarch*, const target_desc*, tdesc_arch_data*, tdesc_unknown_register_ftype): Assertion `data->arch_regs.size () <= num_regs' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.

This is a bug, please report it.  For instructions, see:
<https://www.gnu.org/software/gdb/bugs/>.

Aborted (core dumped)
~$ 
```

Re git: I've installed Qiling using pip, so there's no git log:

```
~$ cd ~/.local/lib/python3.9/site-packages/qiling
~/.local/lib/python3.9/site-packages/qiling$ git log -n 1 --decorate=short | head -n 1
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
~/.local/lib/python3.9/site-packages/qiling$ cat __version__.py 
# NOTE: use "-dev" for dev branch
__version__ = "1.4.2"
#__version__ = "1.4.3" + "-dev"
```

I'll note that my target is `ql = Qiling(path, rootfs, archtype="x86", ostype="windows", libcache=False, verbose=verbose)`; my host itself is Ubuntu 21.04 Linux.

**Comment by elicn** [comment]
I tried to reproduce it locally, but it seems fine here.
Is it posible for you to share the binary and the script youa re using?

That said, I noticed the following line ([here](https://github.com/qilingframework/qiling/blob/ac2a33936041b010befb21e32c5c4efbf2b90e18/qiling/debugger/gdb/gdb.py#L498)) saying:
```python
if os.path.exists(xfercmd_file) and self.ql.ostype is not QL_OS.WINDOWS:
```
which seems to exclude Windows from the supported platforms.
@xwings, since you introduced this line (as part of this commit: of https://github.com/qilingframework/qiling/commit/743cfad06056142e30f78bb984dacae2667361b1) could you please comment on the reason for Windows being unsupported?

**Comment by srobertjames** [comment]
Thanks! Binary is at https://github.com/utcoalition/utcctf-19/blob/master/rev-hactivate/rev.exe .  Host OS is Linux; target is Windows.

**Comment by srobertjames** [comment]
[rev-hactivate_solver.zip](https://github.com/qilingframework/qiling/files/8091703/rev-hactivate_solver.zip)

I've cleaned up my script and attached it.  If you turn DEBUGGER on, it will fail with that message, at least with my gdb:

```
$ gdb-multiarch -v
GNU gdb (Ubuntu 10.1-2ubuntu2) 10.1.90.20210411-git
...
```
