### ISSUE TITLE
wil qiling support run a elf which compress by upx？

### ISSUE THREAD

**Issue by w1th1c3** [qilingframework/qiling#1117]
i just use upx to  compress a elf ,which will call system(ls -alh)  after running
i can run it on linux  normally
but i run it with qiling, it will exit, do not call system(ls -alh)

**Comment by elicn** [comment]
Can you share the emulation properties (i.e. how you run Qiling) and log?
Please make sure to initialize Qiling with `verbose=QL_VERBOSE.DEBUG`.

**Comment by 23R3F** [comment]
@elicn 
c code：
```c
#include <stdio.h>
#include <stdlib.h>

int main(){
    puts("hello!");
	sleep(2);
	system("/bin/ls -lah");
	sleep(1);
	return 0;

}

```
upx ./upx_test
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    849944 ->    313640   36.90%   linux/amd64   upx_test                      

Packed 1 file.
```
run on ubuntu1804,  ./upx_test 
```
hello!
总用量 13M
drwxrwxr-x  7 xxx xxx 4.0K 3月  19 18:47 .
drwxrwxr-x 11 xxx xxx 4.0K 3月  19 04:42 ..
-rwxrwxr-x  1 xxx xxx 307K 3月  19 18:46 upx_test
-rw-rw-r--  1 xxx xxx 133 3月  19 18:46 upx_test.c

```


py code
```
#!/usr/bin/env python3
# coding:utf-8
from qiling import Qiling
from qiling.const import QL_VERBOSE,QL_INTERCEPT

if __name__ == "__main__":
    elf="./upx_test"
    rootfs="../examples/rootfs/x8664_linux"
    ql = Qiling([elf], rootfs, 
        verbose=QL_VERBOSE.DEBUG,
        multithread=True,
        )
    ql.run()
```

qiing debug log:
```
[+]	Profile: Default
[+]	Map GDT at 0x30000 with GDT_LIMIT=4096
[+]	Write to 0x30018 for new entry b'\x00\xf0\x00\x00\x00\xfeO\x00'
[+]	Write to 0x30028 for new entry b'\x00\xf0\x00\x00\x00\x96O\x00'
[+]	Mapped 0x400000-0x447000
[+]	Mapped 0x447000-0x6be000
[+]	mem_start : 0x400000
[+]	mem_end   : 0x6be000
[+]	mmap_address is : 0x7fffb7dd6000
[+] [Thread 2000]	Saved context: fs=0x0 tls=0x0
[+] [Thread 2000]	Set fsbase to 0x0 for [Thread 2000]
[+] [Thread 2000]	Restored context: fs=0x0 tls=0x0
[+] [Thread 2000]	Scheduled from 0x445cd8.
[+] [Thread 2000]	syscall hooked 0x445efe: ql_syscall_open()
[+] [Thread 2000]	open(/proc/self/exe, 0o0) = -2
[+] [Thread 2000]	**File not found /home/zeref/qiling/mytest/../examples/rootfs/x8664_linux/proc/self/exe**
[+] [Thread 2000]	0x0000000000445efe: open(filename = 0x445fbc, flags = 0x0, mode = 0x0) = -0x2 (ENOENT)
[+] [Thread 2000]	syscall hooked 0x445eee: ql_syscall_write()
[+] [Thread 2000]	write() CONTENT: b'/proc/self/exe'
/proc/self/exe[+] [Thread 2000]	0x0000000000445eee: write(fd = 0x2, buf = 0x445fbc, count = 0xe) = 0xe
[+] [Thread 2000]	syscall hooked 0x445ef6: ql_syscall_exit()
[+] [Thread 2000]	0x0000000000445ef6: exit(code = 0x7f) = ?
[+] [Thread 2000]	Suspended at 0x445ef8
[+] [Thread 2000]	Saved context: fs=0x0 tls=0x0
[+] [Thread 2000]	Call sched_cb: <function ql_syscall_exit.<locals>._sched_cb_exit at 0x7f0000280ae8>
[+] [Thread 2000]	[Thread 2000] Terminated

```
if i change the rootfs to "/"
then , it will get this logs:
```
[+]	Profile: Default
[+]	Map GDT at 0x30000 with GDT_LIMIT=4096
[+]	Write to 0x30018 for new entry b'\x00\xf0\x00\x00\x00\xfeO\x00'
[+]	Write to 0x30028 for new entry b'\x00\xf0\x00\x00\x00\x96O\x00'
[+]	Mapped 0x400000-0x447000
[+]	Mapped 0x447000-0x6be000
[+]	mem_start : 0x400000
[+]	mem_end   : 0x6be000
[+]	mmap_address is : 0x7fffb7dd6000
[+] [Thread 2000]	Saved context: fs=0x0 tls=0x0
[+] [Thread 2000]	Set fsbase to 0x0 for [Thread 2000]
[+] [Thread 2000]	Restored context: fs=0x0 tls=0x0
[+] [Thread 2000]	Scheduled from 0x445cd8.
[+] [Thread 2000]	syscall hooked 0x445efe: ql_syscall_open()
[+] [Thread 2000]	**open(/proc/self/exe, 0o0) = 3**
[+] [Thread 2000]	**File found: /usr/bin/python3.6**
[+] [Thread 2000]	0x0000000000445efe: open(filename = 0x445fbc, flags = 0x0, mode = 0x0) = 0x3
[+] [Thread 2000]	syscall hooked 0x445f51: ql_syscall_mmap()
[+] [Thread 2000]	mmap - mapping needed for 0x7fffb7dd6000
[+] [Thread 2000]	mmap - addr range  0x7fffb7dd6000 - 0x7fffb7e1cfff: 
[+] [Thread 2000]	0x0000000000445f51: mmap(addr = 0x0, length = 0x467de, prot = 0x3, flags = 0x22, fd = 0xffffffff, pgoffset = 0x0) = 0x7fffb7dd6000
[+] [Thread 2000]	syscall hooked 0x445f6c: ql_syscall_mmap()
[+] [Thread 2000]	mmap - MAP_FIXED, mapping not needed
[+] [Thread 2000]	mem write : 0x46635
[+] [Thread 2000]	mem mmap  : /usr/bin/python3.6
[+] [Thread 2000]	0x0000000000445f6c: mmap(addr = 0x7fffb7dd6000, length = 0x46635, prot = 0x3, flags = 0x12, fd = 0x3, pgoffset = 0x0) = 0x7fffb7dd6000
[+] [Thread 2000]	Suspended at 0x445cfc
[+] [Thread 2000]	Saved context: fs=0x0 tls=0x0
[+] [Thread 2000]	Call sched_cb: <function QlLinuxThread._default_sched_cb at 0x7f1f8dbdaa60>
[+] [Thread 2000]	Set fsbase to 0x0 for [Thread 2000]
[+] [Thread 2000]	Restored context: fs=0x0 tls=0x0
[+] [Thread 2000]	Scheduled from 0x445cfc.
[+] [Thread 2000]	syscall hooked 0x445fb1: ql_syscall_mprotect()
[+] [Thread 2000]	0x0000000000445fb1: mprotect(start = 0x7fffb7e1b000, mlen = 0x17de, prot = 0x5) = 0x0
[+] [Thread 2000]	syscall hooked 0x7fffb7e1c06f: ql_syscall_readlink()
[+] [Thread 2000]	readlink(/proc/self/exe, 0x80000000cfc8, 0xfff) = 34
[+] [Thread 2000]	0x00007fffb7e1c06f: readlink(path_name = 0x445fbc, path_buff = 0x80000000cfc8, path_buffsize = 0xfff) = 0x22
[+] [Thread 2000]	syscall hooked 0x7fffb7e1c129: ql_syscall_exit()
[+] [Thread 2000]	0x00007fffb7e1c129: exit(code = 0x7f) = ?
[+] [Thread 2000]	Suspended at 0x7fffb7e1c12b
[+] [Thread 2000]	Saved context: fs=0x0 tls=0x0
[+] [Thread 2000]	Call sched_cb: <function ql_syscall_exit.<locals>._sched_cb_exit at 0x7f1f8dbe5b70>
[+] [Thread 2000]	[Thread 2000] Terminated
```
you can see that , still cannot run normally, i think upx  will open  /**proc/self/exe**, but qiling open itself (python)，so this is a bug?

**Comment by w1th1c3** [comment]
@elicn 
c code：
```c
#include <stdio.h>
#include <stdlib.h>

int main(){
    puts("hello!");
	sleep(2);
	system("/bin/ls -lah");
	sleep(1);
	return 0;

}

```
upx ./upx_test
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    849944 ->    313640   36.90%   linux/amd64   upx_test                      

Packed 1 file.
```
run on ubuntu1804,  ./upx_test 
```
hello!
总用量 13M
drwxrwxr-x  7 xxx xxx 4.0K 3月  19 18:47 .
drwxrwxr-x 11 xxx xxx 4.0K 3月  19 04:42 ..
-rwxrwxr-x  1 xxx xxx 307K 3月  19 18:46 upx_test
-rw-rw-r--  1 xxx xxx 133 3月  19 18:46 upx_test.c

```


py code
```
#!/usr/bin/env python3
# coding:utf-8
from qiling import Qiling
from qiling.const import QL_VERBOSE,QL_INTERCEPT

if __name__ == "__main__":
    elf="./upx_test"
    rootfs="../examples/rootfs/x8664_linux"
    ql = Qiling([elf], rootfs, 
        verbose=QL_VERBOSE.DEBUG,
        multithread=True,
        )
    ql.run()
```

qiing debug log:
```
[+]	Profile: Default
[+]	Map GDT at 0x30000 with GDT_LIMIT=4096
[+]	Write to 0x30018 for new entry b'\x00\xf0\x00\x00\x00\xfeO\x00'
[+]	Write to 0x30028 for new entry b'\x00\xf0\x00\x00\x00\x96O\x00'
[+]	Mapped 0x400000-0x447000
[+]	Mapped 0x447000-0x6be000
[+]	mem_start : 0x400000
[+]	mem_end   : 0x6be000
[+]	mmap_address is : 0x7fffb7dd6000
[+] [Thread 2000]	Saved context: fs=0x0 tls=0x0
[+] [Thread 2000]	Set fsbase to 0x0 for [Thread 2000]
[+] [Thread 2000]	Restored context: fs=0x0 tls=0x0
[+] [Thread 2000]	Scheduled from 0x445cd8.
[+] [Thread 2000]	syscall hooked 0x445efe: ql_syscall_open()
[+] [Thread 2000]	open(/proc/self/exe, 0o0) = -2
[+] [Thread 2000]	**File not found /home/zeref/qiling/mytest/../examples/rootfs/x8664_linux/proc/self/exe**
[+] [Thread 2000]	0x0000000000445efe: open(filename = 0x445fbc, flags = 0x0, mode = 0x0) = -0x2 (ENOENT)
[+] [Thread 2000]	syscall hooked 0x445eee: ql_syscall_write()
[+] [Thread 2000]	write() CONTENT: b'/proc/self/exe'
/proc/self/exe[+] [Thread 2000]	0x0000000000445eee: write(fd = 0x2, buf = 0x445fbc, count = 0xe) = 0xe
[+] [Thread 2000]	syscall hooked 0x445ef6: ql_syscall_exit()
[+] [Thread 2000]	0x0000000000445ef6: exit(code = 0x7f) = ?
[+] [Thread 2000]	Suspended at 0x445ef8
[+] [Thread 2000]	Saved context: fs=0x0 tls=0x0
[+] [Thread 2000]	Call sched_cb: <function ql_syscall_exit.<locals>._sched_cb_exit at 0x7f0000280ae8>
[+] [Thread 2000]	[Thread 2000] Terminated

```
if i change the rootfs to "/"
then , it will get this logs:
```
[+]	Profile: Default
[+]	Map GDT at 0x30000 with GDT_LIMIT=4096
[+]	Write to 0x30018 for new entry b'\x00\xf0\x00\x00\x00\xfeO\x00'
[+]	Write to 0x30028 for new entry b'\x00\xf0\x00\x00\x00\x96O\x00'
[+]	Mapped 0x400000-0x447000
[+]	Mapped 0x447000-0x6be000
[+]	mem_start : 0x400000
[+]	mem_end   : 0x6be000
[+]	mmap_address is : 0x7fffb7dd6000
[+] [Thread 2000]	Saved context: fs=0x0 tls=0x0
[+] [Thread 2000]	Set fsbase to 0x0 for [Thread 2000]
[+] [Thread 2000]	Restored context: fs=0x0 tls=0x0
[+] [Thread 2000]	Scheduled from 0x445cd8.
[+] [Thread 2000]	syscall hooked 0x445efe: ql_syscall_open()
[+] [Thread 2000]	**open(/proc/self/exe, 0o0) = 3**
[+] [Thread 2000]	**File found: /usr/bin/python3.6**
[+] [Thread 2000]	0x0000000000445efe: open(filename = 0x445fbc, flags = 0x0, mode = 0x0) = 0x3
[+] [Thread 2000]	syscall hooked 0x445f51: ql_syscall_mmap()
[+] [Thread 2000]	mmap - mapping needed for 0x7fffb7dd6000
[+] [Thread 2000]	mmap - addr range  0x7fffb7dd6000 - 0x7fffb7e1cfff: 
[+] [Thread 2000]	0x0000000000445f51: mmap(addr = 0x0, length = 0x467de, prot = 0x3, flags = 0x22, fd = 0xffffffff, pgoffset = 0x0) = 0x7fffb7dd6000
[+] [Thread 2000]	syscall hooked 0x445f6c: ql_syscall_mmap()
[+] [Thread 2000]	mmap - MAP_FIXED, mapping not needed
[+] [Thread 2000]	mem write : 0x46635
[+] [Thread 2000]	mem mmap  : /usr/bin/python3.6
[+] [Thread 2000]	0x0000000000445f6c: mmap(addr = 0x7fffb7dd6000, length = 0x46635, prot = 0x3, flags = 0x12, fd = 0x3, pgoffset = 0x0) = 0x7fffb7dd6000
[+] [Thread 2000]	Suspended at 0x445cfc
[+] [Thread 2000]	Saved context: fs=0x0 tls=0x0
[+] [Thread 2000]	Call sched_cb: <function QlLinuxThread._default_sched_cb at 0x7f1f8dbdaa60>
[+] [Thread 2000]	Set fsbase to 0x0 for [Thread 2000]
[+] [Thread 2000]	Restored context: fs=0x0 tls=0x0
[+] [Thread 2000]	Scheduled from 0x445cfc.
[+] [Thread 2000]	syscall hooked 0x445fb1: ql_syscall_mprotect()
[+] [Thread 2000]	0x0000000000445fb1: mprotect(start = 0x7fffb7e1b000, mlen = 0x17de, prot = 0x5) = 0x0
[+] [Thread 2000]	syscall hooked 0x7fffb7e1c06f: ql_syscall_readlink()
[+] [Thread 2000]	readlink(/proc/self/exe, 0x80000000cfc8, 0xfff) = 34
[+] [Thread 2000]	0x00007fffb7e1c06f: readlink(path_name = 0x445fbc, path_buff = 0x80000000cfc8, path_buffsize = 0xfff) = 0x22
[+] [Thread 2000]	syscall hooked 0x7fffb7e1c129: ql_syscall_exit()
[+] [Thread 2000]	0x00007fffb7e1c129: exit(code = 0x7f) = ?
[+] [Thread 2000]	Suspended at 0x7fffb7e1c12b
[+] [Thread 2000]	Saved context: fs=0x0 tls=0x0
[+] [Thread 2000]	Call sched_cb: <function ql_syscall_exit.<locals>._sched_cb_exit at 0x7f1f8dbe5b70>
[+] [Thread 2000]	[Thread 2000] Terminated
```
you can see that , still cannot run normally, i think upx  will open  /**proc/self/exe**, but qiling open itself (python)，so this is a bug?

**Comment by w1th1c3** [comment]
@elicn 
by the  way，if i add a fake **/proc/self/exe ( copy target elf to rootfs/proc/self/exe )** to rootfs
it can run a short time,  but still can't call **ls -alh** in the end
logs :
[logs.txt](https://github.com/qilingframework/qiling/files/8310522/logs.txt)

**Comment by elicn** [comment]
Thanks for the details.
The emualted filesystem does not include the `/proc/self` directory automatically; for now you'll have to generate it yourself - like you did. The final run fails mostly because you are using Python 3.6 instead of 3.8: if you are using `dev` branch, then you have to use 3.8.

**Comment by 23R3F** [comment]
@elicn i use the docker of qiling，its python is 3.8.12，but still has the same error.....

**Comment by H4niz** [comment]
Hi you guys,

I also meet this issue and I'm trying to find the solution but I have not found it yet! 

My context is:
- Python3.6
- Stable Qiling

My script python:
```
from qiling import Qiling
from qiling.const import QL_VERBOSE
from qiling.extensions import trace

import os
cwd = os.getcwd()
# print(cwd)
os.chdir(cwd)


if __name__ == '__main__':
	argv = r"/home/h4niz/Downloads/firmware-analysis-toolkit/Zyxel/_V530ABSB5C0.bin.extracted/squashfs-root/bin/zhttpd -h".split(" ")
	rootfs = r"/home/h4niz/Downloads/firmware-analysis-toolkit/Zyxel/_V530ABSB5C0.bin.extracted/squashfs-root"
	libs = {"LD_LIBRARY_PATH":"/lib:/lib/private:/usr/lib"}

	ql = Qiling(argv, rootfs, verbose=QL_VERBOSE.DEBUG, archtype='MIPS', profile='zyxel.ql', multithread=True, env=libs)
	# trace.enable_full_trace(ql)
	ql.add_fs_mapper('/proc', '/proc')
	ql.run()
```

I attach output log in this file: [emu_debug_log.txt](https://github.com/qilingframework/qiling/files/8559770/emu_debug_log.txt)

Are there any ideas?

**Comment by elicn** [comment]
@H4niz, part of the code uses features that were introduced in Python 3.8.
As mentioned above, Python 3.6 is not supported and the code may break if you do use it.

Please re-try with Python 3.8 (or higher) and let us know what you encounter then.

**Comment by H4niz** [comment]
Hi @elicn, I meet this exception when run qiling with python 3.8:


```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/h4niz/.local/lib/python3.8/site-packages/qiling/os/linux/thread.py", line 248, in _run
    self.ql.emu_start(start_address, self.exit_point, count=30000)
  File "/home/h4niz/.local/lib/python3.8/site-packages/qiling/core.py", line 883, in emu_start
    raise self._internal_exception
  File "/home/h4niz/.local/lib/python3.8/site-packages/qiling/utils.py", line 159, in wrapper
    return func(*args, **kw)
  File "/home/h4niz/.local/lib/python3.8/site-packages/qiling/core_hooks.py", line 59, in _hook_intr_cb
    raise QlErrorCoreHook("_hook_intr_cb : not handled")
qiling.exception.QlErrorCoreHook: _hook_intr_cb : not handled
2022-04-27T03:07:17Z <QlLinuxMIPS32Thread at 0x7fdb2aef76a0: _run> failed with QlErrorCoreHook

Traceback (most recent call last):
  File "emu.py", line 19, in <module>
    ql.run()
  File "/home/h4niz/.local/lib/python3.8/site-packages/qiling/core.py", line 730, in run
    self.os.run()
  File "/home/h4niz/.local/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 133, in run
    thread_management.run()
  File "/home/h4niz/.local/lib/python3.8/site-packages/qiling/os/linux/thread.py", line 592, in run
    previous_thread = self._prepare_lib_patch()
  File "/home/h4niz/.local/lib/python3.8/site-packages/qiling/os/linux/thread.py", line 573, in _prepare_lib_patch
    gevent.joinall([self.main_thread], raise_error=True)
  File "src/gevent/greenlet.py", line 1057, in gevent._gevent_cgreenlet.joinall
  File "src/gevent/greenlet.py", line 1073, in gevent._gevent_cgreenlet.joinall
  File "src/gevent/greenlet.py", line 371, in gevent._gevent_cgreenlet.Greenlet._raise_exception
  File "/home/h4niz/.local/lib/python3.8/site-packages/gevent/_compat.py", line 65, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/h4niz/.local/lib/python3.8/site-packages/qiling/os/linux/thread.py", line 248, in _run
    self.ql.emu_start(start_address, self.exit_point, count=30000)
  File "/home/h4niz/.local/lib/python3.8/site-packages/qiling/core.py", line 883, in emu_start
    raise self._internal_exception
  File "/home/h4niz/.local/lib/python3.8/site-packages/qiling/utils.py", line 159, in wrapper
    return func(*args, **kw)
  File "/home/h4niz/.local/lib/python3.8/site-packages/qiling/core_hooks.py", line 59, in _hook_intr_cb
    raise QlErrorCoreHook("_hook_intr_cb : not handled")
qiling.exception.QlErrorCoreHook: _hook_intr_cb : not handled
```

Are there guide to fix this issue?

**Comment by xwings** [comment]
Close for now.

We updated the codebase for Qiling and Unicorn since this issue being posted.

Feel free to try the latest version.

**Comment by elicn** [comment]
Hey @H4niz,
It's been a while, but a few fixes were introduced recently to the codebase, that should make it possible now. If this is still relevant, you should give it a shot.
