### ISSUE TITLE
qilong crashes on some dxe files

### ISSUE THREAD

**Issue by kocoman2** [qilingframework/qiling#1235]
possible to fix like how efiperun is substitue dummy protocol?

https://www.youtube.com/watch?v=JbHrwS4PHMY&t=571s
```
[=] 	Initializing EFI_SMM_SW_DISPATCH2_PROTOCOL
[=] 	 | Register                             0x77011010
[=] 	 | UnRegister                           0x77011018
[=] 	
[=] 	Module Section_PE32_image_LenovoSplashDxe_SystemSplashDxe.efi_body.efi loaded to 0x100000
[=] 	Module entry point at 0x100480
[=] 	Initializing EFI_LOADED_IMAGE_PROTOCOL
[=] 	
[=] 	Done loading modules
[=] 	Running from 0x00100480 of Section_PE32_image_LenovoSplashDxe_SystemSplashDxe.efi_body.efi
[=] 	LocateProtocol(Protocol = e6f014ab-cb0e-456e-8af7-7221edb702f7, Registration = NULL, Interface = 0x0507ffe0) = 0x800000000000000e
[x] 	CPU Context:
[x] 	rax = 800000000000000e | r8  = 00000000001009f0 | cs  = 00000000
[x] 	rbx = 0000000000000000 | r9  = 0000000000000010 | ds  = 00000000
[x] 	rcx = 00000000001002c0 | r10 = 0000000000000000 | es  = 00000000
[x] 	rdx = 0000000000000000 | r11 = 0000000000000000 | fs  = 00000000
[x] 	rsi = 0000000000000000 | r12 = 0000000000000000 | gs  = 00000000
[x] 	rdi = 0000000000000000 | r13 = 0000000000000000 | ss  = 00000000
[x] 	rsp = 000000000507ff90 | r14 = 0000000000000000
[x] 	rbp = 000000000507fff0 | r15 = 0000000000000000
[x] 	rip = 00000000001004a9
[x] 	
[x] 	Hexdump:
[x] 	001004a0 :                            4c 8b 5c 24 50 4c 8d
[x] 	001004b0 : 05 3b 05 00 00 49 8b 03 48 8d 0d 31 fe ff ff 33
[x] 	001004c0 : d2 48 89 05 20 05 00 00 48 8b 05 e9 04 00 00 ff
[x] 	001004d0 : 90 40 01 00 00 e8 46 01 00 00 48 85 c0 78 59 48
[x] 	001004e0 : 8b 05 d2 04 00 00 4c 8d 0d                     
[x] 	
[x] 	Disassembly:
[x] 	001004a9 : 4c8b5c2450                    mov        r11, qword ptr [rsp + 0x50]
[x] 	001004ae : 4c8d053b050000                lea        r8, [rip + 0x53b]
[x] 	001004b5 : 498b03                        mov        rax, qword ptr [r11]
[x] 	001004b8 : 488d0d31feffff                lea        rcx, [rip - 0x1cf]
[x] 	001004bf : 33d2                          xor        edx, edx
[x] 	001004c1 : 48890520050000                mov        qword ptr [rip + 0x520], rax
[x] 	001004c8 : 488b05e9040000                mov        rax, qword ptr [rip + 0x4e9]
[x] 	001004cf : ff9040010000                  call       qword ptr [rax + 0x140]
[x] 	
[x] 	PC = 0x001004a9 (Section_PE32_image_LenovoSplashDxe_SystemSplashDxe.efi_body.efi + 0x4a9)
[x] 	
[x] 	Stack:
[x] 	0507ff70 : 0000000000000000
[x] 	0507ff78 : 0000000000000000
[x] 	0507ff80 : 0000000000000000
[x] 	0507ff88 : 00000000001004a9
[x] 	0507ff90 : 0000000000000000 <=
[x] 	0507ff98 : 0000000000000000
[x] 	0507ffa0 : 0000000000000000
[x] 	0507ffa8 : 0000000000000000
[x] 	0507ffb0 : 0000000000000000
[x] 	
[x] 	Memory map:
[x] 	Start        End          Perm    Label         Image
[x] 	0000100000 - 0000101000   rwx     [module]      Section_PE32_image_LenovoSplashDxe_SystemSplashDxe.efi_body.efi
[x] 	0004000000 - 0004001000   rwx     [heap]        
[x] 	0004001000 - 0004011000   rwx     [heap]        
[x] 	0004011000 - 0004012000   rwx     [heap]        
[x] 	0005000000 - 0005080000   rwx     [stack]       
[x] 	0070008000 - 0070010000   ---     [SMRAM SSA]   
[x] 	0077000000 - 0077001000   rwx     [heap]        
[x] 	0077001000 - 0077011000   rwx     [heap]        
[x] 	0077011000 - 0077012000   rwx     [heap]        
[x] 	0077ff0000 - 0078000000   rwx     [stack]       
Traceback (most recent call last):
  File "/qiling-1.4.3/./qltool", line 253, in <module>
    ql.run(timeout=options.timeout)
  File "qiling-1.4.3/qiling/core.py", line 573, in run
    self.os.run()
  File "qiling-1.4.3/qiling/os/uefi/uefi.py", line 222, in run
    self.ql.emu_start(self.ql.loader.entry_point, self.exit_point, self.ql.timeout, self.ql.count)
  File "qiling-1.4.3/qiling/core.py", line 706, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/usr/local/lib/python3.10/site-packages/unicorn-2.0.0-py3.10-macosx-12-x86_64.egg/unicorn/unicorn.py", line 548, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)
```

**Comment by elicn** [comment]
Hi there,
Qiling already lets you define and load your own DXE or SMM protocols, should protocols you need are missing. It also comes with a few common protocols out of the box; see the `uefi_pe.py` file for more context.

This specific piece of code was not designed to address a possibility of a missing protocol: it tries to locate a protocol, but the `LocateProtocol` method returns an `EFI_NOT_FOUND` error. Typically in such cases the `Interface` out parameter (here points to 0x0507ffe0) is not updated and the pointer usually points to NULL. The code that assumes the protocol is always found references that pointer with `mov r11, qword ptr [rsp + 0x50]` (where `rsp` is 0x507ff90, so `rsp+0x50` points to where `Interface` does) and fails when referencing a dangling pointer.

If you want to get this code passed this failing point, you will need to figure out what is the non-standard protocol whose GUID is `e6f014ab-cb0e-456e-8af7-7221edb702f7` (a quick search suggests this is `TpAcpiNvs`), implement the required functionality and install it. Let me know if you need further pointers on this.

**Comment by elicn** [comment]
@kocoman2
Please let me know if you think this is still an issue.
