### ISSUE TITLE
unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)

### ISSUE THREAD

**Issue by KA2010** [qilingframework/qiling#1275]
```python 
#!/usr/bin/env python3

import os
import sys
sys.path.append("..")
from qiling import Qiling
from qiling.const import QL_VERBOSE
import capstone
from capstone.x86_const import *
import collections



cs = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
cs.detail = True

dinst = collections.deque(maxlen=6)

def hook_opcode(ql, address, size):
        global cs
        global dinst
        
        buf = ql.mem.read(address, size)
        instruction = next(cs.disasm(buf, address))
        dinst.append(instruction)

        if instruction.id == X86_INS_CALL:
            for inst in dinst:
                print("disas instruction 0x%x:\t%s\t%s" %(inst.address, inst.mnemonic, inst.op_str))

def hook_mem_invalid(ql: Qiling, access: int, address: int, size: int, value: int):
    print("[Kawkab] hook_mem is called ...")
    print("the address is 0x%x" % address, size)
    PAGE_SIZE = ql.mem.pagesize
    aligned = ql.mem.align(address)
    ql.mem.map(aligned, PAGE_SIZE)
    ql.mem.write(aligned, b'Q' * PAGE_SIZE)
    return True   

if __name__ == "__main__":

    ql = Qiling(["rootfs/x8664_linux/bin/x8664_fuzz"], "rootfs/x8664_linux", verbose=QL_VERBOSE.DEBUG)
    ql.hook_code(hook_opcode)
    ql.hook_mem_invalid(hook_mem_invalid)
    ql.run(begin=0x555555554000+0x122c)
```
## and how I can solve it?

Kawkab Alkhater, [Nov 21, 2022 at 5:29:09 PM]:
[95m[+] [0m Profile: Default
 [95m[+] [0m Map GDT at 0x30000 with GDT_LIMIT=4096
 [95m[+] [0m Write to 0x30018 for new entry b'\x00\xf0\x00\x00\x00\xfeO\x00'
 [95m[+] [0m Write to 0x30028 for new entry b'\x00\xf0\x00\x00\x00\x96O\x00'
 [95m[+] [0m Mapped 0x555555554000-0x555555555000
 [95m[+] [0m Mapped 0x555555555000-0x555555556000
 [95m[+] [0m Mapped 0x555555556000-0x555555557000
 [95m[+] [0m Mapped 0x555555557000-0x555555559000
 [95m[+] [0m mem_start : 0x0
 [95m[+] [0m mem_end   : 0x5000
 [95m[+] [0m Interpreter path: rootfs/x8664_linux/lib64/ld-linux-x86-64.so.2
 [95m[+] [0m Interpreter addr: 0x7ffff7dd5000
 [95m[+] [0m Interpreter size: 0x22a000
 [95m[+] [0m entry point is: 0x7ffff7dd6090
 [95m[+] [0m mmap_address is : 0x7fffb7dd6000
 [95m[+] [0m rel name b'_ITM_deregisterTMCloneTable'
 [95m[+] [0m rel name b'__libc_start_main'
 [95m[+] [0m rel name b'__gmon_start__'
 [95m[+] [0m rel name b'_ITM_registerTMCloneTable'
 [95m[+] [0m rel name b'__cxa_finalize'
 [95m[+] [0m rel name b'strncpy'
 [95m[+] [0m rel name b'__stack_chk_fail'
 [95m[+] [0m rel name b'printf'
 [95m[+] [0m rel name b'malloc'
 [95m[+] [0m rel name b'getc'
 [94m[=] [0m Start      End        Perm    Label          Image
 [94m[=] [0m 00030000 - 00031000   rwx     [GDT]          
 [94m[=] [0m 06000000 - 07400000   rwx     [GS]           
 [94m[=] [0m 555555554000 - 555555555000   r--     rootfs/x8664_linux/bin/x8664_fuzz   rootfs/x8664_linux/bin/x8664_fuzz
 [94m[=] [0m 555555555000 - 555555556000   r-x     rootfs/x8664_linux/bin/x8664_fuzz   rootfs/x8664_linux/bin/x8664_fuzz
 [94m[=] [0m 555555556000 - 555555557000   r--     rootfs/x8664_linux/bin/x8664_fuzz   rootfs/x8664_linux/bin/x8664_fuzz
 [94m[=] [0m 555555557000 - 555555559000   rw-     rootfs/x8664_linux/bin/x8664_fuzz   rootfs/x8664_linux/bin/x8664_fuzz
 [94m[=] [0m 555555559000 - 55555555b000   rwx     [hook_mem]     
 [94m[=] [0m 7ffff7dd5000 - 7ffff7fff000   rwx     /home/kawkab/Alt/Firmware-Fuzzing/examples/rootfs/x8664_linux/lib64/ld-linux-x86-64.so.2   
 [94m[=] [0m 7ffffffde000 - 80000000e000   rwx     [stack]        
 [94m[=] [0m ffffffffff600000 - ffffffffff601000   rwx     [vsyscall]

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "debug_ringbuf_testx8664_linux.py", line 130, in <module>
    ql.run(begin=image_base_addr+main_addr)
  File "/home/kawkab/Alt/Firmware-Fuzzing/examples/../qiling/core.py", line 731, in run
    self.os.run()
  File "/home/kawkab/Alt/Firmware-Fuzzing/examples/../qiling/os/linux/linux.py", line 150, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/kawkab/Alt/Firmware-Fuzzing/examples/../qiling/core.py", line 883, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/home/kawkab/.local/lib/python3.8/site-packages/unicorn/unicorn.py", line 523, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)

**Comment by KA2010** [comment]
note that I implement hook_mem_invalid function in order to solve the issues but no success!!!

**Comment by elicn** [comment]
Hi there,
Two notes on the code above:
1. Specifying the `begin` argument on `ql.run` is a bit misleading, because it does not set the program counter to start there. Before calling `ql.run` set the program counter to the same value, i.e.: `ql.arch.regs.arch_pc = 0x555555554000 + 0x122c` 
2. Your implementation to `hook_mem_invalid` suggests that you want to handle accesses to unmapped memory. If that is the case, then that hook type is too general and will pick up any kind of invalid memory access. You may want to use a more adequate hook type, like `hook_mem_unmapped`

**Comment by KA2010** [comment]
"will pick up any kind of invalid memory access"
Actually that what I am trying to do as some time I got Invalid memory fetch, raed or write.

**Comment by KA2010** [comment]
I have apply your suggestions but with no success 
```python 
#!/usr/bin/env python3

import os
import sys
sys.path.append("..")
from qiling import Qiling
from qiling.const import QL_VERBOSE
import capstone
from capstone.x86_const import *
import collections



cs = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
cs.detail = True

dinst = collections.deque(maxlen=6)

def hook_opcode(ql, address, size):
        global cs
        global dinst
        
        buf = ql.mem.read(address, size)
        instruction = next(cs.disasm(buf, address))
        dinst.append(instruction)

        if instruction.id == X86_INS_CALL:
            for inst in dinst:
                print("disas instruction 0x%x:\t%s\t%s" %(inst.address, inst.mnemonic, inst.op_str))

def hook_mem_unmapped(ql: Qiling, access: int, address: int, size: int, value: int):
    print("[Kawkab] hook_mem is called ...")
    print("the address is 0x%x" % address, size)
    PAGE_SIZE = ql.mem.pagesize
    aligned = ql.mem.align(address)
    ql.mem.map(aligned, PAGE_SIZE)
    ql.mem.write(aligned, b'Q' * PAGE_SIZE)
    return True   

if __name__ == "__main__":

    ql = Qiling(["rootfs/x8664_linux/bin/x8664_fuzz"], "rootfs/x8664_linux", verbose=QL_VERBOSE.DEBUG)
    ql.hook_code(hook_opcode)
    ql.hook_mem_unmapped(hook_mem_unmapped)
    ql.reg.arch_pc = 0x555555554000 + 0x122c
    ql.run(begin = ql.reg.arch_pc)
```
this time is gave me Invalid memory write
Traceback (most recent call last):
  File "testx8664_linux.py", line 72, in <module>
    ql.run(begin = ql.reg.arch_pc)
  File "/home/kawkab/Alt/Firmware-Fuzzing/examples/../qiling/core.py", line 731, in run
    self.os.run()
  File "/home/kawkab/Alt/Firmware-Fuzzing/examples/../qiling/os/linux/linux.py", line 150, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/kawkab/Alt/Firmware-Fuzzing/examples/../qiling/core.py", line 883, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/home/kawkab/.local/lib/python3.8/site-packages/unicorn/unicorn.py", line 523, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)

**Comment by elicn** [comment]
You've been using `ql.reg.arch_pc` instead of `ql.arch.regs.arch_pc`.
I have no idea how you even managed to get that far..

**Comment by KA2010** [comment]
> You've been using `ql.reg.arch_pc` instead of `ql.arch.regs.arch_pc`. I have no idea how your emulation even started..

because when I did 

> ql.arch.regs.arch_pc
it gave me 
Traceback (most recent call last):
  File "testx8664_linux.py", line 71, in <module>
    ql.arch.regs.arch_pc = 0x555555554000 + 0x122c
AttributeError: 'QlArchX8664' object has no attribute 'regs'
for this I used 

> ql.reg.arch_pc

**Comment by elicn** [comment]
You have a quite outdated version of Qiling.. you should get it up to date.

**Comment by KA2010** [comment]
> You have a quite outdated version of Qiling.. you should get it up to date.

I have updated and use `ql.arch.regs.arch_pc` still giving me invalid memory fetch

**Comment by elicn** [comment]
This is not a bug, but an expected behavior when you set the program counter to an arbitrary address without setting up other registers appropriately.

Jumping into a function without properly setting the stack pointer, stack content and args registers would always end up in a failure.

Please follow the instructions trace to see what gets accessed and patch your script accordingly.

**Comment by KA2010** [comment]
> This is not a bug, but an expected behavior when you set the program counter to an arbitrary address without setting up other registers appropriately.
> 
> Jumping into a function without properly setting the stack pointer, stack content and args registers would always end up in a failure.
> 
> Please follow the instructions trace to see what gets accessed and patch your script accordingly.

Is there is any examples that I can get better idea, I am not getting what I suppose to do, I traced the instructions but I did not get where failure specially happen.

**Comment by elicn** [comment]
Closing this for now; let's continue this discussion on the TG channel.
