### ISSUE TITLE
windows emulation fail

### ISSUE THREAD

**Issue by cv6k** [qilingframework/qiling#1323]
***Describe the bug**
When trying to emulate a simple windows c++ binary, qiling cannot fire up the fs
i used dllcollector.bat to collect all necessary dlls for the fs

**Sample Code**
```python
from qiling import Qiling

filename=["./echo.pe.exe"] 
rootfs="./rootfs_win10/x86_windows"

ql= Qiling(filename, rootfs )

ql.run()

```

**Expected behavior**
no errors

**Additional context**
error output
```
[=] 	Initiate stack address at 0x7ffffffde000 
[=] 	Loading ./echo.exe to 0x140000000
[=] 	PE entry point at 0x1400013f0
[=] 	TEB is at 0x6000000
[=] 	PEB is at 0x60001f0
[=] 	LDR is at 0x60009c0
[=] 	Loading ntdll.dll ...
[=] 	Done loading ntdll.dll
[=] 	Loading kernel32.dll ...
[=] 	Loading kernelbase.dll ...
[=] 	Done loading kernelbase.dll
[=] 	Done loading kernel32.dll
[=] 	Loading mscoree.dll ...
[=] 	Calling mscoree.dll DllMain at 0x1024f100
[x] 	Error encountered while running mscoree.dll DllMain, bailing
[=] 	Done loading mscoree.dll
[=] 	Loading ucrtbase.dll ...
[=] 	Calling ucrtbase.dll DllMain at 0x102aba30
[x] 	Error encountered while running ucrtbase.dll DllMain, bailing
[=] 	Done loading ucrtbase.dll
[=] 	Loading msvcrt.dll ...
[=] 	Calling msvcrt.dll DllMain at 0x103d5ac0
[x] 	Error encountered while running msvcrt.dll DllMain, bailing
[=] 	Done loading msvcrt.dll
[=] 	_initterm(pfbegin = 0x140009018, pfend = 0x140009028) = 0x0
[=] 	_initterm(pfbegin = 0x140009000, pfend = 0x140009010) = 0x0
[=] 	SetUnhandledExceptionFilter(lpTopLevelExceptionFilter = 0x140001d10) = 0x0
[=] 	malloc(size = 0x8) = 0x500000d37
[=] 	_onexit(function = 0x140001440) = 0x500000d3f
[=] 	_onexit(function = 0x1400014c0) = 0x500000d47
[!] 	api _read (msvcrt) is not implemented
[x] 	CPU Context:
[x] 	ah	: 0xbf
[x] 	al	: 0x4c
[x] 	ch	: 0x0
[x] 	cl	: 0x0
[x] 	dh	: 0xcb
[x] 	dl	: 0x68
[x] 	bh	: 0x0
[x] 	bl	: 0x0
[x] 	ax	: 0xbf4c
[x] 	cx	: 0x0
[x] 	dx	: 0xcb68
[x] 	bx	: 0x0
[x] 	sp	: 0xbcc
[x] 	bp	: 0xcb28
[x] 	si	: 0x7048
[x] 	di	: 0xd37
[x] 	ip	: 0xcc1e
[x] 	eax	: 0x103ebf4c
[x] 	ecx	: 0x0
[x] 	edx	: 0x1cb68
[x] 	ebx	: 0x0
[x] 	esp	: 0xefc30bcc
[x] 	ebp	: 0x1cb28
[x] 	esi	: 0x40007048
[x] 	edi	: 0xd37
[x] 	eip	: 0x103fcc1e
[x] 	rax	: 0x103ebf4c
[x] 	rbx	: 0x0
[x] 	rcx	: 0x0
[x] 	rdx	: 0x80000001cb68
[x] 	rsi	: 0x140007048
[x] 	rdi	: 0x500000d37
[x] 	rbp	: 0x1cb28
[x] 	rsp	: 0xefc30bcc
[x] 	r8	: 0x400
[x] 	r9	: 0x0
[x] 	r10	: 0x0
[x] 	r11	: 0x0
[x] 	r12	: 0x0
[x] 	r13	: 0x0
[x] 	r14	: 0x0
[x] 	r15	: 0x0
[x] 	rip	: 0x103fcc1e
[x] 	cr0	: 0x11
[x] 	cr1	: 0x0
[x] 	cr2	: 0x0
[x] 	cr3	: 0x0
[x] 	cr4	: 0x0
[x] 	cr8	: 0x0
[x] 	dr0	: 0x0
[x] 	dr1	: 0x0
[x] 	dr2	: 0x0
[x] 	dr3	: 0x0
[x] 	dr4	: 0x0
[x] 	dr5	: 0x0
[x] 	dr6	: 0xffff0ff0
[x] 	dr7	: 0x400
[x] 	st0	: 0x0
[x] 	st1	: 0x0
[x] 	st2	: 0x0
[x] 	st3	: 0x0
[x] 	st4	: 0x0
[x] 	st5	: 0x0
[x] 	st6	: 0x0
[x] 	st7	: 0x0
[x] 	eflags	: 0x97
[x] 	cs	: 0x33
[x] 	ss	: 0x28
[x] 	ds	: 0x0
[x] 	es	: 0x0
[x] 	fs	: 0x0
[x] 	gs	: 0x0
[x] 	r8b	: 0x0
[x] 	r9b	: 0x0
[x] 	r10b	: 0x0
[x] 	r11b	: 0x0
[x] 	r12b	: 0x0
[x] 	r13b	: 0x0
[x] 	r14b	: 0x0
[x] 	r15b	: 0x0
[x] 	r8w	: 0x400
[x] 	r9w	: 0x0
[x] 	r10w	: 0x0
[x] 	r11w	: 0x0
[x] 	r12w	: 0x0
[x] 	r13w	: 0x0
[x] 	r14w	: 0x0
[x] 	r15w	: 0x0
[x] 	r8d	: 0x400
[x] 	r9d	: 0x0
[x] 	r10d	: 0x0
[x] 	r11d	: 0x0
[x] 	r12d	: 0x0
[x] 	r13d	: 0x0
[x] 	r14d	: 0x0
[x] 	r15d	: 0x0
[x] 	fsbase	: 0x6000
[x] 	gsbase	: 0x6000000
[x] 	xmm0	: 0x0
[x] 	xmm1	: 0x0
[x] 	xmm2	: 0x0
[x] 	xmm3	: 0x0
[x] 	xmm4	: 0x0
[x] 	xmm5	: 0x0
[x] 	xmm6	: 0x0
[x] 	xmm7	: 0x0
[x] 	xmm8	: 0x0
[x] 	xmm9	: 0x0
[x] 	xmm10	: 0x0
[x] 	xmm11	: 0x0
[x] 	xmm12	: 0x0
[x] 	xmm13	: 0x0
[x] 	xmm14	: 0x0
[x] 	xmm15	: 0x0
[x] 	xmm16	: 0x0
[x] 	xmm17	: 0x0
[x] 	xmm18	: 0x0
[x] 	xmm19	: 0x0
[x] 	xmm20	: 0x0
[x] 	xmm21	: 0x0
[x] 	xmm22	: 0x0
[x] 	xmm23	: 0x0
[x] 	xmm24	: 0x0
[x] 	xmm25	: 0x0
[x] 	xmm26	: 0x0
[x] 	xmm27	: 0x0
[x] 	xmm28	: 0x0
[x] 	xmm29	: 0x0
[x] 	xmm30	: 0x0
[x] 	xmm31	: 0x0
[x] 	ymm0	: 0x0
[x] 	ymm1	: 0x0
[x] 	ymm2	: 0x0
[x] 	ymm3	: 0x0
[x] 	ymm4	: 0x0
[x] 	ymm5	: 0x0
[x] 	ymm6	: 0x0
[x] 	ymm7	: 0x0
[x] 	ymm8	: 0x0
[x] 	ymm9	: 0x0
[x] 	ymm10	: 0x0
[x] 	ymm11	: 0x0
[x] 	ymm12	: 0x0
[x] 	ymm13	: 0x0
[x] 	ymm14	: 0x0
[x] 	ymm15	: 0x0
[x] 	ymm16	: 0x0
[x] 	ymm17	: 0x0
[x] 	ymm18	: 0x0
[x] 	ymm19	: 0x0
[x] 	ymm20	: 0x0
[x] 	ymm21	: 0x0
[x] 	ymm22	: 0x0
[x] 	ymm23	: 0x0
[x] 	ymm24	: 0x0
[x] 	ymm25	: 0x0
[x] 	ymm26	: 0x0
[x] 	ymm27	: 0x0
[x] 	ymm28	: 0x0
[x] 	ymm29	: 0x0
[x] 	ymm30	: 0x0
[x] 	ymm31	: 0x0
[x] 	zmm0	: 0x0
[x] 	zmm1	: 0x0
[x] 	zmm2	: 0x0
[x] 	zmm3	: 0x0
[x] 	zmm4	: 0x0
[x] 	zmm5	: 0x0
[x] 	zmm6	: 0x0
[x] 	zmm7	: 0x0
[x] 	zmm8	: 0x0
[x] 	zmm9	: 0x0
[x] 	zmm10	: 0x0
[x] 	zmm11	: 0x0
[x] 	zmm12	: 0x0
[x] 	zmm13	: 0x0
[x] 	zmm14	: 0x0
[x] 	zmm15	: 0x0
[x] 	zmm16	: 0x0
[x] 	zmm17	: 0x0
[x] 	zmm18	: 0x0
[x] 	zmm19	: 0x0
[x] 	zmm20	: 0x0
[x] 	zmm21	: 0x0
[x] 	zmm22	: 0x0
[x] 	zmm23	: 0x0
[x] 	zmm24	: 0x0
[x] 	zmm25	: 0x0
[x] 	zmm26	: 0x0
[x] 	zmm27	: 0x0
[x] 	zmm28	: 0x0
[x] 	zmm29	: 0x0
[x] 	zmm30	: 0x0
[x] 	zmm31	: 0x0
[x] 	Hexdump:
[x] 	53 56 57 a1 60 4f 45 10
[x] 	Disassembly:
[=] 	00000000103fcc1e [msvcrt.dll           + 0x05cc1e]  53                   push                 rbx
[=] 	00000000103fcc1f [msvcrt.dll           + 0x05cc1f]  56                   push                 rsi
[=] 	00000000103fcc20 [msvcrt.dll           + 0x05cc20]  57                   push                 rdi
[=] 	00000000103fcc21 [msvcrt.dll           + 0x05cc21]  a1 60 4f 45 10 31 45 fc 33 movabs               eax, dword ptr [0x33fc453110454f60]
[x] 	PC = 0x00000000103fcc1e (./qiling/rootfs_win10/x86_windows/Windows/System32/msvcrt.dll + 0x5cc1e)

[x] 	Memory map:
[x] 	Start            End              Perm    Label                 Image
[x] 	00000000006000 - 0000000000c000   rwx     [FS]                  
[x] 	00000000030000 - 00000000031000   rwx     [GDT]                 
[x] 	00000006000000 - 00000007400000   rwx     [GS]                  
[x] 	00000010000000 - 0000001021c000   rwx     kernelbase.dll        ./qiling/rootfs_win10/x86_windows/Windows/System32/KernelBase.dll
[x] 	00000010220000 - 00000010272000   rwx     mscoree.dll           ./qiling/rootfs_win10/x86_windows/Windows/System32/mscoree.dll
[x] 	00000010280000 - 000000103a0000   rwx     ucrtbase.dll          ./qiling/rootfs_win10/x86_windows/Windows/System32/ucrtbase.dll
[x] 	000000103a0000 - 0000001045f000   rwx     msvcrt.dll            ./qiling/rootfs_win10/x86_windows/Windows/System32/msvcrt.dll
[x] 	0000004b280000 - 0000004b424000   rwx     ntdll.dll             ./qiling/rootfs_win10/x86_windows/Windows/System32/ntdll.dll
[x] 	0000006b800000 - 0000006b8f0000   rwx     kernel32.dll          ./qiling/rootfs_win10/x86_windows/Windows/System32/kernel32.dll
[x] 	0000007ffe0000 - 0000007ffe1000   rwx     [kuser shared data]   
[x] 	00000140000000 - 00000140023000   rwx     echo.exe           ./qiling/echo.exe
[x] 	00000500000000 - 00000500001000   rwx     [heap]                
[x] 	007ffffffde000 - 0080000001e000   rwx     [stack]               
Traceback (most recent call last):
  File "solve.py", line 16, in <module>
    ql.run()
  File "/usr/local/lib/python3.8/dist-packages/qiling/core.py", line 582, in run
    self.os.run()
  File "/usr/local/lib/python3.8/dist-packages/qiling/os/windows/windows.py", line 219, in run
    self.ql.emu_start(entry_point, exit_point, self.ql.timeout, self.ql.count)
  File "/usr/local/lib/python3.8/dist-packages/qiling/core.py", line 753, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn.py", line 547, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)
```

**Comment by pxqlinux** [comment]
I have the same problem too

**Comment by chinggg** [comment]
Hi! I just tried `examples/hello_x8664_windows_customapi.py` and there is no error. It seems you are emulating a custom compiled "echo" PE binary, can you provide the file for our dev to reproduce the error?

**Comment by cv6k** [comment]
anything compiled with visual studio ++ and mingw have same problems

**Comment by cv6k** [comment]
[test.exe.zip](https://github.com/qilingframework/qiling/files/11007479/test.exe.zip)

attached example binary

**Comment by xwings** [comment]
there are way too many API we need to implement. from your log this is one of those.

api _read (msvcrt) is not implemented

this should be the one stopping it from running. you are always welcome to PR those missing Windows API call.
