### ISSUE TITLE
tendaac15 example error

### ISSUE THREAD

**Issue by 10cks** [qilingframework/qiling#1350]
Bug:
When I test `qiling/examples/fuzzing/tenda_ac15/saver_tendaac15_httpd.py`, it cant correctly run in my computer.

My env:
```
$uname -a
Linux ubuntu 5.15.0-72-generic #79~20.04.1-Ubuntu SMP Thu Apr 20 22:12:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ id
uid=1000(ubuntu) gid=1000(ubuntu) groups=1000(ubuntu),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),132(lxd),133(sambashare)
$ python
Python 3.8.16 (default, Mar  2 2023, 03:21:46) 
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
$ clang --version
Ubuntu clang version 12.0.0-3ubuntu1~20.04.5
```

Debug info:

```
[+] 	socket(AF_INET, SOCK_DGRAM, 0) = 3
[+] 	0x90226fb4: socket(domain = 0x2, socktype = 0x2, protocol = 0x0) = 0x3
[+] 	Received interrupt: 0x2
[+] 	the underlying ioctl raised an exception: No such device
[+] 	0x901eb308: ioctl(fd = 0x3, cmd = 0x8915, arg = 0x7ff3cd14) = -0x1 (EPERM)
[+] 	Received interrupt: 0x2
[+] 	0x901ea670: close(fd = 0x3) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901ecd68: rt_sigaction(signum = 0x11, act = 0x0, oldact = 0x7ff3cd24) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901ec9d8: rt_sigprocmask(how = 0x0, nset = 0x7ff3cd38, oset = 0x7ff3cd38, sigsetsize = 0x8) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901eb890: nanosleep(req = 0x7ff3cd40, rem = 0x7ff3cd40) = 0x0
[+] 	Received interrupt: 0x2
[+] 	Converted emulated socket type 2 to host socket type 2
[+] 	socket(AF_INET, SOCK_DGRAM, 0) = 3
[+] 	0x90226fb4: socket(domain = 0x2, socktype = 0x2, protocol = 0x0) = 0x3
[+] 	Received interrupt: 0x2
[+] 	the underlying ioctl raised an exception: No such device
[+] 	0x901eb308: ioctl(fd = 0x3, cmd = 0x8915, arg = 0x7ff3cd14) = -0x1 (EPERM)
[+] 	Received interrupt: 0x2
[+] 	0x901ea670: close(fd = 0x3) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901ecd68: rt_sigaction(signum = 0x11, act = 0x0, oldact = 0x7ff3cd24) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901ec9d8: rt_sigprocmask(how = 0x0, nset = 0x7ff3cd38, oset = 0x7ff3cd38, sigsetsize = 0x8) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901eb890: nanosleep(req = 0x7ff3cd40, rem = 0x7ff3cd40) = 0x0
[+] 	Received interrupt: 0x2
[+] 	Converted emulated socket type 2 to host socket type 2
[+] 	socket(AF_INET, SOCK_DGRAM, 0) = 3
[+] 	0x90226fb4: socket(domain = 0x2, socktype = 0x2, protocol = 0x0) = 0x3
[+] 	Received interrupt: 0x2
[+] 	the underlying ioctl raised an exception: No such device
[+] 	0x901eb308: ioctl(fd = 0x3, cmd = 0x8915, arg = 0x7ff3cd14) = -0x1 (EPERM)
[+] 	Received interrupt: 0x2
[+] 	0x901ea670: close(fd = 0x3) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901ecd68: rt_sigaction(signum = 0x11, act = 0x0, oldact = 0x7ff3cd24) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901ec9d8: rt_sigprocmask(how = 0x0, nset = 0x7ff3cd38, oset = 0x7ff3cd38, sigsetsize = 0x8) = 0x0
[+] 	Received interrupt: 0x2
```

you can see `0x901eb308: ioctl(fd = 0x3, cmd = 0x8915, arg = 0x7ff3cd14) = -0x1 (EPERM)`, preliminarily I think it's a lack of authority, so I change to root run this script, the mistakes that happen are the same.

**Comment by 10cks** [comment]
add debug info:
```
[+] 	0x900502ec: write(fd = 0x2, buf = 0x7ff3c79f, count = 0x1) = 0x1
[+] 	Received interrupt: 0x2
[+] 	0x901f225c: wait4(pid = 0xcaf, wstatus = 0x7ff3c37c, options = 0x0, rusage = 0x0) = 0xcaf
[+] 	Received interrupt: 0x2
[+] 	0x901f1d68: rt_sigaction(signum = 0x3, act = 0x7ff3c2cc, oldact = 0x7ff3c320) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901f1d68: rt_sigaction(signum = 0x2, act = 0x7ff3c2cc, oldact = 0x7ff3c320) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901f1d68: rt_sigaction(signum = 0x11, act = 0x7ff3c2cc, oldact = 0x7ff3c320) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901f0130: ugetrlimit(res = 0x4, rlim = 0x7ff3cd38) = 0x0
[+] 	Received interrupt: 0x2
[+] 	write() CONTENT: b'init_core_dump 1898: rlim_cur = 5242880, rlim_max = 5242880\n'
init_core_dump 1898: rlim_cur = 5242880, rlim_max = 5242880
[+] 	0x901f22ec: write(fd = 0x1, buf = 0x9024a648, count = 0x3c) = 0x3c
[+] 	Received interrupt: 0x2
[+] 	write() CONTENT: b'\n\nYes:\n\n      ****** WeLoveLinux****** \n\n Welcome to ...'


Yes:

      ****** WeLoveLinux****** 

 Welcome to ...[+] 	0x901f22ec: write(fd = 0x1, buf = 0x9024a648, count = 0x38) = 0x38
[+] 	Received interrupt: 0x2
[+] 	write() CONTENT: b'\n'

[+] 	0x901f22ec: write(fd = 0x1, buf = 0x9024a648, count = 0x1) = 0x1
[+] 	Received interrupt: 0x2
[+] 	0x901f1d68: rt_sigaction(signum = 0xa, act = 0x7ff3ccb4, oldact = 0x7ff3cd08) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901f1d68: rt_sigaction(signum = 0xc, act = 0x7ff3ccb4, oldact = 0x7ff3cd08) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901f1d68: rt_sigaction(signum = 0xf, act = 0x7ff3ccb4, oldact = 0x7ff3cd08) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901f1d68: rt_sigaction(signum = 0xd, act = 0x7ff3ccb4, oldact = 0x7ff3cd08) = 0x0
```

**Comment by elicn** [comment]
Hi there,
A few questions here, just to make sure we are on the same page:

1. Did you follow the instructions on the top of the Python file?
2. Have you tried to run the Tenda example? (it is basically the same code, but without the fuzzing)
3. What Qiling version are you running?
    - If from git, can you provide the output of `git branch -v | grep '*'` ?

**Comment by 10cks** [comment]
1. I followed  the instructions on the top of the Python file, every steps.
```
# 1. Download AC15 Firmware from https://down.tenda.com.cn/uploadfile/AC15/US_AC15V1.0BR_V15.03.05.19_multi_TD01.zip
# 2. unzip
# 3. binwalk -e US_AC15V1.0BR_V15.03.05.19_multi_TD01.bin
# 4. locate squashfs-root
# 5. rm -rf webroot && mv webroot_ro webroot
#
# notes: we are using rootfs in this example, so rootfs = squashfs-root
# 
```
2. I don't test the Tenda, follow your advice I test `test_tendaac15_httpd.py`, it's also failed.
```
$ python test_tendaac15_httpd.py 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-2:
    self.run()
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "test_tendaac15_httpd.py", line 38, in nvram_listener
    sock.bind(server_address)  
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/threading.py", line 932, in _bootstrap_inner
/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/threading.py:934: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
  self._invoke_excepthook(self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
    self.run()
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "test_tendaac15_httpd.py", line 61, in my_tenda
    ql = Qiling(["../examples/rootfs/arm_tendaac15/bin/httpd"], "../examples/rootfs/arm_tendaac15", verbose=QL_VERBOSE.DEBUG)
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/site-packages/qiling/core.py", line 97, in __init__
    raise QlErrorFileNotFound(f'Target binary not found: "{argv[0]}"')
qiling.exception.QlErrorFileNotFound: Target binary not found: "../examples/rootfs/arm_tendaac15/bin/httpd"
E
======================================================================
ERROR: test_tenda_ac15_arm (__main__.ELFTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_tendaac15_httpd.py", line 87, in test_tenda_ac15_arm
    conn.request('POST', '/goform/addressNat', json_data, headers)
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/ubuntu/anaconda3/envs/qiling/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

----------------------------------------------------------------------
Ran 1 test in 5.012s

FAILED (errors=1)
```
3. this is my qiling version.
```
 $ git branch -v | grep '*'
* master d921cb21 Merge pull request #1299 from qilingframework/dev
```

this is my directory structure:
```bash
(qiling) ubuntu@ubuntu:~/Desktop/TD01$ tree _US_AC15V1.0BR_V15.03.05.19_multi_TD01.bin.extracted/ -L 2
_US_AC15V1.0BR_V15.03.05.19_multi_TD01.bin.extracted/
├── 1C9E98.squashfs
├── 5C
├── 5C.7z
├── _5C.extracted
│   ├── 1F000.cpio
│   ├── 32F5B
│   ├── 32F5B.7z
│   ├── 3D3C9A.xz
│   ├── 44E327
│   ├── 44E327.7z
│   └── cpio-root
├── addressNat_overflow.sh
├── rootfs
│   ├── bin
│   ├── cfg
│   ├── dev
│   ├── etc -> /var/etc
│   ├── etc_ro
│   ├── home -> /var/home
│   ├── init -> bin/busybox
│   ├── lib
│   ├── mnt
│   ├── proc
│   ├── qemu-arm-static
│   ├── root -> /var/root
│   ├── saver_tendaac15_httpd.py
│   ├── sbin
│   ├── sys
│   ├── tmp
│   ├── usr
│   ├── var
│   └── webroot
├── run_2.py
├── saver_tendaac15_httpd.py
└── test_tendaac15_httpd.py

16 directories, 19 files
```

**Comment by elicn** [comment]
OK.
Can you switch to `dev` branch ( `git checkout dev` ) and re-try?
Also, please make sure to run the Tenda _example_, not the _test_.

If that fails too, I will author a new script instead.

**Comment by 10cks** [comment]
I use `git checkout dev` switch to dev, then I run the `tendaac1518_httpd.py`, I got failed similar with `saver_tendaac15_httpd.py`

```
[+] 	0x901ecd68: rt_sigaction(signum = 0x11, act = 0x0, oldact = 0x7ff3cd24) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901ec9d8: rt_sigprocmask(how = 0x0, nset = 0x7ff3cd38, oset = 0x7ff3cd38, sigsetsize = 0x8) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901eb890: nanosleep(req = 0x7ff3cd40, rem = 0x7ff3cd40) = 0x0
[+] 	Received interrupt: 0x2
[+] 	Converted emulated socket type 2 to host socket type 2
[+] 	socket(AF_INET, SOCK_DGRAM, 0) = 3
[+] 	0x90226fb4: socket(domain = 0x2, socktype = 0x2, protocol = 0x0) = 0x3
[+] 	Received interrupt: 0x2
[+] 	the underlying ioctl raised an exception: No such device
[+] 	0x901eb308: ioctl(fd = 0x3, cmd = 0x8915, arg = 0x7ff3cd14) = -0x1 (EPERM)
[+] 	Received interrupt: 0x2
[+] 	0x901ea670: close(fd = 0x3) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901ecd68: rt_sigaction(signum = 0x11, act = 0x0, oldact = 0x7ff3cd24) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x901ec9d8: rt_sigprocmask(how = 0x0, nset = 0x7ff3cd38, oset = 0x7ff3cd38, sigsetsize = 0x8) = 0x0
[+] 	Received interrupt: 0x2
```
maybe this is other version ? I used firmware is US_AC15V1.0BR_V15.03.05.19_multi_TD01,  dev script maybe need tendaac1518, I don't know if that has anything to do with it.

**Comment by 10cks** [comment]
I think this is the real reason
```
[+] 	rel name b'tpi_ip_opt_set'
[+] 	rel name b'strcpy'
[+] 	rel name b'kill'
[+] 	rel name b'__deregister_frame_info'
[+] 	rel name b'check_fw_only'
[+] 	rel name b'tpi_syslog_get_lists'
[+] 	rel name b'shutdown'
[+] 	Received interrupt: 0x2
[+] 	0x047bb438: mmap2(addr = 0x0, length = 0x1000, prot = 0x3, flags = 0x4000022, fd = 0xffffffff, pgoffset = 0x0) = 0x90000000
[+] 	Received interrupt: 0x2
[+] 	open(/lib/libCfm.so, 0o0) = 3
[+] 	File found: /home/ubuntu/Desktop/TD01/_US_AC15V1.0BR_V15.03.05.19_multi_TD01.bin.extracted/rootfs/lib/libCfm.so
[+] 	0x047bbd64: open(filename = 0x7ff3c348, flags = 0x0, mode = 0x0) = 0x3
[+] 	Received interrupt: 0x2
[+] 	0x047bbda8: fstat(fd = 0x3, buf_ptr = 0x7ff3c2e0) = 0x0
[+] 	Received interrupt: 0x2
[+] 	0x047bbe78: mmap2(addr = 0x0, length = 0x1000, prot = 0x3, flags = 0x4000022, fd = 0xffffffff, pgoffset = 0x0) = 0x90001000
[+] 	Received interrupt: 0x2
[+] 	read() CONTENT: b'\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00(\x00\x01\x00\x00\x00\xe81\x00\x004\x00\x00\x00\xec\xe7\x01\x00\x02\x00\x00\x054\x00 \x00\x04\x00(\x00"\x00\x1f\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb4\xef\x00\x00\xb4\xef\x00\x00\x05\x00\x00\x00\x00\x80\x00\x00\x01\x00\x00\x00\x00\xf0\x00\x00\x00p\x01\x00\x00p\x01\x00<\x08\x00\x00h\xb0\x01\x00\x06\x00\x00\x00\x00\x80\x00\x00\x02\x00\x00\x00\x0c\xf0\x00\x00\x0cp\x01\x00\x0cp\x01\x00\xd0\x00\x00\x00\xd0\x00\x00\x00\x06\x00\x00\x00\x04\x00\x00\x00Q\xe5td\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x04\x00\x00\x00\xc5\x00\x00\x00\xd5\x00\x00\x00\xc2\x00\x00\x00\xd3\x00\x00\x00\x00\x00\x00\x00\xad\x00\x00\x00v\x00\x00\x00\xb3\x00\x00\x00\x0e\x00\x00\x00\xb8\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x15\x00\x00\x00\x9c\x00\x00\x00\x85\x00\x00\x00d\x00\x00\x00\x90\x00\x00\x00\x00\x00\x00\x00O\x00\x00\x00\x1b\x00\x00\x00\xd0\x00\x00\x00w\x00\x00\x00\xba\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xbd\x00\x00\x00\x83\x00\x00\x00\x9a\x00\x00\x00{\x00\x00\x00\xc5\x00\x00\x0...
```
I don't understand why it happens ' Received interrupt: 0x2'.

**Comment by elicn** [comment]
I don't understand the problem. What are you expecting it to do which it doesn't?
Interrupt 2 is the way system called are invoked there; this is perfectly fine.

**Comment by Riv4ille** [comment]
###   init_core_dump(v3);
  puts("\n\nYes:\n\n      ****** WeLoveLinux****** \n\n Welcome to ...");
  sub_30A5C();
  while ( check_network(v21) <= 0 )
    sleep(1u);

Perhaps it has entered into an infinite loop here.
My solution is to hook the check_network function in the script.

### def hook_check_network(ql:Qiling):
    ql.arch.regs.r0 = 1
    
def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, verbose=QL_VERBOSE.DEBUG)
    ql.os.set_api('check_network',hook_check_network)
    ql.add_fs_mapper("/dev/urandom","/dev/urandom")
    ql.hook_address(patcher, ql.loader.elf_entry)

**Comment by Riv4ille** [comment]
My solution is to hook the check_network function in the script.
`def hook_check_network(ql:Qiling):
    ql.arch.regs.r0 = 1
    
def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, verbose=QL_VERBOSE.DEBUG)
    ql.os.set_api('check_network',hook_check_network)
    ql.add_fs_mapper("/dev/urandom","/dev/urandom")
    ql.hook_address(patcher, ql.loader.elf_entry)`

**Comment by Riv4ille** [comment]
Perhaps it has entered into an infinite loop here.
```C
  init_core_dump(v3);
  puts("\n\nYes:\n\n      ****** WeLoveLinux****** \n\n Welcome to ...");
  sub_30A5C();
  while ( check_network(v21) <= 0 )
    sleep(1u);
```
My solution is to hook the check_network function in the script.
```python
def hook_check_network(ql:Qiling):
    ql.arch.regs.r0 = 1
    
def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, verbose=QL_VERBOSE.DEBUG)
    ql.os.set_api('check_network',hook_check_network)
    ql.add_fs_mapper("/dev/urandom","/dev/urandom")
    ql.hook_address(patcher, ql.loader.elf_entry)
```

**Comment by xwings** [comment]
problem fix and issue closed.
