### ISSUE TITLE
failed in emulate dlink DIR823G_V1.0.2B05 goahead in thread mode while it works as i use gdb attach the process and hook fork

### ISSUE THREAD

**Issue by DockTree** [qilingframework/qiling#1357]
***Describe the bug**
failed in emulate dlink DIR823G_V1.0.2B05 goahead in thread mode while it works as i use gdb attach the process

**Sample Code**
```python
from qiling import *
from qiling.const import QL_VERBOSE

def hook_v0(ql):
    ql.arch.regs.v0 = 1

def hook_v0_0(ql):
    ql.arch.regs.v0 = 0

def fake_daemon(ql):
    return 0

def new_apmib_get(ql):
    return 0

if __name__ == "__main__":
    ql = Qiling(r'bin/goahead'.split(), r'./', multithread=True)#, verbose=QL_VERBOSE.DEBUG)
    ql.hook_address(hook_v0, 0x423bb8)
    ql.hook_address(hook_v0_0, 0x419ca0)
    ql.hook_address(hook_v0_0, 0x41bb08)
    ql.os.set_api('apmib_get', new_apmib_get)
    #ql.os.set_api('fork', fake_daemon)
    #ql.os.set_api('daemon', fake_daemon)
    #ql.debugger = "gdb:127.0.0.1:8888"
    ql.run()
```

**Screenshots**
![image](https://github.com/qilingframework/qiling/assets/104353991/6bfb0ffd-4a49-4f29-85f2-7dc363f3a21f)
```
[+] [Thread 684]        Scheduled from 0x9001fe18.
[+] [Thread 684]        Received interrupt: 0xc
[+] [Thread 684]        [Thread Manager] Stop the world.
[+] [Thread 684]        [Thread Manager] Thread IDs: {683, 684}
[+] [Thread 684]        [Thread Manager] Thread IDs: {683}
[+] [Thread 684]        [Thread Manager] Thread IDs: set()
[+] [Thread 684]        [Thread Manager] Stop the world.
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/games/qilingenv/lib/python3.10/site-packages/qiling/os/linux/thread.py", line 242, in _run
    self.ql.emu_start(start_address, self.exit_point, count=31337)
  File "/usr/games/qilingenv/lib/python3.10/site-packages/qiling/core.py", line 764, in emu_start
    raise self.internal_exception
  File "/usr/games/qilingenv/lib/python3.10/site-packages/qiling/core_hooks.py", line 94, in wrapper
    return callback(*args, **kwargs)
  File "/usr/games/qilingenv/lib/python3.10/site-packages/qiling/core_hooks.py", line 143, in _hook_intr_cb
    raise QlErrorCoreHook("_hook_intr_cb : not handled")
qiling.exception.QlErrorCoreHook: _hook_intr_cb : not handled
2023-06-01T08:49:20Z <QlLinuxMIPS32Thread at 0x7fd033f327a0: _run> failed with QlErrorCoreHook

[+] [Thread 684]        Perform CLONE_CHILD_CLEARTID at 0x90001068
[+] [Thread 684]        No thread at 0x90001068
[+] [Thread 684]
```
**Additional context**
does it relate to thread mode. how can i solve it.

**Comment by xwings** [comment]
If i rememeber clearly. you dont really need multithread to run this binary. Try turn it off ?

**Comment by DockTree** [comment]
Yeah, I am just confused about the reason why gdb can avoid this fail. Thank you for your answer.
