### ISSUE TITLE
/lib/libc.so.6: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by Gift1a** [qilingframework/qiling#1359]
这个文件可以在我的系统下运行，但是当我尝试运行下面这段代码时出现报错
```python
from qiling.os.const import POINTER, UINT, STRING
from qiling import Qiling
from qiling.const import QL_VERBOSE
from qiling.const import QL_INTERCEPT
from qiling import os
from qiling.os.mapper import QlFsMappedObject

# Init Binary File
ql = Qiling(
    ["recursed"],
    r"rootfs/x8664_linux_bak",
    verbose=QL_VERBOSE.OFF,
)

ql.run()
```
报错如下
```python
recursed: /lib/libc.so.6: version `GLIBC_2.34' not found (required by recursed)
[x]     CPU Context:
[x]     ah      : 0x0
[x]     al      : 0xe7
[x]     ch      : 0x0
[x]     cl      : 0x0
[x]     dh      : 0xdb
[x]     dl      : 0x50
[x]     bh      : 0x0
[x]     bl      : 0x0
[x]     ax      : 0xe7
[x]     cx      : 0x0
[x]     dx      : 0xdb50
[x]     bx      : 0x0
[x]     sp      : 0xdb38
[x]     bp      : 0x0
[x]     si      : 0xd3b
[x]     di      : 0x51c9
[x]     ip      : 0x0
[x]     eax     : 0xe7
[x]     ecx     : 0x0
[x]     edx     : 0xdb50
[x]     ebx     : 0x0
[x]     esp     : 0xdb38
[x]     ebp     : 0x0
[x]     esi     : 0xf7df0d3b
[x]     edi     : 0x555551c9
[x]     eip     : 0x0
[x]     rax     : 0xe7
[x]     rbx     : 0x0
[x]     rcx     : 0x0
[x]     rdx     : 0x80000000db50
[x]     rsi     : 0x7ffff7df0d3b
[x]     rdi     : 0x5555555551c9
[x]     rbp     : 0x0
[x]     rsp     : 0x80000000db38
[x]     r8      : 0x0
[x]     r9      : 0x1
[x]     r10     : 0x22
[x]     r11     : 0x6ffffdff
[x]     r12     : 0x8a37322b530
[x]     r13     : 0x0
[x]     r14     : 0x7ffff7ffe170
[x]     r15     : 0x0
[x]     rip     : 0x0
[x]     cr0     : 0x11
[x]     cr1     : 0x0
[x]     cr2     : 0x0
[x]     cr3     : 0x0
[x]     cr4     : 0x0
[x]     cr8     : 0x0
[x]     dr0     : 0x0
[x]     dr1     : 0x0
[x]     dr2     : 0x0
[x]     dr3     : 0x0
[x]     dr4     : 0x0
[x]     dr5     : 0x0
[x]     dr6     : 0xffff0ff0
[x]     dr7     : 0x400
[x]     st0     : 0x0
[x]     st1     : 0x0
[x]     st2     : 0x0
[x]     st3     : 0x0
[x]     st4     : 0x0
[x]     st5     : 0x0
[x]     st6     : 0x0
[x]     st7     : 0x0
[x]     eflags  : 0x46
[x]     cs      : 0x33
[x]     ss      : 0x28
[x]     ds      : 0x0
[x]     es      : 0x0
[x]     fs      : 0x0
[x]     gs      : 0x0
[x]     r8b     : 0x0
[x]     r9b     : 0x1
[x]     r10b    : 0x22
[x]     r11b    : 0xff
[x]     r12b    : 0x30
[x]     r13b    : 0x0
[x]     r14b    : 0x70
[x]     r15b    : 0x0
[x]     r8w     : 0x0
[x]     r9w     : 0x1
[x]     r10w    : 0x22
[x]     r11w    : 0xfdff
[x]     r12w    : 0xb530
[x]     r13w    : 0x0
[x]     r14w    : 0xe170
[x]     r15w    : 0x0
[x]     r8d     : 0x0
[x]     r9d     : 0x1
[x]     r10d    : 0x22
[x]     r11d    : 0x6ffffdff
[x]     r12d    : 0x7322b530
[x]     r13d    : 0x0
[x]     r14d    : 0xf7ffe170
[x]     r15d    : 0x0
[x]     fsbase  : 0x0
[x]     gsbase  : 0x6000000
[x]     xmm0    : 0xffffff00000000000000000000000000
[x]     xmm1    : 0xffffffffffffffffffffffffff
[x]     xmm2    : 0x455441564952505f4342494c47
[x]     xmm3    : 0xff0000000000
[x]     xmm4    : 0x0
[x]     xmm5    : 0x0
[x]     xmm6    : 0x0
[x]     xmm7    : 0x0
[x]     xmm8    : 0x0
[x]     xmm9    : 0x0
[x]     xmm10   : 0x0
[x]     xmm11   : 0x0
[x]     xmm12   : 0x0
[x]     xmm13   : 0x0
[x]     xmm14   : 0x0
[x]     xmm15   : 0x0
[x]     xmm16   : 0x0
[x]     xmm17   : 0x0
[x]     xmm18   : 0x0
[x]     xmm19   : 0x0
[x]     xmm20   : 0x0
[x]     xmm21   : 0x0
[x]     xmm22   : 0x0
[x]     xmm23   : 0x0
[x]     xmm24   : 0x0
[x]     xmm25   : 0x0
[x]     xmm26   : 0x0
[x]     xmm27   : 0x0
[x]     xmm28   : 0x0
[x]     xmm29   : 0x0
[x]     xmm30   : 0x0
[x]     xmm31   : 0x0
[x]     ymm0    : 0xffffff00000000000000000000000000
[x]     ymm1    : 0xffffffffffffffffffffffffff
[x]     ymm2    : 0x455441564952505f4342494c47
[x]     ymm3    : 0xff0000000000
[x]     ymm4    : 0x0
[x]     ymm5    : 0x0
[x]     ymm6    : 0x0
[x]     ymm7    : 0x0
[x]     ymm8    : 0x0
[x]     ymm9    : 0x0
[x]     ymm10   : 0x0
[x]     ymm11   : 0x0
[x]     ymm12   : 0x0
[x]     ymm13   : 0x0
[x]     ymm14   : 0x0
[x]     ymm15   : 0x0
[x]     ymm16   : 0x0
[x]     ymm17   : 0x0
[x]     ymm18   : 0x0
[x]     ymm19   : 0x0
[x]     ymm20   : 0x0
[x]     ymm21   : 0x0
[x]     ymm22   : 0x0
[x]     ymm23   : 0x0
[x]     ymm24   : 0x0
[x]     ymm25   : 0x0
[x]     ymm26   : 0x0
[x]     ymm27   : 0x0
[x]     ymm28   : 0x0
[x]     ymm29   : 0x0
[x]     ymm30   : 0x0
[x]     ymm31   : 0x0
[x]     zmm0    : 0x0
[x]     zmm1    : 0x0
[x]     zmm2    : 0x0
[x]     zmm3    : 0x0
[x]     zmm4    : 0x0
[x]     zmm5    : 0x0
[x]     zmm6    : 0x0
[x]     zmm7    : 0x0
[x]     zmm8    : 0x0
[x]     zmm9    : 0x0
[x]     zmm10   : 0x0
[x]     zmm11   : 0x0
[x]     zmm12   : 0x0
[x]     zmm13   : 0x0
[x]     zmm14   : 0x0
[x]     zmm15   : 0x0
[x]     zmm16   : 0x0
[x]     zmm17   : 0x0
[x]     zmm18   : 0x0
[x]     zmm19   : 0x0
[x]     zmm20   : 0x0
[x]     zmm21   : 0x0
[x]     zmm22   : 0x0
[x]     zmm23   : 0x0
[x]     zmm24   : 0x0
[x]     zmm25   : 0x0
[x]     zmm26   : 0x0
[x]     zmm27   : 0x0
[x]     zmm28   : 0x0
[x]     zmm29   : 0x0
[x]     zmm30   : 0x0
[x]     zmm31   : 0x0
[x]     PC = 0x0000000000000000 (unreachable)

[x]     Memory map:
[x]     Start                End                  Perm    Label                  Image
[x]     000000000000030000 - 000000000000031000   rwx     [GDT]                  
[x]     000000555555554000 - 000000555555555000   r--     recursed               /root/Desktop/Qiling/Demo/recursed
[x]     000000555555555000 - 000000555555556000   r-x     recursed               /root/Desktop/Qiling/Demo/recursed
[x]     000000555555556000 - 000000555555980000   r--     recursed               /root/Desktop/Qiling/Demo/recursed
[x]     000000555555980000 - 000000555555982000   rw-     recursed               /root/Desktop/Qiling/Demo/recursed
[x]     000000555555982000 - 000000555555984000   rwx     [hook_mem]             
[x]     0000007fffb7dd6000 - 0000007fffb7fbd000   r-x     [mmap] libc.so.6       
[x]     0000007fffb7fbd000 - 0000007fffb81bd000   ---     [mmap] libc.so.6       
[x]     0000007fffb81bd000 - 0000007fffb81c3000   rw-     [mmap] libc.so.6       
[x]     0000007fffb81c3000 - 0000007fffb81c7000   rw-     [mmap anonymous]       
[x]     0000007fffb81c7000 - 0000007fffb81c9000   rw-     [mmap anonymous]       
[x]     0000007ffff7dd5000 - 0000007ffff7dfc000   r-x     ld-linux-x86-64.so.2   /root/Desktop/Qiling/Demo/rootfs/x8664_linux_bak/lib64/ld-linux-x86-64.so.2
[x]     0000007ffff7ffc000 - 0000007ffff7fff000   rw-     ld-linux-x86-64.so.2   /root/Desktop/Qiling/Demo/rootfs/x8664_linux_bak/lib64/ld-linux-x86-64.so.2
[x]     0000007ffffffde000 - 00000080000000e000   rwx     [stack]                
[x]     00ffffffffff600000 - 00ffffffffff601000   rwx     [vsyscall]             
Traceback (most recent call last):
  File "qiling_testlinux.py", line 15, in <module>
    ql.run()
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/qiling/core.py", line 582, in run
    self.os.run()
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 176, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/qiling/core.py", line 753, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/unicorn/unicorn.py", line 547, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
```

我猜测这个问题和libc有关，但是当我将qiling提供的rootfs中的libc.so和ld-linux-x86-64.so.2替换为本地目录/usr/lib/x86_64-linux-gnu下的对应文件时仍然会出错。报错信息如下

```python
[!]     0x7ffff7de6eeb: syscall ql_syscall_rseq number = 0x14e(334) not implemented
/lib/libc.so.6: CPU ISA level is lower than required
[x]     CPU Context:
[x]     ah      : 0x0
[x]     al      : 0xe7
[x]     ch      : 0x0
[x]     cl      : 0x0
[x]     dh      : 0xd9
[x]     dl      : 0xe0
[x]     bh      : 0x82
[x]     bl      : 0xe0
[x]     ax      : 0xe7
[x]     cx      : 0x0
[x]     dx      : 0xd9e0
[x]     bx      : 0x82e0
[x]     sp      : 0xd9c8
[x]     bp      : 0x0
[x]     si      : 0x20a0
[x]     di      : 0x51c9
[x]     ip      : 0x0
[x]     eax     : 0xe7
[x]     ecx     : 0x0
[x]     edx     : 0xd9e0
[x]     ebx     : 0xf7e082e0
[x]     esp     : 0xd9c8
[x]     ebp     : 0x0
[x]     esi     : 0xf7de20a0
[x]     edi     : 0x555551c9
[x]     eip     : 0x0
[x]     rax     : 0xe7
[x]     rbx     : 0x7ffff7e082e0
[x]     rcx     : 0x0
[x]     rdx     : 0x80000000d9e0
[x]     rsi     : 0x7ffff7de20a0
[x]     rdi     : 0x5555555551c9
[x]     rbp     : 0x0
[x]     rsp     : 0x80000000d9c8
[x]     r8      : 0x0
[x]     r9      : 0x3c
[x]     r10     : 0x20
[x]     r11     : 0xffffffff
[x]     r12     : 0x0
[x]     r13     : 0x1
[x]     r14     : 0x555555554040
[x]     r15     : 0x7ffff7dfdc99
[x]     rip     : 0x0
[x]     cr0     : 0x11
[x]     cr1     : 0x0
[x]     cr2     : 0x0
[x]     cr3     : 0x0
[x]     cr4     : 0x0
[x]     cr8     : 0x0
[x]     dr0     : 0x0
[x]     dr1     : 0x0
[x]     dr2     : 0x0
[x]     dr3     : 0x0
[x]     dr4     : 0x0
[x]     dr5     : 0x0
[x]     dr6     : 0xffff0ff0
[x]     dr7     : 0x400
[x]     st0     : 0x0
[x]     st1     : 0x0
[x]     st2     : 0x0
[x]     st3     : 0x0
[x]     st4     : 0x0
[x]     st5     : 0x0
[x]     st6     : 0x0
[x]     st7     : 0x0
[x]     eflags  : 0x46
[x]     cs      : 0x33
[x]     ss      : 0x28
[x]     ds      : 0x0
[x]     es      : 0x0
[x]     fs      : 0x0
[x]     gs      : 0x0
[x]     r8b     : 0x0
[x]     r9b     : 0x3c
[x]     r10b    : 0x20
[x]     r11b    : 0xff
[x]     r12b    : 0x0
[x]     r13b    : 0x1
[x]     r14b    : 0x40
[x]     r15b    : 0x99
[x]     r8w     : 0x0
[x]     r9w     : 0x3c
[x]     r10w    : 0x20
[x]     r11w    : 0xffff
[x]     r12w    : 0x0
[x]     r13w    : 0x1
[x]     r14w    : 0x4040
[x]     r15w    : 0xdc99
[x]     r8d     : 0x0
[x]     r9d     : 0x3c
[x]     r10d    : 0x20
[x]     r11d    : 0xffffffff
[x]     r12d    : 0x0
[x]     r13d    : 0x1
[x]     r14d    : 0x55554040
[x]     r15d    : 0xf7dfdc99
[x]     fsbase  : 0x7fffb7fb8100
[x]     gsbase  : 0x6000000
[x]     xmm0    : 0x0
[x]     xmm1    : 0x0
[x]     xmm2    : 0x0
[x]     xmm3    : 0x0
[x]     xmm4    : 0xffff0000000000000000000000000000
[x]     xmm5    : 0x48
[x]     xmm6    : 0x0
[x]     xmm7    : 0x0
[x]     xmm8    : 0x0
[x]     xmm9    : 0x0
[x]     xmm10   : 0x0
[x]     xmm11   : 0x0
[x]     xmm12   : 0x0
[x]     xmm13   : 0x0
[x]     xmm14   : 0x0
[x]     xmm15   : 0x0
[x]     xmm16   : 0x0
[x]     xmm17   : 0x0
[x]     xmm18   : 0x0
[x]     xmm19   : 0x0
[x]     xmm20   : 0x0
[x]     xmm21   : 0x0
[x]     xmm22   : 0x0
[x]     xmm23   : 0x0
[x]     xmm24   : 0x0
[x]     xmm25   : 0x0
[x]     xmm26   : 0x0
[x]     xmm27   : 0x0
[x]     xmm28   : 0x0
[x]     xmm29   : 0x0
[x]     xmm30   : 0x0
[x]     xmm31   : 0x0
[x]     ymm0    : 0x0
[x]     ymm1    : 0x0
[x]     ymm2    : 0x0
[x]     ymm3    : 0x0
[x]     ymm4    : 0xffff0000000000000000000000000000
[x]     ymm5    : 0x48
[x]     ymm6    : 0x0
[x]     ymm7    : 0x0
[x]     ymm8    : 0x0
[x]     ymm9    : 0x0
[x]     ymm10   : 0x0
[x]     ymm11   : 0x0
[x]     ymm12   : 0x0
[x]     ymm13   : 0x0
[x]     ymm14   : 0x0
[x]     ymm15   : 0x0
[x]     ymm16   : 0x0
[x]     ymm17   : 0x0
[x]     ymm18   : 0x0
[x]     ymm19   : 0x0
[x]     ymm20   : 0x0
[x]     ymm21   : 0x0
[x]     ymm22   : 0x0
[x]     ymm23   : 0x0
[x]     ymm24   : 0x0
[x]     ymm25   : 0x0
[x]     ymm26   : 0x0
[x]     ymm27   : 0x0
[x]     ymm28   : 0x0
[x]     ymm29   : 0x0
[x]     ymm30   : 0x0
[x]     ymm31   : 0x0
[x]     zmm0    : 0x0
[x]     zmm1    : 0x0
[x]     zmm2    : 0x0
[x]     zmm3    : 0x0
[x]     zmm4    : 0x0
[x]     zmm5    : 0x0
[x]     zmm6    : 0x0
[x]     zmm7    : 0x0
[x]     zmm8    : 0x0
[x]     zmm9    : 0x0
[x]     zmm10   : 0x0
[x]     zmm11   : 0x0
[x]     zmm12   : 0x0
[x]     zmm13   : 0x0
[x]     zmm14   : 0x0
[x]     zmm15   : 0x0
[x]     zmm16   : 0x0
[x]     zmm17   : 0x0
[x]     zmm18   : 0x0
[x]     zmm19   : 0x0
[x]     zmm20   : 0x0
[x]     zmm21   : 0x0
[x]     zmm22   : 0x0
[x]     zmm23   : 0x0
[x]     zmm24   : 0x0
[x]     zmm25   : 0x0
[x]     zmm26   : 0x0
[x]     zmm27   : 0x0
[x]     zmm28   : 0x0
[x]     zmm29   : 0x0
[x]     zmm30   : 0x0
[x]     zmm31   : 0x0
[x]     PC = 0x0000000000000000 (unreachable)

[x]     Memory map:
[x]     Start                End                  Perm    Label                  Image
[x]     000000000000030000 - 000000000000031000   rwx     [GDT]                  
[x]     000000555555554000 - 000000555555555000   r--     recursed               /root/Desktop/Qiling/Demo/recursed
[x]     000000555555555000 - 000000555555556000   r-x     recursed               /root/Desktop/Qiling/Demo/recursed
[x]     000000555555556000 - 000000555555980000   r--     recursed               /root/Desktop/Qiling/Demo/recursed
[x]     000000555555980000 - 000000555555982000   rw-     recursed               /root/Desktop/Qiling/Demo/recursed
[x]     000000555555982000 - 000000555555984000   rwx     [hook_mem]             
[x]     0000007fffb7dd6000 - 0000007fffb7dfc000   r--     [mmap] libc.so.6       
[x]     0000007fffb7dfc000 - 0000007fffb7f51000   r-x     [mmap] libc.so.6       
[x]     0000007fffb7f51000 - 0000007fffb7fa4000   r--     [mmap] libc.so.6       
[x]     0000007fffb7fa4000 - 0000007fffb7faa000   rw-     [mmap] libc.so.6       
[x]     0000007fffb7faa000 - 0000007fffb7fb7000   rw-     [mmap anonymous]       
[x]     0000007fffb7fb7000 - 0000007fffb7fb9000   rw-     [mmap anonymous]       
[x]     0000007ffff7dd5000 - 0000007ffff7dd6000   r--     ld-linux-x86-64.so.2   /root/Desktop/Qiling/Demo/rootfs/x8664_linux/lib64/ld-linux-x86-64.so.2
[x]     0000007ffff7dd6000 - 0000007ffff7dfb000   r-x     ld-linux-x86-64.so.2   /root/Desktop/Qiling/Demo/rootfs/x8664_linux/lib64/ld-linux-x86-64.so.2
[x]     0000007ffff7dfb000 - 0000007ffff7e05000   r--     ld-linux-x86-64.so.2   /root/Desktop/Qiling/Demo/rootfs/x8664_linux/lib64/ld-linux-x86-64.so.2
[x]     0000007ffff7e05000 - 0000007ffff7e09000   rw-     ld-linux-x86-64.so.2   /root/Desktop/Qiling/Demo/rootfs/x8664_linux/lib64/ld-linux-x86-64.so.2
[x]     0000007ffffffde000 - 00000080000000e000   rwx     [stack]                
[x]     00ffffffffff600000 - 00ffffffffff601000   rwx     [vsyscall]             
Traceback (most recent call last):
  File "qiling_testlinux.py", line 15, in <module>
    ql.run()
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/qiling/core.py", line 582, in run
    self.os.run()
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 176, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/qiling/core.py", line 753, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/unicorn/unicorn.py", line 547, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
```

我尝试搜索该问题，但是并没有找到相关问题的答案，希望能收到你们的回复。

**Comment by Gift1a** [comment]
这是我用于测试的两个附件，遇到的问题都是一样的
[test.zip](https://github.com/qilingframework/qiling/files/11706339/test.zip)

**Comment by chinggg** [comment]
该问题是由于你的可执行程序和 rootfs 的 libc 版本不匹配，Qiling 自带的 `rootfs/x8664_linux` 应该是 Ubuntu 20.04 的环境，若你有该程序的源码，可以尝试在相近的环境下编译得可执行文件，否则可尝试将本机的 `libc.so` 等共享库文件放进 rootfs

The problem is due to a mismatch between your executable and the libc version of rootfs, `rootfs/x8664_linux` seems to be a Ubuntu 20.04 environment. If you have the source code of the program, you can try to compile the executable in a similar environment, otherwise you can try to put your local `libc.so` and other shared libraries into the rootfs
