### ISSUE TITLE
ERROR: fail to load the dynamic library

### ISSUE THREAD

**Issue by Hexix23** [qilingframework/qiling#1474]
***Describe the bug**
Im having the following issue on MacOS Sonoma 14.5 everytime Im trying to run qltool.

**Sample Code**
```bash
python qltool
Traceback (most recent call last):
  File "/Users/0xh3l1x/Tools/Emulation/qiling/qltool", line 19, in <module>
    from qiling.arch import utils as arch_utils
  File "/Users/0xh3l1x/Tools/Emulation/qiling/qiling/arch/utils.py", line 14, in <module>
    from keystone import (Ks, KS_ARCH_ARM, KS_ARCH_ARM64, KS_ARCH_MIPS, KS_ARCH_X86, KS_ARCH_PPC,
  File "/Users/0xh3l1x/.pyenv/versions/3.10.14/lib/python3.10/site-packages/keystone/__init__.py", line 4, in <module>
    from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, __version__
  File "/Users/0xh3l1x/.pyenv/versions/3.10.14/lib/python3.10/site-packages/keystone/keystone.py", line 74, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
```

**Additional context**
I know that the issue is described on https://github.com/qilingframework/qiling/issues/18 but didnt work.

I already installed also keystone-engine  from source and didnt fix it anything

Thanks for the help, will be awesome to fix this :)

**Comment by farss** [comment]
pip uninstall keystone-engine

**Comment by farss** [comment]
file /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keystone/libkeystone.dylib
