### ISSUE TITLE
QlArchARM object has no attribute unicorn_exception_handler during ARM Cortex-M emulation

### ISSUE THREAD

**Issue by thdemarty** [qilingframework/qiling#1478]
**Describe the bug**
When attempting to emulate a bare-metal ARM program for Cortex-M using Qiling, the following error occurs: `AttributeError: 'QlArchARM' object has no attribute 'unicorn_exception_handler'.`

**Sample Code**
```python
from qiling import Qiling
from qiling.const import *

ELF_FILE_PATH = "my-application.axf"
ROOT_FS_PATH = "./rootfs"

ql = Qiling([ELF_FILE_PATH], ROOT_FS_PATH, archtype=QL_ARCH.ARM, ostype=QL_OS.MCU, verbose=QL_VERBOSE.DEBUG)
ql.run()
```

**Expected behavior**
The Qiling emulator should successfully initialize and run the provided ARM Cortex-M ELF file without raising an `AttributeError`.

**Screenshots**

**Additional context**
* Qiling version: 1.4.6
* Python version: 3.10.12
Operating System: Ubuntu 22.04.4 LTS - x86_64
Detailed error message: `AttributeError: 'QlArchARM' object has no attribute 'unicorn_exception_handler'`

**Comment by elicn** [comment]
Hi there and welcome to Qiling.
Can you please provide the relevant error message from the logs?

**Comment by thdemarty** [comment]
Hello,

Here is the full traceback when executing the program :
```bash
[+]     Profile: default
Traceback (most recent call last):
  File "/home/me/emulation/qiling_emulation.py", line 15, in <module>
    ql = Qiling([ELF_FILE_PATH], ROOT_FS_PATH, archtype=QL_ARCH.ARM, ostype=QL_OS.MCU, verbose=QL_VERBOSE.DEBUG)
  File "/home/me/emulation/env/lib/python3.10/site-packages/qiling/core.py", line 190, in __init__
    self.loader.run()
  File "/home/me/emulation/env/lib/python3.10/site-packages/qiling/loader/mcu.py", line 136, in run
    self.ql.hook_intr(self.ql.arch.unicorn_exception_handler)
AttributeError: 'QlArchARM' object has no attribute 'unicorn_exception_handler'

'QlArchARM' object has no attribute 'unicorn_exception_handler'
```

**Comment by elicn** [comment]
`archtype=QL_ARCH.ARM` is not supported for MCU; try `archtype=QL_ARCH.CORTEX_M` instead
