### ISSUE TITLE
New Dockerfile and test_all.py script error.

### ISSUE THREAD

**Issue by chfl4gs** [qilingframework/qiling#150]
The Dockerfile below is a multi stage docker image build that drastically reduces docker image size from 737MB to 298MB. However, there is an error with test_all.py script. Anyone can take a look?

### Error
```
======================================================================
ERROR: test_macho_macos_x8664 (test_macho.MACHOTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/qiling/tests/test_macho.py", line 14, in test_macho_macos_x8664
    ql = Qiling(["../examples/rootfs/x8664_macos/bin/x8664_hello_usercorn"], "../examples/rootfs/x8664_macos", output = "debug")
  File "/opt/qiling/lib/python3.6/site-packages/qiling-0.9-py3.6.egg/qiling/core.py", line 199, in __init__
    self.load_exec()
  File "/opt/qiling/lib/python3.6/site-packages/qiling-0.9-py3.6.egg/qiling/core.py", line 209, in load_exec
    loader_file(self)
  File "/opt/qiling/lib/python3.6/site-packages/qiling-0.9-py3.6.egg/qiling/os/macos/x8664.py", line 85, in loader_file
    loader.loadMachoX8664()
  File "/opt/qiling/lib/python3.6/site-packages/qiling-0.9-py3.6.egg/qiling/loader/macho.py", line 293, in loadMachoX8664
    self.loadSegment64(cmd, isdyld)
  File "/opt/qiling/lib/python3.6/site-packages/qiling-0.9-py3.6.egg/qiling/loader/macho.py", line 338, in loadSegment64
    self.uc.mem_map(vaddr_start, seg_size)
  File "/opt/qiling/lib/python3.6/site-packages/unicorn/unicorn.py", line 448, in mem_map
    raise UcError(status)
unicorn.unicorn.UcError: No memory available or memory not present (UC_ERR_NOMEM)

----------------------------------------------------------------------
Ran 22 tests in 8.151s

FAILED (errors=1)
```

### Dockerfile
```
FROM python:3.6-slim AS builder

MAINTAINER "Kevin Foo <chbsd64@gmail.com>"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get -y upgrade \
  && apt-get install -y --no-install-recommends cmake build-essential gcc git

RUN python -m venv /opt/qiling

ENV PATH="/opt/qiling/bin:$PATH"

RUN git clone https://github.com/qilingframework/qiling.git \
  && cd qiling \
  && pip install -r requirements.txt \
  && python setup.py install

FROM python:3.6-slim AS base

COPY --from=builder /opt/qiling /opt/qiling

COPY --from=builder /qiling /qiling

WORKDIR /qiling

ENV HOME /qiling

ENV PATH="/opt/qiling/bin:$PATH"

CMD bash
```

**Comment by xwings** [comment]
the last few test seems to be good ? again ? .. again, i guess just move the docker to allow fail.
