### ISSUE TITLE
unicorn.unicorn_py3.unicorn.UcError: Invalid argument (UC_ERR_ARG)

### ISSUE THREAD

**Issue by ywl20020421** [qilingframework/qiling#1507]
***Describe the bug**
[=] 	Initiate stack address at 0xfffdd000 
[=] 	Loading E:\qiling\examples\rootfs\x86_windows\bin\x86_hello.exe to 0x400000
[=] 	PE entry point at 0x401280
[=] 	TEB is at 0x6000
[=] 	PEB is at 0x61b0
[=] 	LDR is at 0x6630
[=] 	Loading ntdll.dll ...
[=] 	Done loading ntdll.dll
[=] 	Loading kernel32.dll ...
[=] 	Loading kernelbase.dll ...
[=] 	Done loading kernelbase.dll
[=] 	Done loading kernel32.dll
[=] 	Loading mscoree.dll ...
[=] 	Calling mscoree.dll DllMain at 0x102c1100
Traceback (most recent call last):
  File "E:\qiling\examples\demo.py", line 12, in <module>
    my_sandbox(["E:\\qiling\\examples\\rootfs\\x86_windows\\bin\\x86_hello.exe"], "E:\\qiling\\examples\\rootfs\\x86_windows")
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\qiling\examples\demo.py", line 6, in my_sandbox
    ql = Qiling(path, rootfs)
  File "E:\qiling\qiling\core.py", line 190, in __init__
    self.loader.run()
    ~~~~~~~~~~~~~~~^^
  File "E:\qiling\qiling\loader\pe.py", line 725, in run
    self.load(pe)
    ~~~~~~~~~^^^^
  File "E:\qiling\qiling\loader\pe.py", line 804, in load
    super().load_dll(each, self.is_driver)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "E:\qiling\qiling\loader\pe.py", line 261, in load_dll
    self.call_dll_entrypoint(dll, dll_base, dll_len, dll_name)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\qiling\qiling\loader\pe.py", line 303, in call_dll_entrypoint
    regs_state = self.ql.arch.regs.save()
  File "E:\qiling\qiling\arch\register.py", line 75, in save
    return dict((reg, self.read(reg)) for reg in self.register_mapping)
  File "E:\qiling\qiling\arch\register.py", line 75, in <genexpr>
    return dict((reg, self.read(reg)) for reg in self.register_mapping)
                      ~~~~~~~~~^^^^^
  File "E:\qiling\qiling\arch\register.py", line 60, in read
    return self.uc.reg_read(register)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\15189\AppData\Local\Programs\Python\Python313\Lib\site-packages\unicorn\unicorn_py3\arch\intel.py", line 158, in reg_read
    value = super().reg_read(reg_id, aux)
  File "C:\Users\15189\AppData\Local\Programs\Python\Python313\Lib\site-packages\unicorn\unicorn_py3\unicorn.py", line 425, in reg_read
    return self._reg_read(reg_id, self._DEFAULT_REGTYPE)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\15189\AppData\Local\Programs\Python\Python313\Lib\site-packages\unicorn\unicorn_py3\unicorn.py", line 381, in _reg_read
    raise UcError(status, reg_id)
unicorn.unicorn_py3.unicorn.UcError: Invalid argument (UC_ERR_ARG)

**Sample Code**
```python
from qiling import *

# sandbox to emulate the EXE
def my_sandbox(path, rootfs):
    # setup Qiling engine
    ql = Qiling(path, rootfs)
    # now emulate the EXE
    ql.run()

if __name__ == "__main__":
    # execute Windows EXE under our rootfs
    my_sandbox(["E:\\qiling\\examples\\rootfs\\x86_windows\\bin\\x86_hello.exe"], "E:\\qiling\\examples\\rootfs\\x86_windows")
```

**Expected behavior**

I have tested most of the test files in the project, and on a Windows environment, this error is reported,
I use the same environment, and rootfs are also the same. There are no errors on ubantu.
I want to know how to run test files properly on Windows 11. If this question is foolish, please forgive me. I am a student.

**Comment by ywl20020421** [comment]
I have found a solution. pip install unicorn=2.0.1

**Comment by elicn** [comment]
Hi there,
This is a known issue due to an incompatible Unicorn version, but it seems that you already got it sorted out. I'll go ahead and close this one.
