### ISSUE TITLE
AttributeError: 'PE' object has no attribute 'DIRECTORY_ENTRY_IMPORT'

### ISSUE THREAD

**Issue by ryancor** [qilingframework/qiling#166]
What do we do in situations where there its a pe file with no IAT? Example file https://www.virustotal.com/gui/file/e036d68b8f8b7afc6c8b6252876e1e290f11a26d4ad18ac6f310662845b2c734/detection

```
[+] FS : 0x73
[+] GS : 0x7b
[+] DS : 0x83
[+] CS : 0x8b
[+] SS : 0x90
[+] Windows Registry PATH: /home/ryancor/Desktop/SandBoxMalware/cryptowall/Windows/registry
[+] Loading /home/ryancor/Desktop/SandBoxMalware/cryptowall/bin/cryptowall_055A0000.exe to 0x400000
[+] PE entry point at 0x4170b0
[+] Initiate stack address at 0xfffdd000 
[+] TEB addr is 0x6000
[+] PEB addr is 0x6044
Traceback (most recent call last):
  File "Find-C2.py", line 9, in <module>
    ql = Qiling(["/home/ryancor/Desktop/SandBoxMalware/cryptowall/bin/cryptowall_055A0000.exe"], "/home/ryancor/Desktop/SandBoxMalware/cryptowall", output = "debug")
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/core.py", line 200, in __init__
    self.load_exec()
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/core.py", line 208, in load_exec
    loader_file(self)
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/os/windows/x86.py", line 118, in loader_file
    ql.PE.load()
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/loader/pe.py", line 351, in load
    for entry in self.pe.DIRECTORY_ENTRY_IMPORT:
AttributeError: 'PE' object has no attribute 'DIRECTORY_ENTRY_IMPORT'
```

Python Script
```
from qiling import *

def killerswitch(uc, address, size, ql):
	if address == 0x004108A2:
		print("\n---\nCryptoWall InternetC2Server Found, Emulation Stop\n---\n")
		ql.uc.emu_stop()

if __name__ == "__main__":
	ql = Qiling(["/home/user/Desktop/SandBoxMalware/cryptowall/bin/cryptowall.exe"], "/home/user/Desktop/SandBoxMalware/cryptowall", output = "debug")
	ql.hook_code(killerswitch, ql)
	ql.run()
```

**Comment by xwings** [comment]
hi,

will you be able to provide a pull request and fix the issue ?

**Comment by ryancor** [comment]
To be honest, im not sure how to go about fixing this problem @xwings

**Comment by xwings** [comment]
Hi,

is there any binary we can look at.

**Comment by learn-more** [comment]
This seems to be fixed in current master?
Both x86 and x64 applications without any imports load fine for me.

They break on returning from WinMain (without calling ExitProcess), but that is another issue...

**Comment by xwings** [comment]
There are some big refactoring duirng march, april and may. I guess that could be the issue.

close for now.
