### ISSUE TITLE
Netgear R6220 emulation

### ISSUE THREAD

**Issue by waveburst** [qilingframework/qiling#172]
Hi,

I've been exploring Qiling by trying to emulate the Netgear r6220 example. However, I've encounters some issues.

```
Running OS:
➜  ~ cat /etc/issue
Ubuntu 18.04.4 LTS \n \l
➜  ~ uname -a
Linux wave 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I'm using the lastest R6220 firmware (R6220-V1.1.0.86) 

When I try to run the firmware as it committed I get this following error:

```
fcntl64(4, 2, 1) = 0
setsockopt
bind(4,127.0.0.1:8080,16) = 0
[+] syscall bind host: 127.0.0.1 and port: 8080 sin_family: 2
listen(4, 1024) = 0
[!] SYSCALL ERROR: ql_syscall_clone
[-] 'NoneType' object has no attribute 'cur_thread'
Traceback (most recent call last):
  File "/home/wave/playground/qiling/examples/netgear_6220_mips32el_linux.py", line 52, in <module>
    "rootfs/netgear_r6220")
  File "/home/wave/playground/qiling/examples/netgear_6220_mips32el_linux.py", line 43, in my_netgear
    ql.run()
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/core.py", line 236, in run
    runner(self)
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/os/linux/mips32.py", line 329, in runner
    raise ql.internal_exception
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/core.py", line 25, in wrapper
    return func(*args, **kw)
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/core.py", line 303, in _callback
    callback(self, intno)
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/os/linux/mips32.py", line 54, in hook_syscall
    LINUX_SYSCALL_FUNC(ql, param0, param1, param2, param3, param4, param5)
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/os/posix/syscall.py", line 2005, in ql_syscall_clone
    f_th = ql.thread_management.cur_thread    
AttributeError: 'NoneType' object has no attribute 'cur_thread'

Process finished with exit code 1
```

I noticed that the thread manager is None and initialized only when the multithread flag is enabled. However, it is mentioned that multithreading is unstable for MIPS32EL.

That's how I managed to get the webserver running. I saw that the webserver executes setup.cgi and lead me to a new issue.

setup.cgi outputs the following error:

```
[+] stat() write completed
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x4000802, 2146682488, 2146682492)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | 67110912, 2146682488, 2146682492)
[+] log mmap - return addr : 0x7fe72000
[+] log mmap - addr range  : 0x7fe72000 - 0x7fe73000
[+] log mmap - mapping needed
mmap(0x0, 0x1000, 0x3, 0x4000802, -1, 0) = 0x7fe72000
[+] mmap_base is 0x7fe72000
set_thread_area(0x7fe79470)
[!] SYSCALL ERROR: ql_syscall_mips32_set_thread_area
[-] Invalid memory write (UC_ERR_WRITE_UNMAPPED)
read(4, 0x7ff33c58, 0x400) = 0
exit_group(0)
```

When I ran only the setup.cgi with Qiling, everything works fine. It is only with it forked from mini_httpd that I receive that error. I guess that 0x7fe79470 is not mapped for some reason.

But I'm not sure what to do next. Any ideas? Is there a way to use python debugger for a forked child?

Thanks,
Gal

**Comment by xwings** [comment]
I guess the new version they introduce multithread which we are still implementing. try the older version. You can get it from their website

**Comment by waveburst** [comment]
Thanks @xwings for the quick answer. I tried and older version and things seems to work better now :)
