### ISSUE TITLE
ImportError: ERROR: fail to load the dynamic library.

### ISSUE THREAD

**Issue by bannsec** [qilingframework/qiling#18]
```
pip3 install -e .
Obtaining file:///home/user/work/opt/qiling
Collecting capstone>=4.0.1 (from qiling==0.9)
  Downloading https://files.pythonhosted.org/packages/35/0c/74db5b9b9ed25d72869832865b7612658bd796cd02c26b1d567cbc9f0ab6/capstone-4.0.1-py2.py3-none-manylinux1_x86_64.whl (1.9MB)
     |████████████████████████████████| 1.9MB 3.2MB/s
Collecting keystone-engine>=0.9.1.post3 (from qiling==0.9)
  Downloading https://files.pythonhosted.org/packages/9a/fc/ed0d3f46921bfaa612d9e8ce8313f99f4149ecf6635659510220c994cb72/keystone-engine-0.9.1-3.tar.gz (2.8MB)
     |████████████████████████████████| 2.8MB 6.7MB/s
Collecting unicorn>=1.0.2rc1 (from qiling==0.9)
  Downloading https://files.pythonhosted.org/packages/40/ca/316207963eb550a890ca48d717c2c1c3e2e5cadcdc812d6102c4f5bcf8f3/unicorn-1.0.2rc1-py2.py3-none-manylinux1_x86_64.whl (8.1MB)
     |████████████████████████████████| 8.1MB 16.4MB/s
Collecting pefile>=2019.4.18 (from qiling==0.9)
Collecting python-registry>=1.3.1 (from qiling==0.9)
  Downloading https://files.pythonhosted.org/packages/f1/0f/2605f98bb9c7ef92f926fdf3295583363fe42fc6e8f64cf38b24a029e767/python_registry-1.3.1-py3-none-any.whl
Collecting future (from pefile>=2019.4.18->qiling==0.9)
  Downloading https://files.pythonhosted.org/packages/f6/85/c273089eb6efa5644c0a1382ea553554bc0d40e00a46d989ec67f123f8b5/future-0.18.0.tar.gz (830kB)
     |████████████████████████████████| 839kB 11.8MB/s
Collecting unicodecsv (from python-registry>=1.3.1->qiling==0.9)
  Downloading https://files.pythonhosted.org/packages/6f/a4/691ab63b17505a26096608cc309960b5a6bdf39e4ba1a793d5f9b1a53270/unicodecsv-0.14.1.tar.gz
Collecting enum-compat (from python-registry>=1.3.1->qiling==0.9)
  Downloading https://files.pythonhosted.org/packages/95/6e/26bdcba28b66126f66cf3e4cd03bcd63f7ae330d29ee68b1f6b623550bfa/enum-compat-0.0.2.tar.gz
Building wheels for collected packages: keystone-engine, future, unicodecsv, enum-compat
  Building wheel for keystone-engine (setup.py) ... done
  Created wheel for keystone-engine: filename=keystone_engine-0.9.1.post3-cp36-cp36m-linux_x86_64.whl size=1800659 sha256=2ffa06c5301c69ad6f7c04e6756af7855204c0e15a778ff9f94376734b574757
  Stored in directory: /home/user/.cache/pip/wheels/e9/40/c1/6ac6e82d6aa880cd8d492d95e59be376eb77015683b94ee934
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.0-cp36-none-any.whl size=490414 sha256=2b81a1dc0ee38feef14c2a9e9bcd8271b3186308c9dfa3b1d9e49ffc014869aa
  Stored in directory: /home/user/.cache/pip/wheels/2c/02/af/63eadc269fe686aa0aa9c38eee165ad5734cbf8b765cfeedaa
  Building wheel for unicodecsv (setup.py) ... done
  Created wheel for unicodecsv: filename=unicodecsv-0.14.1-cp36-none-any.whl size=10767 sha256=841650414e90d25583f068fdb46662d5c61f47c59285af82ca781eb54090ef96
  Stored in directory: /home/user/.cache/pip/wheels/a6/09/e9/e800279c98a0a8c94543f3de6c8a562f60e51363ed26e71283
  Building wheel for enum-compat (setup.py) ... done
  Created wheel for enum-compat: filename=enum_compat-0.0.2-cp36-none-any.whl size=1290 sha256=596b7ad6bb60fc1943c81d2fbfdcd97dd1cb47d164919d0455a8701f654b4963
  Stored in directory: /home/user/.cache/pip/wheels/b1/69/f4/229af6a49beece0f688c9c73d9188769b89e698361d21ce96a
Successfully built keystone-engine future unicodecsv enum-compat
Installing collected packages: capstone, keystone-engine, unicorn, future, pefile, unicodecsv, enum-compat, python-registry, qiling
  Running setup.py develop for qiling
Successfully installed capstone-4.0.1 enum-compat-0.0.2 future-0.18.0 keystone-engine-0.9.1.post3 pefile-2019.4.18 python-registry-1.3.1 qiling unicodecsv-0.14.1 unicorn-1.0.2rc1
(qiling) ✔ ~/work/opt/qiling [master|✔]
14:02 $ qlalr ^C
(qiling) ✘-INT ~/work/opt/qiling [master|✔]
14:04 $ ls -al
total 100
drwxrwxr-x 8 user user  4096 Oct 14 14:01 .
drwxrwxr-x 4 user user  4096 Oct 14 14:00 ..
-rw-rw-r-- 1 user user   233 Oct 14 14:00 AUTHORS.TXT
-rw-rw-r-- 1 user user 17992 Oct 14 14:00 COPYING
-rw-rw-r-- 1 user user   547 Oct 14 14:00 CREDITS.TXT
-rw-rw-r-- 1 user user   465 Oct 14 14:00 Dockerfile
drwxrwxr-x 2 user user  4096 Oct 14 14:00 docs
drwxrwxr-x 5 user user  4096 Oct 14 14:00 examples
drwxrwxr-x 8 user user  4096 Oct 14 14:00 .git
-rw-rw-r-- 1 user user   240 Oct 14 14:00 .gitignore
drwxrwxr-x 5 user user  4096 Oct 14 14:00 qiling
drwxrwxr-x 2 user user  4096 Oct 14 14:02 qiling.egg-info
-rwxrwxr-x 1 user user  7944 Oct 14 14:00 qltool
-rw-rw-r-- 1 user user  5962 Oct 14 14:00 README.md
-rw-rw-r-- 1 user user   104 Oct 14 14:00 requirements.txt
-rw-rw-r-- 1 user user  1696 Oct 14 14:00 setup.py
drwxrwxr-x 2 user user  4096 Oct 14 14:00 tests
-rw-rw-r-- 1 user user   694 Oct 14 14:00 TODO
-rw-rw-r-- 1 user user    79 Oct 14 14:00 .travis.yml
(qiling) ✔ ~/work/opt/qiling [master|✔]
14:04 $ ./qltool
Traceback (most recent call last):
  File "./qltool", line 15, in <module>
    from keystone import *
  File "/home/user/.virtualenvs/qiling/lib/python3.6/site-packages/keystone/__init__.py", line 4, in <module>
    from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, __version__
  File "/home/user/.virtualenvs/qiling/lib/python3.6/site-packages/keystone/keystone.py", line 75, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.
```

This appears to be the same issue i've run into with keystone before...

https://github.com/keystone-engine/keystone/issues/386

It looks like there's still not a solution for this, but it will likely cause headaches for your users if this is not addressed in some way.

For ref, the current solution I have is to link (or copy) the keystone.so file over manually after install into an appropriate library path.

**Comment by 0x1shyboy1** [comment]
I have the same problem."cp /usr/local/lib/python3.6/dist-packages/usr/lib/python3/dist-packages/keystone/libkeystone.so /usr/lib/   " .I sovled the problem

**Comment by 0x1shyboy1** [comment]
you can check kestone.py
**************************************************************
if (_found == False) and (system() == 'Darwin'):
    _lib_path = '/usr/local/lib/'
    for _lib in _all_libs:
        try:
            _lib_file = join(_lib_path, _lib)
            #print(">> 3: Trying to load %s" %_lib_file);
            _ks = cdll.LoadLibrary(_lib_file)
            _found = True
            break
        except OSError:
            pass

if _found == False:
    raise ImportError("ERROR: fail to load the dynamic library.")

**Comment by chfl4gs** [comment]
Workaround until upstream fix.

cp /usr/local/lib/python3.6/dist-packages/usr/lib/python3/dist-packages/keystone/libkeystone.so /usr/local/lib/python3.6/dist-packages/keystone/

**Comment by firmianay** [comment]
On Mac I found this works well.
https://pypi.org/project/keystone-engine-mac-temporary/
