### ISSUE TITLE
Invalid memory fetch when emulating a simple binary of IoTGoat

### ISSUE THREAD

**Issue by cq674350529** [qilingframework/qiling#194]
Firstly, thanks for the great job.

When emulating a simple binary (`x86`) of IoTGoat firmware, it seems to fall into an infinite loop. An error `unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)` occurred when input `Ctrl + C`.  According to the log, it seems to fail to load the shared library `libgcc_s.so.1`.

I tried to run with `sudo` or `ql.root=True`, and both didn't work. The qiling framework installed is the latest version.

The code to reproduce is as follows. And the shellback is just a simple binary: accept connections and execve `/bin/busybox sh`.
```python
path = ["examples/_IoTGoat-x86.img.extracted/squashfs-root/usr/bin/shellback"]
rootfs = "examples/_IoTGoat-x86.img.extracted/squashfs-root/"
ql = Qiling(path, rootfs, verbose=1, output="debug", log_console=True, log_dir="log_output")
ql.run()
```

The corrresponding logs are:
```shell
[+] load 0x8048000 - 0x80487a0
[+] load 0x8049f00 - 0x804a004
[+] mem_start: 0x8048000 mem_end: 0x804b000
[+] interp is : examples/_IoTGoat-x86.img.extracted/squashfs-root//lib/ld-musl-i386.so.1
[+] interp_mem_size is : 0x6a000
[+] interp_base is : 0xfb7d3000
[+] mmap_start is : 0xf7bd6000
[+] DS : 0x83
[+] CS : 0x8b
[+] SS : 0x90
set_thread_area(u_info_addr= 0xffffdc58)
[+] set_thread_area base : 0xfb83be04 limit is : 0xfffff
[+] STA : 0x63
set_tid_address(fb83be20) = 21920
open(/etc/ld-musl-i386.path, 0x88000, 0o666) = -1
[+] open(/etc/ld-musl-i386.path, O_RDONLY | 557056, 0o666) = -1
[!] File Not Found /etc/ld-musl-i386.path
writev(0x2, 0xffffd940, 0x2)
[+] writev() CONTENT:
bytearray(b'Error loading shared library libgcc_s.so.1: Operation not permitted (needed by ')
bytearray(b'examples/_IoTGoat-x86.img.extracted/squashfs-root/usr/bin/shellback')
writev(0x2, 0xffffd940, 0x2)
[+] writev() CONTENT:
bytearray(b'Error loading shared library libgcc_s.so.1: Operation not permitted (needed by ')
bytearray(b'examples/_IoTGoat-x86.img.extracted/squashfs-root/usr/bin/shellback')
writev(0x2, 0xffffd940, 0x2)
[+] writev() CONTENT:
bytearray(b'Error loading shared library libgcc_s.so.1: Operation not permitted (needed by ')
bytearray(b'examples/_IoTGoat-x86.img.extracted/squashfs-root/usr/bin/shellback')
writev(0x2, 0xffffd940, 0x2)
[+] writev() CONTENT:
bytearray(b'Error loading shared library libgcc_s.so.1: Operation not permitted (needed by ')
bytearray(b'examples/_IoTGoat-x86.img.extracted/squashfs-root/usr/bin/shellback')
writev(0x2, 0xffffd940, 0x2)
[+] writev() CONTENT:
bytearray(b'Error loading shared library libgcc_s.so.1: Operation not permitted (needed by ')
bytearray(b'examples/_IoTGoat-x86.img.extracted/squashfs-root/usr/bin/shellback')
writev(0x2, 0xffffd940, 0x2)
[+] writev() CONTENT:
bytearray(b'Error loading shared library libgcc_s.so.1: Operation not permitted (needed by ')
// ... 
bytearray(b'examples/_IoTGoat-x86.img.extracted/squashfs-root/usr/bin/shellback')
writev(0x2, 0xffffd940, 0x2)
[+] writev() CONTENT:
bytearray(b'Error loading shared library libgcc_s.so.1: Operation not permitted (needed by ')
bytearray(b'examples/_IoTGoat-x86.img.extracted/squashfs-root/usr/bin/shellback')
writev(0x2, 0xffffd940, 0x2)
[+] writev() CONTENT:
bytearray(b'Error loading shared library libgcc_s.so.1: Operation not permitted (needed by ')
bytearray(b'examples/_IoTGoat-x86.img.extracted/squashfs-root/usr/bin/shellback')
writev(0x2, 0xffffd940, 0x2)
[+] PC = 0x0
[+] Start      End        Perm.  Path
[+] 08048000 - 0804b000 - r-x    examples/_IoTGoat-x86.img.extracted/squashfs-root/usr/bin/shellback
[+] fb7d3000 - fb83d000 - r-x    /lib/ld-musl-i386.so.1
[+] ffffdef0 - ffffe000 - rw-    [stack]
Traceback (most recent call last):
  File "qiling_demo.py", line 17, in <module>
    main()
  File "qiling_demo.py", line 14, in main
    ql.run()
  File "~/workspace/git/qiling/qiling/core.py", line 272, in run
    runner(self)
  File "~/workspace/git/qiling/qiling/os/linux/x86.py", line 168, in runner
    ql.uc.emu_start(ql.elf_entry, ql.until_addr, ql.timeout) 
  File "/usr/local/lib/python3.6/dist-packages/unicorn/unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
```

The IoTGoat firmware is available at: https://github.com/OWASP/IoTGoat/releases/download/v1.0/IoTGoat-x86.img.gz

Any suggestions? Thanks in advance.

**Comment by xwings** [comment]
i will give it a try maybe tomorrow.

**Comment by xwings** [comment]
Do u have this File Not Found /etc/ld-musl-i386.path u need this, From the log

**Comment by cq674350529** [comment]
Yes, this file doesn't exist. By greping the string "ld-musl-i386.path", it seems to be used by `/lib/libc.so`.
However, since it's x86 arch, simply run with `chroot .` works well.
```
~/squashfs-root$ sudo chroot . ./usr/bin/shellback
```

**Comment by xwings** [comment]
![image](https://user-images.githubusercontent.com/463553/79139564-1ddb8880-7de9-11ea-9897-9278006bf2d3.png)

seems like lib/ld-musl-i386.so.1 which link so libc.so got a corrupted section header size ? which normally chroot will not care becoz it does not parse elf header, but qemu-usermode and us fail at the same time.

**Comment by cq674350529** [comment]
Like as what you did, I try it with `qemu-i386-static`  and it works well.

```shell
~/squashfs-root$ file ./lib/ld-musl-i386.so.1
./lib/ld-musl-i386.so.1: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, corrupted section header size

~/squashfs-root$ ./qemu-i386-static -L . -strace ./usr/bin/shellback 
3449 set_thread_area(-151003688,-159399216,-1,-159399936,-151003024,-151003640) = 0
3449 set_tid_address(-159392224,-159399216,-151003024,-159399936,-159399936,-151003640) = 3449
3449 open("/etc/ld-musl-i386.path",O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 errno=2 (No such file or directory)
3449 open("/lib/libgcc_s.so.1",O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
3449 fcntl64(3,F_SETFD,1) = 0
3449 fstat64(3,0xf6ffdab4) = 0
3449 read(3,0xf6ffd6b8,936) = 936
3449 mmap2(NULL,86016,PROT_EXEC|PROT_READ,MAP_PRIVATE,3,0) = 0xf677e000
3449 mmap2(0xf6791000,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED,3,0x12) = 0xf6791000
3449 close(3) = 0
3449 mprotect(0xf6791000,4096,PROT_READ) = 0
3449 mprotect(0xf67fb000,4096,PROT_READ) = 0
3449 mprotect(0x08049000,4096,PROT_READ) = 0
3449 socketcall(1,-151003328,2,-159399936,-159399936,-151003256) = 3
3449 socketcall(2,-151003288,3,134514496,0,-151003256) = 0
3449 socketcall(4,-151003288,3,3,0,-151003256) = 0
3449 socketcall(5,-151003288,0,0,0,0)

# in another terminal
~/squashfs-root$ netstat -tlnp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:5515            0.0.0.0:*               LISTEN      3449/qemu-i386-stat
```

**Comment by xwings** [comment]
You are right, will you be able to check and fix the issue ?

**Comment by cq674350529** [comment]
I'll have a try.

**Comment by xwings** [comment]
we should at least see a syscall open before the writeev, not too sure why. Will you be able to recompile that IoT goat and try to do it again ?

**Comment by xwings** [comment]
we found and issue will issue a fix into dev in few hours time. its some issue with out open implentation.

**Comment by xwings** [comment]
bug fixed ! Enjoy

![image](https://user-images.githubusercontent.com/463553/79294394-a69d1600-7f08-11ea-8372-a58158579317.png)

**Comment by cq674350529** [comment]
Good, thx!
