### ISSUE TITLE
 Code running error

### ISSUE THREAD

**Issue by tianstcht** [qilingframework/qiling#276]
when I run a simple code like example:
````
from qiling import *

path = ["examples/rootfs/x8664_linux/bin/x8664_hello"]
rootfs = "examples/rootfs/x8664_linux"
ql = Qiling(path, rootfs)
ql.run()
````

I meet following problem :
````
Traceback (most recent call last):
  File "/home/t1an5t/ipc-monitor/qiling-master/qiling/utils.py", line 167, in ql_get_module_function
    imp_module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/t1an5t/ipc-monitor/qiling-master/qiling/os/linux/linux.py", line 9, in <module>
    from qiling.os.posix.posix import QlOsPosix
  File "/home/t1an5t/ipc-monitor/qiling-master/qiling/os/posix/posix.py", line 13, in <module>
    from qiling.os.os import QlOs
  File "/home/t1an5t/ipc-monitor/qiling-master/qiling/os/os.py", line 9, in <module>
    from .utils import QLOsUtils
  File "/home/t1an5t/ipc-monitor/qiling-master/qiling/os/utils.py", line 13, in <module>
    from keystone import *
  File "/usr/local/lib/python3.6/dist-packages/keystone/__init__.py", line 4, in <module>
    from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, __version__
  File "/usr/local/lib/python3.6/dist-packages/keystone/keystone.py", line 75, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./m.py", line 5, in <module>
    ql = Qiling(path, rootfs)
  File "/home/t1an5t/ipc-monitor/qiling-master/qiling/core.py", line 180, in __init__
    self.os = self.os_setup()
  File "/home/t1an5t/ipc-monitor/qiling-master/qiling/core_utils.py", line 113, in os_setup
    return ql_get_module_function(module_name, function_name)(self)
  File "/home/t1an5t/ipc-monitor/qiling-master/qiling/utils.py", line 169, in ql_get_module_function
    raise QlErrorModuleNotFound("[!] Unable to import module %s" % module_name)
qiling.exception.QlErrorModuleNotFound: [!] Unable to import module qiling.os.linux.linux
````
My OS is Ubuntu 18.04.2 LTS in VMFusion, and kernel verison is 5.3.0-51-generic, and python version is 3.6.9. All of wheels' version in requirements.txt are right.
It seems like a dynamic library problem, but I don't know how to deal with that.

**Comment by xwings** [comment]
Hi,

can you try dev branch please ?

**Comment by tianstcht** [comment]
ok，it works, thank you!!
