### ISSUE TITLE
Unable to import module qiling.os.linux.linux

### ISSUE THREAD

**Issue by LKMDang** [qilingframework/qiling#284]
On my Ubuntu Desktop 18.04 VM, right after the installation, I try to run `hello_x8664_linux.py` in the `examples` dir and I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/qiling-1.0-py3.6.egg/qiling/utils.py", line 167, in ql_get_module_function
    imp_module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/qiling-1.0-py3.6.egg/qiling/os/linux/linux.py", line 9, in <module>
    from qiling.os.posix.posix import QlOsPosix
  File "/usr/local/lib/python3.6/dist-packages/qiling-1.0-py3.6.egg/qiling/os/posix/posix.py", line 13, in <module>
    from qiling.os.os import QlOs
  File "/usr/local/lib/python3.6/dist-packages/qiling-1.0-py3.6.egg/qiling/os/os.py", line 9, in <module>
    from .utils import QLOsUtils
  File "/usr/local/lib/python3.6/dist-packages/qiling-1.0-py3.6.egg/qiling/os/utils.py", line 13, in <module>
    from keystone import *
  File "/usr/local/lib/python3.6/dist-packages/keystone/__init__.py", line 4, in <module>
    from .keystone import Ks, ks_version, ks_arch_supported, version_bind, debug, KsError, __version__
  File "/usr/local/lib/python3.6/dist-packages/keystone/keystone.py", line 75, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
ImportError: ERROR: fail to load the dynamic library.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./hello_x8664_linux.py", line 10, in <module>
    ql = Qiling(["rootfs/x8664_linux/bin/x8664_hello"], "rootfs/x8664_linux")
  File "/usr/local/lib/python3.6/dist-packages/qiling-1.0-py3.6.egg/qiling/core.py", line 180, in __init__
    self.os = self.os_setup()
  File "/usr/local/lib/python3.6/dist-packages/qiling-1.0-py3.6.egg/qiling/core_utils.py", line 113, in os_setup
    return ql_get_module_function(module_name, function_name)(self)
  File "/usr/local/lib/python3.6/dist-packages/qiling-1.0-py3.6.egg/qiling/utils.py", line 169, in ql_get_module_function
    raise QlErrorModuleNotFound("[!] Unable to import module %s" % module_name)
qiling.exception.QlErrorModuleNotFound: [!] Unable to import module qiling.os.linux.linux
```
Did anyone face this problem before or know how to fix it? Thank you.

**Comment by xwings** [comment]
Hi,

are you on Qiling dev branch ? 

please refer to: https://docs.qiling.io/en/latest/faq/

**Comment by LKMDang** [comment]
switched to dev branch, it works now. Thank you very much.
