### ISSUE TITLE
An error occured in ql_syscall_fstat64

### ISSUE THREAD

**Issue by minghangshen** [qilingframework/qiling#314]
Hello, I use it to fuzz arm-demo which code is same as x8664_fuzz.

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Program that will crash easily.
#define SIZE (10)

int fun(int i) {
    char *buf = malloc(SIZE);
    char buf2[SIZE];
    while (*buf = getc(stdin) == 'A') {
        buf[i++] = *buf;
    }
    strncpy(buf2, buf, i);
    printf(buf2);
    return 0;
}

int main(int argc, char **argv) {
    return fun(argc);
}
```

command :
`aarch64-linux-gnu-gcc ./test.c -o ./test`

and I run `AFL_DEBUG_CHILD_OUTPUT=1 sh ./fuzz.sh`
It crashed 

```
Traceback (most recent call last):
  File "./fuzz_x8664_linux.py", line 156, in <module>
    main(sys.argv[1])
  File "./fuzz_x8664_linux.py", line 141, in main
    ql.run()
  File "/usr/local/lib/python3.6/site-packages/qiling-1.1a1-py3.6.egg/qiling/core.py", line 197, in run
    self.os.run()
  File "/usr/local/lib/python3.6/site-packages/qiling-1.1a1-py3.6.egg/qiling/os/linux/linux.py", line 119, in run
    raise self.ql.internal_exception
  File "/usr/local/lib/python3.6/site-packages/qiling-1.1a1-py3.6.egg/qiling/utils.py", line 19, in wrapper
    return func(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/qiling-1.1a1-py3.6.egg/qiling/core_hooks.py", line 112, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "/usr/local/lib/python3.6/site-packages/qiling-1.1a1-py3.6.egg/qiling/core_hooks.py", line 34, in call
    return self.callback(ql, *args)
  File "/usr/local/lib/python3.6/site-packages/qiling-1.1a1-py3.6.egg/qiling/os/linux/linux.py", line 65, in hook_syscall
    return self.load_syscall(intno)
  File "/usr/local/lib/python3.6/site-packages/qiling-1.1a1-py3.6.egg/qiling/os/posix/posix.py", line 94, in load_syscall
    self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "/usr/local/lib/python3.6/site-packages/qiling-1.1a1-py3.6.egg/qiling/os/posix/syscall/stat.py", line 80, in ql_syscall_fstat64
    fstat64_info = ql.os.file_des[user_fileno].fstat()
AttributeError: 'NoneType' object has no attribute 'fstat'
```

I don't know why it happened. could you help me to solve it?

**Comment by xwings** [comment]
can u try to run your binary manually and figure out the issue ?

**Comment by AsmitaJha08** [comment]
Hello @minghangshen 
I think you need to set syscall for this. I had similar issue , then in qiling script, I did these changes 
```
def my_syscall_fstat(ql, fstat64_fd, fstat64_buf, fstat64_count, *args, **kw):
    return 0

def run_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, output="debug")
    ql.set_syscall("fstat64", my_syscall_fstat)

```
And it worked in my case. Probably you can check.

Regards
Asmita

**Comment by xwings** [comment]
It should not be that way. 

But that is a good way to demo how you use set_syscall

**Comment by AsmitaJha08** [comment]
Yes, in my case error mentioned was `Syscall Error : ql_syscall_fstat64 DEBUG ... (Screenshot attached)
![Selection_240](https://user-images.githubusercontent.com/57127733/83767816-b381ee80-a69b-11ea-8b2a-15b95297452b.png)

**Comment by xwings** [comment]
looks like this is a very old version. Can u try the latest dev branch ?

**Comment by minghangshen** [comment]
Thank you. I have sovled it by another way.
