### ISSUE TITLE
KeyError: b'_crt_debugger_hook'

### ISSUE THREAD

**Issue by 0x1shyboy1** [qilingframework/qiling#35]
root@ubuntu:~/tool/qiling-master/examples# python3 regdemo_x86_windows.py 
[+] SET_THREAD_AREA selector : 0x73
[+] SET_THREAD_AREA selector : 0x7b
[+] SET_THREAD_AREA selector : 0x83
[+] SET_THREAD_AREA selector : 0x8b
[+] SET_THREAD_AREA selector : 0x90
WARNING: Registry files format error['  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/os/windows/registry.py", line 76, in __init__\n    self.hklm[\'SAM\'] = Registry.Registry(os.path.join(self.hive, \'SAM\'))\n']
[+] Loading rootfs/x86_windows/bin/RegDemo.exe to 0x400000
[+] PE entry point at 0x401381
[+] Initiate stack address at 0xfffdd000 
[+] TEB addr is 0x6000
[+] PEB addr is 0x6044
[+] Loading rootfs/x86_windows/dlls/kernel32.dll to 0x10000000
[+] Done with loading rootfs/x86_windows/dlls/kernel32.dll
[+] Loading rootfs/x86_windows/dlls/advapi32.dll to 0x100b2000
[+] Done with loading rootfs/x86_windows/dlls/advapi32.dll
[+] Loading rootfs/x86_windows/dlls/msvcr110.dll to 0x10155000
[+] Done with loading rootfs/x86_windows/dlls/msvcr110.dll
Traceback (most recent call last):
  File "regdemo_x86_windows.py", line 25, in <module>
    my_sandbox(["rootfs/x86_windows/bin/RegDemo.exe"], "rootfs/x86_windows")
  File "regdemo_x86_windows.py", line 18, in my_sandbox
    ql = Qiling(path, rootfs, output = "debug")
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/core.py", line 176, in __init__
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/core.py", line 185, in run_exec
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/os/windows/x86.py", line 109, in loader_file
  File "/usr/local/lib/python3.6/dist-packages/qiling-0.9-py3.6.egg/qiling/loader/pe.py", line 313, in load
KeyError: b'_crt_debugger_hook'

**Comment by xwings** [comment]
do you dump the registry file ?

**Comment by 0x1shyboy1** [comment]
sorry!!! I know why . I make a stupid mistake.I used 64 bit dll (C:\\windows\system32\\).the correct way is to use dll of C:\Windows\SysWOW64

**Comment by xwings** [comment]
Ok, I will close the issue now.
