### ISSUE TITLE
Windows - Referenced before assignment error

### ISSUE THREAD

**Issue by hackingump** [qilingframework/qiling#366]
```python
>>> ql = qiling.Qiling(["/home/ubuntu/Tools/Samples/pts-tinype/hh1.golden.exe"],"windowsenv/rootfs/x86_windows")
[+] Initiate stack address at 0xfffdd000
[+] Loading /home/ubuntu/Tools/Samples/pts-tinype/hh1.golden.exe to 0x400000
[+] PE entry point at 0x403000
[+] TEB addr is 0x6000
[+] PEB addr is 0x6044
[+] Loading windowsenv/rootfs/x86_windows/Windows/SysWOW64/ntdll.dll to 0x10000000
[+] Done with loading windowsenv/rootfs/x86_windows/Windows/SysWOW64/ntdll.dll
[+] Loading windowsenv/rootfs/x86_windows/Windows/SysWOW64/kernel32.dll to 0x10175000
[+] Done with loading windowsenv/rootfs/x86_windows/Windows/SysWOW64/kernel32.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.pyenv/versions/3.6.1/lib/python3.6/site-packages/qiling-1.1a2-py3.6.egg/qiling/core.py", line 178, in __init__
    self.loader.run()
  File "/home/ubuntu/.pyenv/versions/3.6.1/lib/python3.6/site-packages/qiling-1.1a2-py3.6.egg/qiling/loader/pe.py", line 312, in run
    self.load()
  File "/home/ubuntu/.pyenv/versions/3.6.1/lib/python3.6/site-packages/qiling-1.1a2-py3.6.egg/qiling/loader/pe.py", line 407, in load
    address = self.ql.pack32(addr)
UnboundLocalError: local variable 'addr' referenced before assignment
>>>
```

The following error happens when I try to execute Windows PE binaries on a linux ubuntu 16.04 system. DLLs are taken from a Windows 7 machine.

**Comment by xwings** [comment]
Not too sure with Windows 7, will you be able to try to Windows 10 and see the difference ?

**Comment by hackingump** [comment]
```python
In [5]: ql = qiling.Qiling(["/home/zorro/Projects/WinRun-Qiling/pts-tinype/hh3.golden.exe"], rootfs="/home/zorro/Projects/WinRun-Qiling/Win10-Libraries-Qiling/rootfs/x86_windows/", output = "debug")             
[+] Windows Registry PATH: /home/zorro/Projects/WinRun-Qiling/Win10-Libraries-Qiling/rootfs/x86_windows/Windows/registry
[+] Initiate stack address at 0xfffdd000 
[+] Loading /home/zorro/Projects/WinRun-Qiling/pts-tinype/hh3.golden.exe to 0x400000
[+] PE entry point at 0x401000
[+] TEB addr is 0x6000
[+] PEB addr is 0x6044
[+] Loading /home/zorro/Projects/WinRun-Qiling/Win10-Libraries-Qiling/rootfs/x86_windows/Windows/SysWOW64/ntdll.dll to 0x10000000
[+] Done with loading /home/zorro/Projects/WinRun-Qiling/Win10-Libraries-Qiling/rootfs/x86_windows/Windows/SysWOW64/ntdll.dll
[+] Loading /home/zorro/Projects/WinRun-Qiling/Win10-Libraries-Qiling/rootfs/x86_windows/Windows/SysWOW64/kernel32.dll to 0x1019c000
[+] Done with loading /home/zorro/Projects/WinRun-Qiling/Win10-Libraries-Qiling/rootfs/x86_windows/Windows/SysWOW64/kernel32.dll
[+] Done with loading /home/zorro/Projects/WinRun-Qiling/pts-tinype/hh3.golden.exe

In [6]: ql.run()                                                                                                                                                                                                   
0x101be390: GetStdHandle(nStdHandle = 0xfffffff5) = 0xfffffff5
Hello, World!
0x101c0020: WriteFile(hFile = 0xfffffff5, lpBuffer = 0x402000, nNumberOfBytesToWrite = 0xf, lpNumberOfBytesWritten = 0xffffcff8, lpOverlapped = 0x0) = 0x1
0x101c0f20: ExitProcess(uExitCode = 0x0)

```

The problem really occurs with Windows 7 libraries. This time I used Windows 10 DLLs. It might be a good hint to mention that Windows 10 DLLs should be used :-).

From my side, I dont have any questions regarding this ticket anymore, it can be closed.
