### ISSUE TITLE
Error in futex() syscall

### ISSUE THREAD

**Issue by alexander-pick** [qilingframework/qiling#383]
I am getting an error  in the futex() syscall which I cannot make any sense of. Any tipp how this crash could be solved?

**Crash Snippet**
```
openat(-100, /sys/devices/system/cpu/online, 0x80000, 0o14130260541) = 3
read(3, 0x80000000bcc0, 0x2000) = 4
close(3) = 0
futex(80000000dd9c, 7, 0) = ?
[!] Syscall ERROR: ql_syscall_futex DEBUG: 'NoneType' object has no attribute 'cur_thread'
futex(80000000dadc, 7, 0) = ?
[!] Syscall ERROR: ql_syscall_futex DEBUG: 'NoneType' object has no attribute 'cur_thread'
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    my_sandbox(["<removed>"], "rootfs/")
  File "test.py", line 10, in my_sandbox
    ql.run()
  File "/home/alx/.local/lib/python3.8/site-packages/qiling/core.py", line 198, in run
    self.os.run()
  File "/home/alx/.local/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 129, in run
    raise self.ql.internal_exception
  File "/home/alx/.local/lib/python3.8/site-packages/qiling/utils.py", line 19, in wrapper
    return func(*args, **kw)
  File "/home/alx/.local/lib/python3.8/site-packages/qiling/core_hooks.py", line 121, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "/home/alx/.local/lib/python3.8/site-packages/qiling/core_hooks.py", line 36, in call
    return self.callback(ql, *args)
  File "/home/alx/.local/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 65, in hook_syscall
    return self.load_syscall(intno)
  File "/home/alx/.local/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 167, in load_syscall
    self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "/home/alx/.local/lib/python3.8/site-packages/qiling/os/posix/syscall/futex.py", line 60, in ql_syscall_futex
    ql.os.thread_management.cur_thread.stop()
AttributeError: 'NoneType' object has no attribute 'cur_thread'

```

**Comment by ucgJhe** [comment]
the error indicate that you are running a multi-threading binary so you need to set `ql.multithread = True`

**Comment by alexander-pick** [comment]
Thanks a lot, the solution worked!
