### ISSUE TITLE
Error during emulation

### ISSUE THREAD

**Issue by aj-00** [qilingframework/qiling#407]
Hi,
I was trying to emulate a boa binary from a firmware. I am successfully able to emulate it using qemu. Tried with qiling. Getting error as in the image below.
![image](https://user-images.githubusercontent.com/57127733/88881385-ec2de680-d24c-11ea-8e1e-0c07bc63ba73.png)

Any guidance would be helpful.

Thanks
Asmita

**Comment by xwings** [comment]
clearly error msg? file not found ?

**Comment by AsmitaJha08** [comment]
Yes it says about glibc, I tried downloading precompiled Glibc for ARM 32-bit, got confused in that process. Wanted to know if u all have come across such issue, then how do u proceed? From where do we download and which location in the extracted filesystem, should I put it, I have very very limited knowledge in this field.

**Comment by ucgJhe** [comment]
no, mostly you just need to make some links

**Comment by aj-00** [comment]
Hi,
Can you please elaborate like what links to create. Do I need to create dummy files for all file not found error I am getting? On scrolling up, I can see many files not found error, 
![image](https://user-images.githubusercontent.com/57127733/88942022-55dade80-d2a7-11ea-85c7-1d39fd5502a8.png)

so in this case, would just creating dummy file at that location should work or do I need to symbolically link it to something?

**Comment by xwings** [comment]
if this is a firmware, u need to use the original libc from the firmware

**Comment by aj-00** [comment]
Hi,
libc.so is already in the rootfs after extracting the firmware.
![image](https://user-images.githubusercontent.com/57127733/88944928-fbdc1800-d2aa-11ea-812a-785eb2fa14c4.png)

Also, yes there is libssl present

![image](https://user-images.githubusercontent.com/57127733/88945056-1dd59a80-d2ab-11ea-85e6-6c8d5a2744f4.png)

So, it means I need to create link to these files in the respective locations where file not found error is coming

**Comment by AsherDLL** [comment]
I am facing a very similar issue, but in my case it's after executing an fstat64:
![image](https://user-images.githubusercontent.com/8671727/88983321-873fb400-d27f-11ea-8908-1112c458098d.png)

```
[!] Emulation Error

[-] zero	:	 0x0
[-] at	:	 0xfffffff8
[-] v0	:	 0x0
[-] v1	:	 0xcad0
[-] a0	:	 0x7ff3c978
[-] a1	:	 0x0
[-] a2	:	 0x0
[-] a3	:	 0x7ff3c978
[-] t0	:	 0x0
[-] t1	:	 0x0
[-] t2	:	 0x0
[-] t3	:	 0xffffffff
[-] t4	:	 0x47ba000
[-] t5	:	 0xf0000000
[-] t6	:	 0x1
[-] t7	:	 0x775f2f98
[-] s0	:	 0x1000
[-] s1	:	 0x0
[-] s2	:	 0x512
[-] s3	:	 0x7
[-] s4	:	 0x776d575c
[-] s5	:	 0x1
[-] s6	:	 0x3
[-] s7	:	 0x20
[-] t8	:	 0xfed
[-] t9	:	 0x7778fa30
[-] k0	:	 0x0
[-] k1	:	 0x0
[-] gp	:	 0x77813490
[-] sp	:	 0x7ff3c898
[-] s8	:	 0x7ff3c8e0
[-] ra	:	 0x0
[-] status	:	 0x0
[-] lo	:	 0x0
[-] hi	:	 0x0
[-] badvaddr	:	 0x0
[-] cause	:	 0x0
[-] pc	:	 0x0
[-] cp0_config3	:	 0x0
[-] cp0_userlocal	:	 0x0

[+] PC = 0x0 
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/qiling/os/linux/linux.py", line 123, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/usr/local/lib/python3.8/dist-packages/qiling/core.py", line 257, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "emulator.py", line 85, in <module>
    my_emulator(["cpio-root/bin/lighttpd",
  File "emulator.py", line 28, in my_emulator
    ql.run()
  File "/usr/local/lib/python3.8/dist-packages/qiling/core.py", line 198, in run
    self.os.run()
  File "/usr/local/lib/python3.8/dist-packages/qiling/os/linux/linux.py", line 126, in run
    self.emu_error()
  File "/usr/local/lib/python3.8/dist-packages/qiling/os/os.py", line 83, in emu_error
    buf = self.ql.mem.read(self.ql.reg.arch_pc, 8)
  File "/usr/local/lib/python3.8/dist-packages/qiling/os/memory.py", line 179, in read
    return self.ql.uc.mem_read(addr, size)
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn.py", line 435, in mem_read
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)
```

**Comment by AsherDLL** [comment]
The last instructions were the next:

```
:: 0x77767af4:	addiu	$v0, $zero, 0x1077
:: 0x77767af8:	syscall	
0x77767afc: ('[+] Received Interupt: 17 Hooked Interupt: 17',)
fstat64(7, 0x7ff3c820) = 0
0x77767afc: ('[+] fstat64 write completed',)
:: 0x77767afc:	beqz	$a3, 0x77767b1c
:: 0x77767b00:	move	$s0, $v0
:: 0x77767b1c:	bnez	$v0, 0x77767b40
:: 0x77767b20:	lw	$ra, 0x8c($sp)
:: 0x77767b24:	lw	$t9, -0x7fd0($gp)
:: 0x77767b28:	sw	$v0, 0x80($sp)
:: 0x77767b2c:	addiu	$a0, $sp, 0x18
:: 0x77767b30:	bal	0x7776cb68
:: 0x77767b34:	move	$a1, $a2
:: 0x7776cb68:	lui	$gp, 0xa
:: 0x7776cb6c:	addiu	$gp, $gp, 0x6928
:: 0x7776cb70:	addu	$gp, $gp, $t9
:: 0x7776cb74:	lw	$t9, -0x7f74($gp)
:: 0x7776cb78:	addiu	$sp, $sp, -0x28
:: 0x7776cb7c:	sw	$gp, 0x10($sp)
:: 0x7776cb80:	sw	$ra, 0x24($sp)
:: 0x7776cb84:	sw	$s1, 0x20($sp)
:: 0x7776cb88:	sw	$s0, 0x1c($sp)
:: 0x7776cb8c:	move	$s1, $a0
:: 0x7776cb90:	move	$s0, $a1
:: 0x7776cb94:	move	$a0, $a1
:: 0x7776cb98:	addiu	$a2, $zero, 0x98
:: 0x7776cb9c:	jalr	$t9
:: 0x7776cba0:	move	$a1, $zero
:: 0x7778fa30:	slti	$t1, $a2, 8
:: 0x7778fa34:	bnez	$t1, 0x7778faa4
:: 0x7778fa38:	move	$v0, $a0
:: 0x7778fa3c:	beqz	$a1, 0x7778fa54
:: 0x7778fa40:	andi	$a1, $a1, 0xff
:: 0x7778fa54:	negu	$t0, $a0
:: 0x7778fa58:	andi	$t0, $t0, 3
:: 0x7778fa5c:	beqz	$t0, 0x7778fa6c
:: 0x7778fa60:	subu	$a2, $a2, $t0
:: 0x7778fa6c:	andi	$t0, $a2, 7
:: 0x7778fa70:	beq	$t0, $a2, 0x7778fa90
:: 0x7778fa74:	subu	$a3, $a2, $t0
:: 0x7778fa78:	addu	$a3, $a3, $a0
:: 0x7778fa7c:	move	$a2, $t0
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa80:	addiu	$a0, $a0, 8
:: 0x7778fa84:	sw	$a1, -8($a0)
:: 0x7778fa88:	bne	$a0, $a3, 0x7778fa80
:: 0x7778fa8c:	sw	$a1, -4($a0)
:: 0x7778fa90:	andi	$t0, $a2, 4
:: 0x7778fa94:	beqz	$t0, 0x7778faa4
:: 0x7778fa98:	subu	$a2, $a2, $t0
:: 0x7778faa4:	blez	$a2, 0x7778fab8
:: 0x7778faa8:	addu	$a3, $a2, $a0
:: 0x7778fab8:	jr	$ra
:: 0x7778fabc:	nop	
:: 0x7776cba4:	lw	$v0, ($s1)
:: 0x7776cba8:	sw	$zero, 4($s0)
:: 0x7776cbac:	sw	$v0, ($s0)
:: 0x7776cbb0:	lw	$v0, 0x10($s1)
:: 0x7776cbb4:	sw	$v0, 0x10($s0)
:: 0x7776cbb8:	lw	$v0, 0x18($s1)
:: 0x7776cbbc:	sw	$v0, 0x14($s0)
:: 0x7776cbc0:	lw	$v0, 0x1c($s1)
:: 0x7776cbc4:	sw	$v0, 0x18($s0)
:: 0x7776cbc8:	lw	$v0, 0x20($s1)
:: 0x7776cbcc:	sw	$v0, 0x1c($s0)
:: 0x7776cbd0:	lw	$v0, 0x24($s1)
:: 0x7776cbd4:	sw	$v0, 0x20($s0)
:: 0x7776cbd8:	lw	$v0, 0x28($s1)
:: 0x7776cbdc:	sw	$zero, 0x2c($s0)
:: 0x7776cbe0:	sw	$v0, 0x28($s0)
:: 0x7776cbe4:	lw	$v0, 0x38($s1)
:: 0x7776cbe8:	sw	$v0, 0x34($s0)
:: 0x7776cbec:	lw	$v0, 0x58($s1)
:: 0x7776cbf0:	sw	$v0, 0x54($s0)
:: 0x7776cbf4:	lw	$v0, 0x60($s1)
:: 0x7776cbf8:	sw	$v0, 0x58($s0)
:: 0x7776cbfc:	lw	$v0, 0x40($s1)
:: 0x7776cc00:	sw	$v0, 0x3c($s0)
:: 0x7776cc04:	lw	$v0, 0x44($s1)
:: 0x7776cc08:	sw	$v0, 0x40($s0)
:: 0x7776cc0c:	lw	$v0, 0x48($s1)
:: 0x7776cc10:	sw	$v0, 0x44($s0)
:: 0x7776cc14:	lw	$v0, 0x4c($s1)
:: 0x7776cc18:	sw	$v0, 0x48($s0)
:: 0x7776cc1c:	lw	$v0, 0x50($s1)
:: 0x7776cc20:	sw	$v0, 0x4c($s0)
:: 0x7776cc24:	lw	$v0, 0x54($s1)
:: 0x7776cc28:	sw	$v0, 0x50($s0)
:: 0x7776cc2c:	lw	$ra, 0x24($sp)
:: 0x7776cc30:	lw	$s1, 0x20($sp)
:: 0x7776cc34:	lw	$s0, 0x1c($sp)
:: 0x7776cc38:	jr	$ra
:: 0x7776cc3c:	addiu	$sp, $sp, 0x28
:: 0x77767b38:	lw	$v0, 0x80($sp)
:: 0x77767b3c:	lw	$ra, 0x8c($sp)
:: 0x77767b40:	lw	$s0, 0x88($sp)
:: 0x77767b44:	jr	$ra
:: 0x77767b48:	addiu	$sp, $sp, 0x90
[!] Emulation Error
...
```

**Comment by xwings** [comment]
check all the location ? one by one ?

**Comment by xwings** [comment]
btw, these are are logical error. if a file is missing find it and match it back to the path required. u might need to fufill all to get it working.

**Comment by xwings** [comment]
there is a fix with how we process new path. will you be able to try it ?
