### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cur_thread'

### ISSUE THREAD

**Issue by bannsec** [qilingframework/qiling#431]
***Describe the bug**
Can't run example.

```
AttributeError: 'NoneType' object has no attribute 'cur_thread'
```

**Sample Code**
```bash
./qltool run --rootfs examples/rootfs/arm64_linux/ -f examples/rootfs/arm64_linux/bin/arm64_tcp_test
```

**Expected behavior**
Should be able to run the example test binary.

**Screenshots**

**Additional context**
```python
port is 22033.
[!] Syscall ERROR: ql_syscall_clone DEBUG: 'NoneType' object has no attribute 'cur_thread'
Traceback (most recent call last):
  File "./qltool", line 270, in <module>
    ql.run(timeout=timeout)
  File "/home/angr/qiling/qiling/core.py", line 198, in run
    self.os.run()
  File "/home/angr/qiling/qiling/os/linux/linux.py", line 130, in run
    raise self.ql.internal_exception
  File "/home/angr/qiling/qiling/utils.py", line 19, in wrapper
    return func(*args, **kw)
  File "/home/angr/qiling/qiling/core_hooks.py", line 121, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "/home/angr/qiling/qiling/core_hooks.py", line 36, in call
    return self.callback(ql, *args)
  File "/home/angr/qiling/qiling/os/linux/linux.py", line 65, in hook_syscall
    return self.load_syscall(intno)
  File "/home/angr/qiling/qiling/os/posix/posix.py", line 167, in load_syscall
    self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "/home/angr/qiling/qiling/os/posix/syscall/sched.py", line 51, in ql_syscall_clone
    f_th = ql.os.thread_management.cur_thread   
AttributeError: 'NoneType' object has no attribute 'cur_thread'
```

**Comment by xwings** [comment]
arm64_tcp_test is a thread'ed process. so u need to run with --multithread

**Comment by bannsec** [comment]
Ah gotcha. Do you support raw socket emulation?

**Comment by xwings** [comment]
In what context? maybe we have alternative.
