### ISSUE TITLE
Error trying to run qiling under Windows 10

### ISSUE THREAD

**Issue by KarlSimonsen** [qilingframework/qiling#435]
When trying to run qiling under WIndows we get the following error while emulating a linux program on Windows:

Error log:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\qiling\utils.py", line 151, in ql_get_module_function
    imp_module = importlib.import_module(module_name)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\qiling\os\linux\linux.py", line 9, in <module>
    from qiling.os.posix.posix import QlOsPosix
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\qiling\os\posix\posix.py", line 17, in <module>
    from qiling.os.posix.syscall import *
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\qiling\os\posix\syscall\__init__.py", line 12, in <module>
    from .resource import *
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\qiling\os\posix\syscall\resource.py", line 6, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ksimonsen\Downloads\qiling_test\qiling_debugger.py", line 14, in <module>
    ql = Qiling(sys.argv[1:], './')
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\qiling\core.py", line 175, in __init__
    self.os = self.os_setup()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\qiling\core_utils.py", line 145, in os_setup
    return ql_get_module_function(module_name, function_name)(self)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\qiling\utils.py", line 153, in ql_get_module_function
    raise QlErrorModuleNotFound("[!] Unable to import module %s" % module_name)
qiling.exception.QlErrorModuleNotFound: [!] Unable to import module qiling.os.linux.linux
```

If we comment out the resource import within resource.py and fix up all the references, that seems to "fix" it.
But the real issue is: Why is it trying to load a Linux resource under Windows?

**Comment by xwings** [comment]
qiling utils is a core share package between Windows and others. So, that is the reason why. 

there is a pull request fixing this issue, https://github.com/qilingframework/qiling/pull/403

please change to dev branch and you are good to go. checkout https://docs.qiling.io/en/latest/faq/#how-to-swtich-to-dev-branch
