### ISSUE TITLE
console = True/False affect function  ql_syscall_write  cann‘t write a bytearray to ql.os.file_des[write_fd] 

### ISSUE THREAD

**Issue by wonderkun** [qilingframework/qiling#444]
***Describe the bug**

**Sample Code**
```python
# file  ./qiling/os/posix/syscall/unistd.py

def ql_syscall_write(ql, write_fd, write_buf, write_count, *args, **kw):
    regreturn = 0
    buf = None

    try:
        buf = ql.mem.read(write_buf, write_count)
        if buf:
            ql.dprint(D_CTNT, "[+] write() CONTENT:")
            ql.dprint(D_CTNT, "%s" % buf)

        ql.nprint("write(%d,%x,%i) = %d" % (write_fd, write_buf, write_count, regreturn))
        ql.os.file_des[write_fd].write(buf)
        regreturn = write_count

    except:
        regreturn = -1
        ql.nprint("write(%d,%x,%i) = %d" % (write_fd, write_buf, write_count, regreturn))
        if ql.output in (QL_OUTPUT.DEBUG, QL_OUTPUT.DUMP):
            raise
    #if buf:
    #    ql.nprint(buf.decode(errors='ignore'))
    ql.os.definesyscall_return(regreturn)

```

**Expected behavior**

**Screenshots**

python3 crackme_x86_linux.py

Traceback (most recent call last):
  File "crackme_x86_linux.py", line 91, in <module>
    solve()
  File "crackme_x86_linux.py", line 76, in solve
    old_count = run_one_round(flag)
  File "crackme_x86_linux.py", line 65, in run_one_round
    ql.run()
  File "../qiling/core.py", line 198, in run
    self.os.run()
  File "../qiling/os/linux/linux.py", line 130, in run
    raise self.ql.internal_exception
  File "../qiling/utils.py", line 19, in wrapper
    return func(*args, **kw)
  File "../qiling/core_hooks.py", line 121, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "../qiling/core_hooks.py", line 36, in call
    return self.callback(ql, *args)
  File "../qiling/os/linux/linux.py", line 65, in hook_syscall
    return self.load_syscall(intno)
  File "../qiling/os/posix/posix.py", line 167, in load_syscall
    self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "../qiling/os/posix/syscall/unistd.py", line 267, in ql_syscall_write
    ql.os.file_des[write_fd].write(buf)
TypeError: write() argument must be str, not bytearray

**Additional context**

in python3, `ql.mem.read` return a bytearray, but`ql.os.file_des[write_fd].write(buf)` need a str, so we must decode it.
But there is some difficulty to fix this bug because we don't how to decode it. I decode it as `latin-1` in   flare-emu

**Comment by xwings** [comment]
I tested dev branch and it seems to be another issue. The issue u mentin did not appear.

can u try to pull dev branch and try the same example again ?

fix in https://github.com/qilingframework/qiling/commit/2b6f3a475597e393c385165650e4faadf89c836c

**Comment by wonderkun** [comment]
ok, Set console=True can fix this problem, but I don't know  why. 

Another problem is that! 

```
_llseek(0, 0xffffffff, 0xffffffff, 0x1 = 0)
[!] Syscall ERROR: ql_syscall__llseek DEBUG: 'MyPipe' object has no attribute 'lseek'
Traceback (most recent call last):
  File "crackme_x86_linux.py", line 89, in <module>
    solve()
  File "crackme_x86_linux.py", line 74, in solve
    old_count = run_one_round(flag)
  File "crackme_x86_linux.py", line 63, in run_one_round
    ql.run()
  File "../qiling/core.py", line 198, in run
    self.os.run()
  File "../qiling/os/linux/linux.py", line 130, in run
    raise self.ql.internal_exception
  File "../qiling/utils.py", line 19, in wrapper
    return func(*args, **kw)
  File "../qiling/core_hooks.py", line 121, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "../qiling/core_hooks.py", line 36, in call
    return self.callback(ql, *args)
  File "../qiling/os/linux/linux.py", line 65, in hook_syscall
    return self.load_syscall(intno)
  File "../qiling/os/posix/posix.py", line 167, in load_syscall
    self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "../qiling/os/posix/syscall/unistd.py", line 155, in ql_syscall__llseek
    ret = ql.os.file_des[fd].lseek(offset, origin)
AttributeError: 'MyPipe' object has no attribute 'lseek'
```
Define `lseek`  function for MyPipe class.  
I suggest defining a base class for stdin、 stdout and stderr and default function. When need to hijack the stdin or stdout , the use can inherit the base class to avoid some error!

**Comment by xwings** [comment]
check my commit. i fixed the lseek issue already,

pull the new code for dev branch.

**Comment by wonderkun** [comment]
ok, thx.

**Comment by xwings** [comment]
I will reopen this, the console = True  / False issue is a problem.

@ucgJhe will you be able to help ?

**Comment by xwings** [comment]
case close
