### ISSUE TITLE
arm_tcp_test/arm_multithreading fails

### ISSUE THREAD

**Issue by uhx** [qilingframework/qiling#488]
***Describe the bug**
Trying to run example `arm_linux/bin/arm_tcp_test` or `arm_multithreading` and it fails with error `'NoneType' object has no attribute 'cur_thread'`

**Sample Code**
```python
if __name__ == "__main__":

    root = os.path.abspath('../qiling')

    rootfs = os.path.join(root, 'examples/rootfs/arm_linux')
    sample = os.path.join(rootfs, 'bin/arm_tcp_test')

    ql = qiling.Qiling([sample], rootfs)

    ql.run()
```

Output:

```log
...
mmap2(0x0, 0x13e540, 0x5, 0x802, 3, 0) = 0x774c2000
mprotect(0x775eb000, 0x10000, 0x0) = 0
mmap2(0x775fb000, 0x3000, 0x3, 0x812, 3, 1216512) = 0x775fb000
mmap2(0x775fe000, 0x2540, 0x3, 0x32, -1, 0) = 0x775fe000
close(3) = 0
settls(0x774c17e0)
mprotect(0x775fb000, 0x2000, 0x1) = 0
mprotect(0x20000, 0x1000, 0x1) = 0
mprotect(0x47ea000, 0x1000, 0x1) = 0
write(2,7ff3a810,15) = 0
port is 22033.
[!] Syscall ERROR: ql_syscall_clone DEBUG: 'NoneType' object has no attribute 'cur_thread'
[!] Emulation Error

[-] r0	:	 0x1200011
[-] r1	:	 0x0
[-] r2	:	 0x0
[-] r3	:	 0x0
[-] r4	:	 0x774c1388
[-] r5	:	 0x0
[-] r6	:	 0x0
[-] r7	:	 0x78
[-] r8	:	 0x0
[-] r9	:	 0x775fd000
[-] r10	:	 0x47eb000
[-] r11	:	 0x7ff3cd64
[-] r12	:	 0x774c1320
[-] sp	:	 0x7ff3cd38
[-] lr	:	 0x7755e068
[-] pc	:	 0x7755e178
[-] cpsr	:	 0x600001d3
[-] c1_c0_2	:	 0xf00000
[-] c13_c0_3	:	 0x774c17e0
[-] fpexc	:	 0x40000000

[+] PC = 0x7755e178
[+] Start      End        Perm.  Path
[+] 00010000 - 00011000 - r-x    /home/user/Projects/qiling/examples/rootfs/arm_linux/bin/arm_tcp_test (/home/user/Projects/qiling/examples/rootfs/arm_linux/bin/arm_tcp_test)
[+] 00020000 - 00022000 - rw-    /home/user/Projects/qiling/examples/rootfs/arm_linux/bin/arm_tcp_test (/home/user/Projects/qiling/examples/rootfs/arm_linux/bin/arm_tcp_test)
[+] 00022000 - 00024000 - rwx    [hook_mem] (/home/user/Projects/qiling/examples/rootfs/arm_linux/bin/arm_tcp_test)
[+] 047ba000 - 047ec000 - rwx    /home/user/Projects/qiling/examples/rootfs/arm_linux/lib/ld-linux.so.3
[+] 774bf000 - 774c2000 - rwx    [syscall_mmap2]
[+] 774c2000 - 775fb000 - rwx    [mmap2] /home/user/Projects/qiling/examples/rootfs/arm_linux/lib/tls/libc.so.6
[+] 775fb000 - 775fe000 - rwx    [mmap2] /home/user/Projects/qiling/examples/rootfs/arm_linux/lib/tls/libc.so.6
[+] 775fe000 - 77601000 - rwx    [mmap2] /home/user/Projects/qiling/examples/rootfs/arm_linux/lib/tls/libc.so.6
[+] 7ff0d000 - 7ff3d000 - rwx    [stack]
[+] ffff0000 - ffff1000 - rwx    [arm_tls]
[+] ['0x1', '0xa', '0x70', '0xe3', '0x0', '0x60', '0xa0', '0xe1']

[+] 0x7755e178     01 0a 70 e3 00 60 a0 e1 2c 00 00 8a 00 00 50 e3 30 00 00 1a 6c 32 9f e5 03 30 8f e0 00 30 93 e5 00 00 53 e3 00 20 93 15 04 20 82 12 00 20 83 15 54 32 9f e5 03 30 8f e0 00 30 93 e5 00 00 53 e3 cmn r0, #0x1000
mov r6, r0
bhi #0x7755e238
cmp r0, #0
bne #0x7755e250
ldr r3, [pc, #0x26c]
add r3, pc, r3
ldr r3, [r3]
cmp r3, #0
ldrne r2, [r3]
addne r2, r2, #4
strne r2, [r3]
ldr r3, [pc, #0x254]
add r3, pc, r3
ldr r3, [r3]
cmp r3, #0
Traceback (most recent call last):
  File "run.py", line 20, in <module>
    ql.run()
  File "/home/user/.local/lib/python3.7/site-packages/qiling/core.py", line 197, in run
    self.os.run()
  File "/home/user/.local/lib/python3.7/site-packages/qiling/os/linux/linux.py", line 124, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/user/.local/lib/python3.7/site-packages/qiling/core.py", line 259, in emu_start
    raise self.internal_exception
  File "/home/user/.local/lib/python3.7/site-packages/qiling/utils.py", line 19, in wrapper
    return func(*args, **kw)
  File "/home/user/.local/lib/python3.7/site-packages/qiling/core_hooks.py", line 121, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "/home/user/.local/lib/python3.7/site-packages/qiling/core_hooks.py", line 36, in call
    return self.callback(ql, *args)
  File "/home/user/.local/lib/python3.7/site-packages/qiling/os/linux/linux.py", line 65, in hook_syscall
    return self.load_syscall(intno)
  File "/home/user/.local/lib/python3.7/site-packages/qiling/os/posix/posix.py", line 178, in load_syscall
    raise e
  File "/home/user/.local/lib/python3.7/site-packages/qiling/os/posix/posix.py", line 169, in load_syscall
    self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "/home/user/.local/lib/python3.7/site-packages/qiling/os/posix/syscall/sched.py", line 51, in ql_syscall_clone
    f_th = ql.os.thread_management.cur_thread	
AttributeError: 'NoneType' object has no attribute 'cur_thread'
```

**Expected behavior**
Obviously, it should just work and finish up correctly :)

**Additional context**
branch: **master**, **qiling-1.1.1**, **Python 3.7.3**

**Comment by xwings** [comment]
Obviously you did not check the FAQ :)


https://docs.qiling.io/en/latest/faq/#syscall-not-implemented-or-attributeerror-nonetype-object-has-no-attribute-cur_thread-error

**Comment by uhx** [comment]
:D sorry I was trying to find it on GitHub and forgot about docs
