### ISSUE TITLE
Request for more documentation & Some help

### ISSUE THREAD

**Issue by zi0Black** [qilingframework/qiling#507]
## Context
I'm trying to emulate the `mini_httpd` binary of the NETGEAR R6220 router, but I'm experiencing the problem of reading access to an unmapped memory area: Invalid memory read (UC_ERR_READ_UNMAPPED).
I tried to trace where the error occurs, but it doesn't seem to be very useful since the exception occurs during a call to `__malloc_consolidate` in `libuClibc.9.3`.

## Idea
I thought to look for some functionality that would allow me to put a hook on the `UC_ERR_READ_UNMAPPED` exception; I found the following function that seems to be right for me: `ql.hook_mem_unmapped()`. The hope is to be able to either find some more information about the error or maybe to map that memory area dynamically and see what happens.

```python
def my_memory_manager(ql, *args):
    saved_args = locals()
    print("saved args:",  saved_args)
    #if ql.mem.is_available(addr, size):
    #    ql.mem.map(addr,size,info = [my_first_map])
[...]
ql.hook_mem_unmapped(my_memory_manager)
```
Output:
```bash
saved args: {'ql': <qiling.core.Qiling object at 0x7fb9698eda00>, 'args': (19, 12, 4, 0)}
```

## Request
Unfortunately, the documentation on the following two pages is particularly "poor":
- https://docs.qiling.io/en/latest/hook/
- https://docs.qiling.io/en/latest/memory/

So I have two questions:

- Is my idea completely wrong, or does it make any sense?
- Could you share some information about these features and their use? (here or in the documentation)

Please be verbose in your answers (so at most I try to integrate with external resources if I understand the context better).

I appreciate any help you can provide.

**Comment by xwings** [comment]
Maybe this will help ?

https://docs.qiling.io/en/latest/faq/#uc_err_fetch_unmapped-uc_err_write_unmapped-and-related-issues

**Comment by xwings** [comment]
Or rather u can disasm and dump our the context. That is how you find the issue.

**Comment by zi0Black** [comment]
> Or rather u can disasm and dump our the context. That is how you find the issue.

```
open(/var/lock/tmp_nvram.lock, 0x241, 0o600) = -2
[+] open(/var/lock/tmp_nvram.lock, O_RDONLY | O_WRONLY | O_TRUNC | 64, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/var/lock/tmp_nvram.lock
open(/tmp/nvram, 0x0, 0o600) = -2
[+] open(/tmp/nvram, O_RDONLY, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/tmp/nvram
open(/var/lock/etc_default.lock, 0x241, 0o600) = -2
[+] open(/var/lock/etc_default.lock, O_RDONLY | O_WRONLY | O_TRUNC | 64, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/var/lock/etc_default.lock
open(/etc/default, 0x0, 0o600) = -2
[+] open(/etc/default, O_RDONLY, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/etc/default
open(/var/lock/tmp_nvram.lock, 0x241, 0o600) = -2
[+] open(/var/lock/tmp_nvram.lock, O_RDONLY | O_WRONLY | O_TRUNC | 64, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/var/lock/tmp_nvram.lock
open(/tmp/nvram, 0x0, 0o600) = -2
[+] open(/tmp/nvram, O_RDONLY, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/tmp/nvram
open(/var/lock/etc_default.lock, 0x241, 0o600) = -2
[+] open(/var/lock/etc_default.lock, O_RDONLY | O_WRONLY | O_TRUNC | 64, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/var/lock/etc_default.lock
open(/etc/default, 0x0, 0o600) = -2
[+] open(/etc/default, O_RDONLY, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/etc/default
open(/var/lock/tmp_nvram.lock, 0x241, 0o600) = -2
[+] open(/var/lock/tmp_nvram.lock, O_RDONLY | O_WRONLY | O_TRUNC | 64, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/var/lock/tmp_nvram.lock
open(/tmp/nvram, 0x0, 0o600) = -2
[+] open(/tmp/nvram, O_RDONLY, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/tmp/nvram
open(/var/lock/etc_default.lock, 0x241, 0o600) = -2
[+] open(/var/lock/etc_default.lock, O_RDONLY | O_WRONLY | O_TRUNC | 64, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/var/lock/etc_default.lock
open(/etc/default, 0x0, 0o600) = -2
[+] open(/etc/default, O_RDONLY, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/etc/default
[!] Emulation Error

[-] zero        :        0x0
[-] at  :        0x774c1cc4
[-] v0  :        0x0
[-] v1  :        0x31
[-] a0  :        0x43002e
[-] a1  :        0x0
[-] a2  :        0x180
[-] a3  :        0x1
[-] t0  :        0x2
[-] t1  :        0x75616665
[-] t2  :        0x200
[-] t3  :        0x100
[-] t4  :        0x807
[-] t5  :        0x800
[-] t6  :        0x400
[-] t7  :        0x8
[-] s0  :        0x420000
[-] s1  :        0x410000
[-] s2  :        0x420000
[-] s3  :        0x420000
[-] s4  :        0x420000
[-] s5  :        0x420000
[-] s6  :        0x420000
[-] s7  :        0x420000
[-] t8  :        0x0
[-] t9  :        0x777995c0
[-] k0  :        0x0
[-] k1  :        0x0
[-] gp  :        0x42b080
[-] sp  :        0x7ff36be0
[-] s8  :        0x430018
[-] ra  :        0x40a0e4
[-] status      :        0x0
[-] lo  :        0x0
[-] hi  :        0x0
[-] badvaddr    :        0x0
[-] cause       :        0x0
[-] pc  :        0x777995c0
[-] cp0_config3 :        0x2000
[-] cp0_userlocal       :        0x7783c470

[+] PC = 0x777995c0
[+] Start      End        Perm.  Path
[+] 00400000 - 00413000 - r-x    /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/bin/mini_httpd (/home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/bin/mini_httpd)
[+] 00422000 - 00424000 - rw-    /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/bin/mini_httpd (/home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/bin/mini_httpd)
[+] 00424000 - 0042e000 - rwx    /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/bin/mini_httpd (/home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/bin/mini_httpd)
[+] 0042e000 - 00430000 - rwx    [hook_mem] (/home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/bin/mini_httpd)
[+] 00430000 - 00431000 - rwx    [brk]
[+] 047ba000 - 047d3000 - rwx    /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/ld-uClibc.so.0
[+] 774bf000 - 774c0000 - rwx    [syscall_mmap]
[+] 774c1000 - 774c4000 - rwx    [mmap] /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/libscnvram.so
[+] 774c4000 - 774d3000 - rwx    [syscall_mmap]
[+] 774d3000 - 774d4000 - rwx    [mmap] /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/libscnvram.so
[+] 774d5000 - 77533000 - rwx    [mmap] /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/libssl.so.0.9.8
[+] 77533000 - 77542000 - rwx    [syscall_mmap]
[+] 77542000 - 77548000 - rwx    [mmap] /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/libssl.so.0.9.8
[+] 77549000 - 776fd000 - rwx    [mmap] /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/libcrypto.so.0.9.8
[+] 776fd000 - 7770c000 - rwx    [syscall_mmap]
[+] 7770c000 - 77723000 - rwx    [mmap] /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/libcrypto.so.0.9.8
[+] 77723000 - 77725000 - rwx    [syscall_mmap]
[+] 77726000 - 77752000 - rwx    [mmap] /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/libgcc_s.so.1
[+] 77752000 - 77761000 - rwx    [syscall_mmap]
[+] 77761000 - 77762000 - rwx    [mmap] /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/libgcc_s.so.1
[+] 77763000 - 77809000 - rwx    [mmap] /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/libuClibc-0.9.33.2.so
[+] 77809000 - 77818000 - rwx    [syscall_mmap]
[+] 77818000 - 7781a000 - rwx    [mmap] /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/libuClibc-0.9.33.2.so
[+] 7781a000 - 77820000 - rwx    [syscall_mmap]
[+] 77821000 - 77824000 - rwx    [mmap] /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/libdl-0.9.33.2.so
[+] 77824000 - 77833000 - rwx    [syscall_mmap]
[+] 77833000 - 77835000 - rwx    [mmap] /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/lib/libdl-0.9.33.2.so
[+] 77835000 - 77836000 - rwx    [syscall_mmap]
[+] 7ff0d000 - 7ff3d000 - rwx    [stack]
[+] ['0x0', '0x0', '0x83', '0x90', '0x0', '0x0', '0xa2', '0x90']

[+] 0x777995c0     00 00 83 90 00 00 a2 90 01 00 84 24 03 00 60 14 01 00 a5 24 08 00 e0 03 23 10 02 00 f9 ff 62 50 00 00 83 90 23 10 62 00 08 00 e0 03 00 00 00 00 21 10 80 00 03 00 00 10 21 18 80 00 01 00 a5 24 lbu $v1, ($a0)
lbu $v0, ($a1)
addiu $a0, $a0, 1
bnez $v1, 0x777995dc
addiu $a1, $a1, 1
jr $ra
negu $v0, $v0
beql $v1, $v0, 0x777995c4
lbu $v1, ($a0)
subu $v0, $v1, $v0
jr $ra
nop 
move $v0, $a0
b 0x77799604
move $v1, $a0
addiu $a1, $a1, 1
Traceback (most recent call last):
  File "run.py", line 45, in <module>
    my_netgear(["rootfs/netgear_R6220/bin/mini_httpd",
  File "run.py", line 41, in my_netgear
    ql.run()
  File "/usr/local/lib/python3.8/dist-packages/qiling/core.py", line 197, in run
    self.os.run()
  File "/usr/local/lib/python3.8/dist-packages/qiling/os/linux/linux.py", line 113, in run
    thread_management.run()
  File "/usr/local/lib/python3.8/dist-packages/qiling/os/linux/thread.py", line 455, in run
    self.runing_time += self.cur_thread.run(bbl_slice = thread_slice, mode = BBL_MODE)
  File "/usr/local/lib/python3.8/dist-packages/qiling/os/linux/thread.py", line 132, in run
    self.ql.emu_start(self.start_address, self.exit_point)
  File "/usr/local/lib/python3.8/dist-packages/qiling/core.py", line 256, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)
``` 
This is the output from the script, but I guess you want a some kind of different dump?

**Comment by xwings** [comment]
seems like etc default is missing and execve() needs it?

**Comment by zi0Black** [comment]
> seems like etc default is missing and execve() needs it?

I think all the files and links are in the right place:
```
z0b@host:~/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220$ ls -la
total 88
drwxr-xrwx 11 z0b z0b  4096 Sep  5 17:17 .
drwxr-xrwx  3 z0b z0b  4096 Sep  5 17:37 ..
lrwxrwxrwx  1 z0b z0b     9 Sep  5 17:17 bin -> usr/sbin/
drwxr-xrwx  2 z0b z0b  4096 Sep  5 17:20 dev
lrwxrwxrwx  1 z0b z0b     8 Sep  5 17:17 etc -> /tmp/etc
lrwxrwxrwx  1 z0b z0b    11 Sep  5 17:17 etc_ro -> /tmp/etc_ro
drwxr-xrwx  2 z0b z0b  4096 Sep  5 17:17 home
lrwxrwxrwx  1 z0b z0b    11 Sep  5 17:17 init -> bin/busybox
drwxr-xrwx  5 z0b z0b 20480 Sep  5 17:17 lib
drwxr-xrwx  2 z0b z0b  4096 Sep  5 17:17 media
lrwxrwxrwx  1 z0b z0b     8 Sep  5 17:17 mnt -> /tmp/mnt
drwxr-xrwx  2 z0b z0b  4096 Sep  5 17:17 proc
lrwxrwxrwx  1 z0b z0b    13 Sep  5 17:17 root -> /tmp/smb_root
lrwxrwxrwx  1 z0b z0b     9 Sep  5 17:17 sbin -> usr/sbin/
drwxr-xrwx  2 z0b z0b  4096 Sep  5 17:17 sys
drwxr-xrwx  8 z0b z0b  4096 Sep  5 17:57 tmp
drwxr-xrwx 10 z0b z0b  4096 Sep  5 17:17 usr
lrwxrwxrwx  1 z0b z0b     8 Sep  5 17:17 var -> /tmp/var
-rw-r--rwx  1 z0b z0b  1035 Sep  5 17:17 watchdog.conf
lrwxrwxrwx  1 z0b z0b     8 Sep  5 17:17 www -> /tmp/www
drwxr-xrwx  9 z0b z0b 28672 Sep  5 17:17 www.eng
z0b@host:~/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220$ ls -la tmp/
total 56
drwxr-xrwx  8 z0b z0b  4096 Sep  5 17:57 .
drwxr-xrwx 11 z0b z0b  4096 Sep  5 17:17 ..
drwxr-xr-x 16 z0b z0b  4096 Sep  5 17:56 etc
drwxr-xr-x  9 z0b z0b  4096 Sep  5 17:57 etc_ro
drwxr-xr-x  2 z0b z0b  4096 Sep  5 17:51 mnt
drwxr-xr-x  2 z0b z0b  4096 Sep  5 17:51 smb_root
drwxr-xr-x  3 z0b z0b  4096 Sep  5 17:54 var
drwxr-xr-x  9 z0b z0b 28672 Sep  5 17:49 www
z0b@host:~/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220$ 
```
And `default` is present under `etc`:
```
z0b@host:~/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220$ ls -la tmp/etc/ | grep default
-rw-r--r-x  1 z0b z0b  13585 Sep  5 17:56 default
```

**Comment by cq674350529** [comment]
@zi0Black  According to the error log above, I guess the `qiling` framework didn't handle sym link properly in your case. As can be seen, the final path of `/etc/default` is `/home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/etc/default`, actually it should be `/home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/tmp/etc/default`.  

```
open(/etc/default, 0x0, 0o600) = -2
[+] open(/etc/default, O_RDONLY, 0o600) = -2
[!] File Not Found /home/z0b/Research/QIling/Test/httpserver-example/rootfs/netgear_R6220/etc/default
``` 

There is something need to do with path transfer. A quick way to test this is to change `etc -> /tmp/etc` into `etc -> tmp/etc`, or copy these files in `/tmp/etc` into `etc` manually.

Actually, I came across similar issues recently, but I didn't have time to look at it yet.

**Comment by xwings** [comment]
@cq674350529 is right. 

But again, we updated and it should work by now. 

We got a test for this case,   in test_elf.py.

btw, please use @cq674350529 suggestion and try. I am not sure did we screw it up again.

**Comment by zi0Black** [comment]
I recreate the symlink pointing locally to `tmp/etc`, and now everything works.

Thanks, @cq674350529, for the fix.

Thanks also to you, @xwings, for the assistance.
