### ISSUE TITLE
ModuleNotFoundError: No module named 'magic'

### ISSUE THREAD

**Issue by zbx911** [qilingframework/qiling#533]
D:\Anaconda3_x64\python.exe "C:\PyCharm 2020.2.1\plugins\python\helpers\pydev\pydevd.py" --multiproc --save-signatures --qt-support=auto --client 127.0.0.1 --port 60309 --file M:/qiling/qiling-master/tests/test_android.py
pydev debugger: process 3780 is connecting

Connected to pydev debugger (build 202.6948.78)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Anaconda3_x64\lib\site-packages\qiling\__init__.py", line 1, in <module>
    from .core import Qiling
  File "D:\Anaconda3_x64\lib\site-packages\qiling\core.py", line 15, in <module>
    from .core_utils import QlCoreUtils
  File "D:\Anaconda3_x64\lib\site-packages\qiling\core_utils.py", line 18, in <module>
    from .loader.utils import ql_checkostype
  File "D:\Anaconda3_x64\lib\site-packages\qiling\loader\utils.py", line 7, in <module>
    import magic
  File "D:\Anaconda3_x64\lib\site-packages\magic.py", line 201, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by zbx911** [comment]
pip3 install --user https://github.com/qilingframework/qiling/archive/dev.zip 解决

**Comment by OevreFlataeker** [comment]
Still get the same error using plain python38 under Windows 10 even after @zbx911's suggestion. Tried the PIP and cloned variant from github directly. Also tried installing various versions of python-magic-0.4.x with the same result. Do I need to install another 3rd party DLL?

**Comment by xwings** [comment]
As per setup.py , 

```
pip3 install python-magic-bin
```
![image](https://user-images.githubusercontent.com/463553/95012112-4cd00a00-0668-11eb-9e10-771d718800a6.png)

**Comment by OevreFlataeker** [comment]
Strange... seems as if another a wrong build with the correct version was installed.

```
PS D:\> C:\Python38\Scripts\pip3 install python-magic-bin
Requirement already satisfied: python-magic-bin in c:\python38\lib\site-packages\python_magic_bin-0.4.14-py3.8-win-amd64.egg (0.4.14)
PS D:\> C:\Python38\python.exe
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from qiling import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\daubsi\AppData\Roaming\Python\Python38\site-packages\qiling\__init__.py", line 1, in <module>
    from .core import Qiling
  File "C:\Users\daubsi\AppData\Roaming\Python\Python38\site-packages\qiling\core.py", line 15, in <module>
    from .core_utils import QlCoreUtils
  File "C:\Users\daubsi\AppData\Roaming\Python\Python38\site-packages\qiling\core_utils.py", line 18, in <module>
    from .loader.utils import ql_checkostype
  File "C:\Users\daubsi\AppData\Roaming\Python\Python38\site-packages\qiling\loader\utils.py", line 7, in <module>
    import magic
  File "C:\Python38\lib\site-packages\magic.py", line 201, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
>>> exit()
PS D:\> C:\Python38\Scripts\pip3 uninstall python-magic-bin
Found existing installation: python-magic-bin 0.4.14
Uninstalling python-magic-bin-0.4.14:
  Would remove:
    c:\python38\lib\site-packages\python_magic_bin-0.4.14-py3.8-win-amd64.egg
Proceed (y/n)? y
  Successfully uninstalled python-magic-bin-0.4.14
PS D:\> C:\Python38\Scripts\pip3 install python-magic-bin
Collecting python-magic-bin
  Downloading python_magic_bin-0.4.14-py2.py3-none-win_amd64.whl (409 kB)
     |████████████████████████████████| 409 kB 2.2 MB/s
Installing collected packages: python-magic-bin
Successfully installed python-magic-bin-0.4.14
PS D:\> C:\Python38\python.exe
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from qiling import *
>>>
```

**Comment by xwings** [comment]
that is a libmagic issue ?
