### ISSUE TITLE
AttributeError: '_io.TextIOWrapper' object has no attribute 'fstat'

### ISSUE THREAD

**Issue by zbx911** [qilingframework/qiling#534]
Traceback (most recent call last):
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\linux\linux.py", line 113, in run
    thread_management.run()
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\linux\thread.py", line 455, in run
    self.runing_time += self.cur_thread.run(bbl_slice = thread_slice, mode = BBL_MODE)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\linux\thread.py", line 132, in run
    self.ql.emu_start(self.start_address, self.exit_point)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\core.py", line 255, in emu_start
    raise self.internal_exception
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\utils.py", line 19, in wrapper
    return func(*args, **kw)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\core_hooks.py", line 121, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\core_hooks.py", line 36, in call
    return self.callback(ql, *args)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\linux\linux.py", line 66, in hook_syscall
    return self.load_syscall(intno)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\posix\posix.py", line 178, in load_syscall
    raise e
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\posix\posix.py", line 169, in load_syscall
    self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\posix\syscall\stat.py", line 218, in ql_syscall_fstat
    fstat_info = ql.os.fd[user_fileno].fstat()
AttributeError: '_io.TextIOWrapper' object has no attribute 'fstat'

Process finished with exit code 1

**Comment by xwings** [comment]
Again, try in WSL2

**Comment by zbx911** [comment]
AttributeError: '_io.TextIOWrapper' object has no attribute 'fstat'  跟WSL2有啥关系？python的版本会因为是wsl2而强化？

**Comment by xwings** [comment]
NTFS对文件分析缺乏 这个问题还在修复中 WSL2本身是linux的fs

**Comment by bkerler** [comment]
Should be fixed with PR #580
