### ISSUE TITLE
qiling.exception.QlErrorFileNotFound: Error: Registry files not found in 'rootfs/x86_windows\Windows\registry'!

### ISSUE THREAD

**Issue by zbx911** [qilingframework/qiling#536]
D:\Anaconda3_x64_2020_7\python.exe "C:\PyCharm 2020.2.1\plugins\python\helpers\pydev\pydevd.py" --multiproc --save-signatures --qt-support=auto --client 127.0.0.1 --port 53296 --file M:/qiling/qiling-learn/examples/crackme_x86_windows_auto.py
pydev debugger: process 9248 is connecting

Connected to pydev debugger (build 202.6948.78)
Traceback (most recent call last):
  File "C:\PyCharm 2020.2.1\plugins\python\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\PyCharm 2020.2.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "M:/qiling/qiling-learn/examples/crackme_x86_windows_auto.py", line 60, in <module>
    our_sandbox(["rootfs/x86_windows/bin/Easy_CrackMe.exe"], "rootfs/x86_windows")
  File "M:/qiling/qiling-learn/examples/crackme_x86_windows_auto.py", line 51, in our_sandbox
    ql = Qiling(path, rootfs)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\core.py", line 172, in __init__
    self.loader.run()
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\loader\pe.py", line 311, in run
    self.ql.os.setupComponents()
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\windows\windows.py", line 63, in setupComponents
    self.registry_manager = RegistryManager(self.ql)
  File "C:\Users\zzzz\AppData\Roaming\Python\Python38\site-packages\qiling\os\windows\registry.py", line 44, in __init__
    raise QlErrorFileNotFound(f"Error: Registry files not found in '{self.hive}'!")
qiling.exception.QlErrorFileNotFound: Error: Registry files not found in 'rootfs/x86_windows\Windows\registry'!

**Comment by xwings** [comment]
Error: Registry files not found in 'rootfs/x86_windows\Windows\registry'!

Please follow https://docs.qiling.io/en/latest/install/

**Comment by SwordFaith** [comment]
It seems both master and dev branch lack of rootfs/x86_windows/windows directory, how can I solve this problem by install ?

**Comment by xwings** [comment]
> It seems both master and dev branch lack of rootfs/x86_windows/windows directory, how can I solve this problem by install ?

https://docs.qiling.io/en/latest/install/#important-note-on-windows-dlls-and-registry
