### ISSUE TITLE
Simulate a arm64_android exeacute so have error Unreachable

### ISSUE THREAD

**Issue by Hho-hyj** [qilingframework/qiling#551]
***Describe the bug**
I want simulate a arm64_android exeacute so with qilingframework, but it failed. It give an error Unreachable.

**Sample Code**
```python
import sys
sys.path.append("..")
from qiling import *

if __name__ == "__main__":
    ql = Qiling(["rootfs/arm64_android/bin/qiling_test"], "rootfs/arm64_android", output="debug" )
    ql.run()
```

**operation result**
```
[+] load 0x555555554000 - 0x555555555000
[+] load 0x555555555000 - 0x555555557000
[+] mem_start: 0x0 mem_end: 0x3000
[+] interp is : rootfs/arm64_android/system/bin/linker64
[+] interp_mem_size is : 0x15d000
[+] interp_address is : 0x7ffff7dd5000
[+] mmap_address is : 0x7fffb7dd6000
[+] rel name b'printf'
[+] rel name b'__libc_init'
[+] rel name b'__cxa_atexit'
[+] log mmap - mmap(0x0, 0x5000, 0x0, 0x22, 4294967295, 0)
[+] log mmap - mmap(0x0, 0x5000, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, 4294967295, 0)
[+] log mmap - return addr : 0x7fffb7dd6000
[+] log mmap - addr range  : 0x7fffb7dd6000 - 0x7fffb7ddb000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7dd6000  length 0x5000
mmap(0x0, 0x5000, 0x0, 0x22, 4294967295, 0) = 0x7fffb7dd6000
[+] mmap_base is 0x7fffb7dd6000
prctl() = 0
mprotect(0x7fffb7dd7000, 0x3000, 0x3) = 0
[+] mprotect(0x7fffb7dd7000, 0x3000, PROT_READ | PROT_WRITE) = 0
prctl() = 0
set_tid_address(7ffff7f2c9c0) = 7149
facccessat (4294967196, 0x7ffff7e93972, 0x4) = -1
[!] File Not Found or Skipped: /dev/urandom
futex(7ffff7f29268, 129, 2147483647) = 0
[+] log mmap - mmap(0x0, 0x5000, 0x3, 0x22, 4294967295, 0)
[+] log mmap - mmap(0x0, 0x5000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 4294967295, 0)
[+] log mmap - return addr : 0x7fffb7ddb000
[+] log mmap - addr range  : 0x7fffb7ddb000 - 0x7fffb7de0000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7ddb000  length 0x5000
mmap(0x0, 0x5000, 0x3, 0x22, 4294967295, 0) = 0x7fffb7ddb000
[+] mmap_base is 0x7fffb7ddb000
mprotect(0x7fffb7ddb000, 0x1000, 0x0) = 0
[+] mprotect(0x7fffb7ddb000, 0x1000, PROT_NONE) = 0
[!] 0x7ffff7e854d8: syscall ql_syscall_sigaltstack number = 0x84(132) not implemented
prctl() = 0
prctl() = 0
mprotect(0x7ffff7eba000, 0x4000, 0x1) = 0
[+] mprotect(0x7ffff7eba000, 0x4000, PROT_READ) = 0
mprotect(0x7ffff7f2b000, 0x1000, 0x1) = 0
[+] mprotect(0x7ffff7f2b000, 0x1000, PROT_READ) = 0
mprotect(0x7ffff7f2b000, 0x1000, 0x3) = 0
[+] mprotect(0x7ffff7f2b000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7ffff7f2b000, 0x1000, 0x1) = 0
[+] mprotect(0x7ffff7f2b000, 0x1000, PROT_READ) = 0
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 4294967295, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 4294967295, 0)
[+] log mmap - return addr : 0x7fffb7de0000
[+] log mmap - addr range  : 0x7fffb7de0000 - 0x7fffb7de1000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de0000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 4294967295, 0) = 0x7fffb7de0000
[+] mmap_base is 0x7fffb7de0000
prctl() = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
getrandom(0x80000000ca20, 0x28, 0x1) = 40
[+] log mmap - mmap(0x0, 0x450, 0x3, 0x22, 4294967295, 0)
[+] log mmap - mmap(0x0, 0x450, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 4294967295, 0)
[+] log mmap - return addr : 0x7fffb7de1000
[+] log mmap - addr range  : 0x7fffb7de1000 - 0x7fffb7de2000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de1000  length 0x1000
mmap(0x0, 0x450, 0x3, 0x22, 4294967295, 0) = 0x7fffb7de1000
[+] mmap_base is 0x7fffb7de1000
prctl() = 0
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7de2000
[+] log mmap - addr range  : 0x7fffb7de2000 - 0x7fffb7de3000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de2000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7de2000
[+] mmap_base is 0x7fffb7de2000
prctl() = 0
[+] log mmap - mmap(0x0, 0x18, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x18, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7de3000
[+] log mmap - addr range  : 0x7fffb7de3000 - 0x7fffb7de4000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de3000  length 0x1000
mmap(0x0, 0x18, 0x3, 0x22, 0, 0) = 0x7fffb7de3000
[+] mmap_base is 0x7fffb7de3000
prctl() = 0
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7de4000
[+] log mmap - addr range  : 0x7fffb7de4000 - 0x7fffb7de5000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de4000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7de4000
[+] mmap_base is 0x7fffb7de4000
prctl() = 0
[+] log mmap - mmap(0x0, 0x18, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x18, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7de5000
[+] log mmap - addr range  : 0x7fffb7de5000 - 0x7fffb7de6000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de5000  length 0x1000
mmap(0x0, 0x18, 0x3, 0x22, 0, 0) = 0x7fffb7de5000
[+] mmap_base is 0x7fffb7de5000
prctl() = 0
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7de6000
[+] log mmap - addr range  : 0x7fffb7de6000 - 0x7fffb7de7000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de6000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7de6000
[+] mmap_base is 0x7fffb7de6000
prctl() = 0
mprotect(0x7fffb7de6000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de6000, 0x1000, PROT_READ | PROT_WRITE) = 0
fstatat64(0xffffff9c, /dev/__properties__) = -1
[!] Directory Not Found: /dev/__properties__
openat(4294967196, /dev/__properties__, 0x88000, 0o0) = -1
[+] openat(4294967196, /dev/__properties__, O_RDONLY | 557056, 0o0) = -1
[!] File Not Found /home/hyj/qiling/examples/rootfs/arm64_android/dev/__properties__
[+] log mmap - mmap(0x0, 0x3000, 0x0, 0x22, 4294967295, 0)
[+] log mmap - mmap(0x0, 0x3000, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, 4294967295, 0)
[+] log mmap - return addr : 0x7fffb7de7000
[+] log mmap - addr range  : 0x7fffb7de7000 - 0x7fffb7dea000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7de7000  length 0x3000
mmap(0x0, 0x3000, 0x0, 0x22, 4294967295, 0) = 0x7fffb7de7000
[+] mmap_base is 0x7fffb7de7000
mprotect(0x7fffb7de8000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de8000, 0x1000, PROT_READ | PROT_WRITE) = 0
rt_sigaction(0x6, 0x80000000ca68, = 0x0) = 0
rt_sigaction(0x7, 0x80000000ca68, = 0x0) = 0
rt_sigaction(0x8, 0x80000000ca68, = 0x0) = 0
rt_sigaction(0x4, 0x80000000ca68, = 0x0) = 0
rt_sigaction(0xb, 0x80000000ca68, = 0x0) = 0
rt_sigaction(0x10, 0x80000000ca68, = 0x0) = 0
rt_sigaction(0x1f, 0x80000000ca68, = 0x0) = 0
rt_sigaction(0x5, 0x80000000ca68, = 0x0) = 0
rt_sigaction(0x23, 0x80000000ca68, = 0x0) = 0
prctl() = 0
fstatat64(0xffffff9c, /proc/self/exe) = 0
[+] Directory Found: /proc/self/exe
mprotect(0x7fffb7de0000, 0x1000, 0x3) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x7fffb7de0000, 0x1000, 0x1) = 0
[+] mprotect(0x7fffb7de0000, 0x1000, PROT_READ) = 0
futex(7ffff7f29268, 129, 2147483647) = 0
readlinkat(0xffffff9c, 0x7ffff7e8cd2a, 0x80000000ce00, 0x1000) = 62
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7dea000
[+] log mmap - addr range  : 0x7fffb7dea000 - 0x7fffb7deb000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7dea000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7dea000
[+] mmap_base is 0x7fffb7dea000
prctl() = 0
[+] log mmap - mmap(0x0, 0x18, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x18, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7deb000
[+] log mmap - addr range  : 0x7fffb7deb000 - 0x7fffb7dec000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7deb000  length 0x1000
mmap(0x0, 0x18, 0x3, 0x22, 0, 0) = 0x7fffb7deb000
[+] mmap_base is 0x7fffb7deb000
prctl() = 0
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7dec000
[+] log mmap - addr range  : 0x7fffb7dec000 - 0x7fffb7ded000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7dec000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7dec000
[+] mmap_base is 0x7fffb7dec000
prctl() = 0
openat(4294967196, /system/etc/ld.config.txt, 0x88000, 0o0) = 3
[+] openat(4294967196, /system/etc/ld.config.txt, O_RDONLY | 557056, 0o0) = 3
[+] File Found: /home/hyj/qiling/examples/rootfs/arm64_android/system/etc/ld.config.txt
fstat(3, 0x80000000b2d8) = 0
[+] fstat write completed
[+] log mmap - mmap(0x0, 0x7000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x7000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7ded000
[+] log mmap - addr range  : 0x7fffb7ded000 - 0x7fffb7df4000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7ded000  length 0x7000
mmap(0x0, 0x7000, 0x3, 0x22, 0, 0) = 0x7fffb7ded000
[+] mmap_base is 0x7fffb7ded000
prctl() = 0
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 1024
read(3, 0x80000000b358, 0x400) = 66
read(3, 0x80000000b358, 0x400) = 0
close(3) = 0
[+] log mmap - mmap(0x0, 0x7000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x7000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7df4000
[+] log mmap - addr range  : 0x7fffb7df4000 - 0x7fffb7dfb000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7df4000  length 0x7000
mmap(0x0, 0x7000, 0x3, 0x22, 0, 0) = 0x7fffb7df4000
[+] mmap_base is 0x7fffb7df4000
prctl() = 0
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7dfb000
[+] log mmap - addr range  : 0x7fffb7dfb000 - 0x7fffb7dfc000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7dfb000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7dfb000
[+] mmap_base is 0x7fffb7dfb000
prctl() = 0
[+] log mmap - mmap(0x0, 0x18, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x18, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7dfc000
[+] log mmap - addr range  : 0x7fffb7dfc000 - 0x7fffb7dfd000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7dfc000  length 0x1000
mmap(0x0, 0x18, 0x3, 0x22, 0, 0) = 0x7fffb7dfc000
[+] mmap_base is 0x7fffb7dfc000
prctl() = 0
munmap(0x7fffb7dfb000, 0x1000) = 0
munmap(0x7fffb7df4000, 0x7000) = 0
munmap(0x7fffb7ded000, 0x7000) = 0
fstatat64(0xffffff9c, /system) = 0
[+] Directory Found: /system
fstatat64(0xffffff9c, /system/lib64) = 0
[+] Directory Found: /system/lib64
fstatat64(0xffffff9c, /vendor) = -1
[!] Directory Not Found: /vendor
[+] log mmap - mmap(0x0, 0x1000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7dfd000
[+] log mmap - addr range  : 0x7fffb7dfd000 - 0x7fffb7dfe000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7dfd000  length 0x1000
mmap(0x0, 0x1000, 0x3, 0x22, 0, 0) = 0x7fffb7dfd000
[+] mmap_base is 0x7fffb7dfd000
prctl() = 0
openat(4294967196, /system/lib64/libm.so, 0x80000, 0o0) = 3
[+] openat(4294967196, /system/lib64/libm.so, O_RDONLY | 524288, 0o0) = 3
[+] File Found: /home/hyj/qiling/examples/rootfs/arm64_android/system/lib64/libm.so
[+] log mmap - mmap(0x0, 0x2000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x2000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7dfe000
[+] log mmap - addr range  : 0x7fffb7dfe000 - 0x7fffb7e00000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7dfe000  length 0x2000
mmap(0x0, 0x2000, 0x3, 0x22, 0, 0) = 0x7fffb7dfe000
[+] mmap_base is 0x7fffb7dfe000
prctl() = 0
[+] log mmap - mmap(0x0, 0x2000, 0x3, 0x22, 0, 0)
[+] log mmap - mmap(0x0, 0x2000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap - return addr : 0x7fffb7e00000
[+] log mmap - addr range  : 0x7fffb7e00000 - 0x7fffb7e02000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7e00000  length 0x2000
mmap(0x0, 0x2000, 0x3, 0x22, 0, 0) = 0x7fffb7e00000
[+] mmap_base is 0x7fffb7e00000
prctl() = 0
readlinkat(0xffffff9c, 0x7fffb7e00010, 0x7fffb7dfe010, 0x1000) = -1
socket(1, 526338, 0) = 4
[+] socket(AF_LOCAL, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, 0) = 4
connect(/home/hyj/qiling/examples/rootfs/arm64_android/dev/socket/logdw) = -1
close(4) = 0
writev(0x2, 0x80000000c008, 0x4)
[+] writev() CONTENT:
bytearray(b'linker')
bytearray(b': ')
bytearray(b'readlink("/proc/self/fd/3") failed: Operation not permitted [fd=3]')
bytearray(b'\n')
munmap(0x7fffb7e00000, 0x2000) = 0
munmap(0x7fffb7dfe000, 0x2000) = 0
socket(1, 526338, 0) = 4
[+] socket(AF_LOCAL, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, 0) = 4
connect(/home/hyj/qiling/examples/rootfs/arm64_android/dev/socket/logdw) = -1
close(4) = 0
writev(0x2, 0x80000000c048, 0x4)
[+] writev() CONTENT:
bytearray(b'linker')
bytearray(b': ')
bytearray(b'warning: unable to get realpath for the library "/system/lib64/libm.so". Will use given path.')
bytearray(b'\n')
fstat(3, 0x80000000c850) = 0
[+] fstat write completed
[!] 0x7ffff7e75130: syscall ql_syscall_fstatfs number = 0x2c(44) not implemented
close(3) = 0
writev(0x2, 0x80000000c568, 0x2)
[+] writev() CONTENT:
bytearray(b'CANNOT LINK EXECUTABLE "rootfs/arm64_android/bin/qiling_test": unable to fstatfs file for the library "libm.so": Operation not permitted')
bytearray(b'\n')
socket(1, 526338, 0) = 3
[+] socket(AF_LOCAL, SOCK_STREAM | SOCK_NONBLOCK | SOCK_CLOEXEC, 0) = 3
connect(/home/hyj/qiling/examples/rootfs/arm64_android/dev/socket/logdw) = -1
close(3) = 0
writev(0x2, 0x80000000c3f8, 0x4)
[+] writev() CONTENT:
bytearray(b'libc')
bytearray(b': ')
bytearray(b'CANNOT LINK EXECUTABLE "rootfs/arm64_android/bin/qiling_test": unable to fstatfs file for the library "libm.so": Operation not permitted')
bytearray(b'\n')
[+] log mmap - mmap(0x0, 0x91, 0x3, 0x22, 4294967295, 0)
[+] log mmap - mmap(0x0, 0x91, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 4294967295, 0)
[+] log mmap - return addr : 0x7fffb7e02000
[+] log mmap - addr range  : 0x7fffb7e02000 - 0x7fffb7e03000
[+] log mmap - mapping needed
[+] mmap_base 0x7fffb7e02000  length 0x1000
mmap(0x0, 0x91, 0x3, 0x22, 4294967295, 0) = 0x7fffb7e02000
[+] mmap_base is 0x7fffb7e02000
getpid() = 1298
gettid() = 1996
rt_sigprocmask(0x2, 0x80000000c960, 0x80000000c958, 0x8) = 0
[!] 0x7ffff7e75520: syscall ql_syscall_tgkill number = 0x83(131) not implemented
rt_sigaction(0x6, 0x80000000c948, = 0x80000000c928) = 0
rt_sigprocmask(0x2, 0x80000000c960, 0x80000000c958, 0x8) = 0
[!] 0x7ffff7e75520: syscall ql_syscall_tgkill number = 0x83(131) not implemented
exit_group(127)
[!] Emulation Error

[-] x0	:	 0x80000000c990
[-] x1	:	 0x0
[-] x2	:	 0x698
[-] x3	:	 0x80000000c960
[-] x4	:	 0x0
[-] x5	:	 0x0
[-] x6	:	 0x0
[-] x7	:	 0x8
[-] x8	:	 0x1d58
[-] x9	:	 0x1d68
[-] x10	:	 0x1d78
[-] x11	:	 0x1
[-] x12	:	 0xffffffffffffffff
[-] x13	:	 0x0
[-] x14	:	 0x0
[-] x15	:	 0x30
[-] x16	:	 0x555555555fc8
[-] x17	:	 0x5d0
[-] x18	:	 0x1f1f0d2c
[-] x19	:	 0x512
[-] x20	:	 0x7cc
[-] x21	:	 0x55555555448a
[-] x22	:	 0x80000000ce08
[-] x23	:	 0x555555555f60
[-] x24	:	 0x7ffff7ebe280
[-] x25	:	 0x7ffff7ebf800
[-] x26	:	 0x7ffff7ebf860
[-] x27	:	 0x80000000de00
[-] x28	:	 0x7ffff7ebf000
[-] x29	:	 0x80000000c980
[-] x30	:	 0x555555554670
[-] sp	:	 0x80000000c960
[-] pc	:	 0x5d0
[-] cpacr_el1	:	 0x300000
[-] tpidr_el0	:	 0x7ffff7f2ca48

[+] PC = 0x5d0
[+] Start      End        Perm.  Path
[+] 555555554000 - 555555555000 - r-x    /home/hyj/qiling/examples/rootfs/arm64_android/bin/qiling_test (/home/hyj/qiling/examples/rootfs/arm64_android/bin/qiling_test)
[+] 555555555000 - 555555557000 - rw-    /home/hyj/qiling/examples/rootfs/arm64_android/bin/qiling_test (/home/hyj/qiling/examples/rootfs/arm64_android/bin/qiling_test)
[+] 555555557000 - 555555559000 - rwx    [hook_mem] (/home/hyj/qiling/examples/rootfs/arm64_android/bin/qiling_test)
[+] 7fffb7dd6000 - 7fffb7ddb000 - rwx    [syscall_mmap]
[+] 7fffb7ddb000 - 7fffb7de0000 - rwx    [syscall_mmap]
[+] 7fffb7de0000 - 7fffb7de1000 - rwx    [syscall_mmap]
[+] 7fffb7de1000 - 7fffb7de2000 - rwx    [syscall_mmap]
[+] 7fffb7de2000 - 7fffb7de3000 - rwx    [syscall_mmap]
[+] 7fffb7de3000 - 7fffb7de4000 - rwx    [syscall_mmap]
[+] 7fffb7de4000 - 7fffb7de5000 - rwx    [syscall_mmap]
[+] 7fffb7de5000 - 7fffb7de6000 - rwx    [syscall_mmap]
[+] 7fffb7de6000 - 7fffb7de7000 - rwx    [syscall_mmap]
[+] 7fffb7de7000 - 7fffb7dea000 - rwx    [syscall_mmap]
[+] 7fffb7dea000 - 7fffb7deb000 - rwx    [syscall_mmap]
[+] 7fffb7deb000 - 7fffb7dec000 - rwx    [syscall_mmap]
[+] 7fffb7dec000 - 7fffb7ded000 - rwx    [syscall_mmap]
[+] 7fffb7dfc000 - 7fffb7dfd000 - rwx    [syscall_mmap]
[+] 7fffb7dfd000 - 7fffb7dfe000 - rwx    [syscall_mmap]
[+] 7fffb7e02000 - 7fffb7e03000 - rwx    [syscall_mmap]
[+] 7ffff7dd5000 - 7ffff7f32000 - rwx    /home/hyj/qiling/examples/rootfs/arm64_android/system/bin/linker64
[+] 7ffffffde000 - 80000000e000 - rwx    [stack]
[!] Error: PC(0x5d0) Unreachable
Traceback (most recent call last):
  File "/home/hyj/qiling/examples/test.py", line 7, in <module>
    ql.run()
  File "/home/hyj/qiling/qiling/core.py", line 193, in run
    self.os.run()
  File "/home/hyj/qiling/qiling/os/linux/linux.py", line 125, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/hyj/qiling/qiling/core.py", line 252, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
```

I have already put libm.so in lib64 ,but it give:
CANNOT LINK EXECUTABLE "rootfs/arm64_android/bin/qiling_test": unable to fstatfs file for the library "libm.so": Operation not permitted
Do I need to change my progrem?

**Comment by xwings** [comment]
You might need this ?

```
[!] 0x7ffff7e75130: syscall ql_syscall_fstatfs number = 0x2c(44) not implemented
```

**Comment by Hho-hyj** [comment]
Yes, I implemented it and worked well. Thank you for your answer

**Comment by xwings** [comment]
You might want to PR your update ?
