### ISSUE TITLE
相同的Python文件可以在Linux下运行而不能在Windows下运行

### ISSUE THREAD

**Issue by Hho-hyj** [qilingframework/qiling#598]
***Describe the bug**
我编写了一个python文件测试qiling，它可以在linux下成功运行却不可以在windows下运行。

在linux下的日志：
```
[+] Enable ARM VFP
[+] Set init_kernel_get_tls
[+] load 0x56555000 - 0x56556000
[+] load 0x56556000 - 0x56558000
[+] mem_start: 0x0 mem_end: 0x3000
[+] interp is : rootfs/android_32/system/bin/linker
[+] interp_mem_size is : 0x12000
[+] interp_address is : 0x47ba000
[+] mmap_address is : 0x774bf000
[+] rel name b'__stack_chk_guard'
[+] rel name b'__libc_init'
[+] rel name b'__cxa_atexit'
[+] rel name b'printf'
[+] rel name b'__stack_chk_fail'
mprotect(0x47c9000, 0x1000, 0x1) = 0
[+] mprotect(0x47c9000, 0x1000, PROT_READ) = 0
ugetrlimit(3, 0x7ff3cda8) = 0
gettid() = 1996
settls(0x47caf24)
[+] log mmap2 - mmap2(0x0, 0x2000, 0x3, 0x22, 0, 0)
[+] log mmap2 - mmap2(0x0, 0x2000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap2 - return addr : 0x774bf000
[+] log mmap2 - addr range  : 0x774bf000 - 0x774c1000
[+] log mmap2 - mapping needed
mmap2(0x0, 0x2000, 0x3, 0x22, 0, 0) = 0x774bf000
[+] mmap2_base is 0x774bf000
madvise() = 0
[!] 0x47c2944: syscall ql_syscall_sigaltstack number = 0xba(186) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[+] log mmap2 - mmap2(0x0, 0xffc, 0x3, 0x22, 0, 0)
[+] log mmap2 - mmap2(0x0, 0xffc, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap2 - return addr : 0x774c1000
[+] log mmap2 - addr range  : 0x774c1000 - 0x774c2000
[+] log mmap2 - mapping needed
mmap2(0x0, 0xffc, 0x3, 0x22, 0, 0) = 0x774c1000
[+] mmap2_base is 0x774c1000
madvise() = 0
open(/vendor/lib/libm.so, 0xa0000, 0o0) = -2
[+] open(/vendor/lib/libm.so, O_RDONLY | O_NOFOLLOW | 524288, 0o0) = -2
[!] File Not Found /home/hyj/myqiling/rootfs/android_32/vendor/lib/libm.so
open(/system/lib/libm.so, 0xa0000, 0o0) = 3
[+] open(/system/lib/libm.so, O_RDONLY | O_NOFOLLOW | 524288, 0o0) = 3
[+] File Found: /home/hyj/myqiling/rootfs/android_32/system/lib/libm.so
read(3, 0x7ff3cd14, 0x34) = 52
[+] log mmap2 - mmap2(0x0, 0x1000, 0x1, 0x2, 3, 0)
[+] log mmap2 - mmap2(0x0, 0x1000, PROT_READ, MAP_PRIVATE, 3, 0)
[+] log mmap2 - return addr : 0x774c2000
[+] log mmap2 - addr range  : 0x774c2000 - 0x774c3000
[+] log mmap2 - mapping needed
[+] log mem write : 0x1000
[+] log mem mmap2  : /home/hyj/myqiling/rootfs/android_32/system/lib/libm.so
mmap2(0x0, 0x1000, 0x1, 0x2, 3, 0) = 0x774c2000
[+] mmap2_base is 0x774c2000
madvise() = 0
[+] log mmap2 - mmap2(0x0, 0x1a000, 0x0, 0x22, -1, 0)
[+] log mmap2 - mmap2(0x0, 0x1a000, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0)
[+] log mmap2 - return addr : 0x774c3000
[+] log mmap2 - addr range  : 0x774c3000 - 0x774dd000
[+] log mmap2 - mapping needed
mmap2(0x0, 0x1a000, 0x0, 0x22, -1, 0) = 0x774c3000
[+] mmap2_base is 0x774c3000
madvise() = 0
[+] log mmap2 - mmap2(0x774c3000, 0x17ee4, 0x5, 0x12, 3, 0)
[+] log mmap2 - mmap2(0x774c3000, 0x17ee4, PROT_READ | PROT_EXEC, MAP_PRIVATE | MAP_FIXED, 3, 0)
[+] log mmap2 - return addr : 0x774c3000
[+] log mmap2 - addr range  : 0x774c3000 - 0x774db000
[+] log mem write : 0x17ee4
[+] log mem mmap2  : /home/hyj/myqiling/rootfs/android_32/system/lib/libm.so
mmap2(0x774c3000, 0x17ee4, 0x5, 0x12, 3, 0) = 0x774c3000
[+] mmap2_base is 0x774c3000
madvise() = 0
[+] log mmap2 - mmap2(0x774db000, 0x106c, 0x3, 0x12, 3, 94208)
[+] log mmap2 - mmap2(0x774db000, 0x106c, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_FIXED, 3, 94208)
[+] log mmap2 - return addr : 0x774db000
[+] log mmap2 - addr range  : 0x774db000 - 0x774dd000
[+] log mem write : 0x106c
[+] log mem mmap2  : /home/hyj/myqiling/rootfs/android_32/system/lib/libm.so
mmap2(0x774db000, 0x106c, 0x3, 0x12, 3, 94208) = 0x774db000
[+] mmap2_base is 0x774db000
madvise() = 0
close(3) = 0
munmap(0x774c2000, 0x1000) = 0
open(/vendor/lib/libc.so, 0xa0000, 0o0) = -2
[+] open(/vendor/lib/libc.so, O_RDONLY | O_NOFOLLOW | 524288, 0o0) = -2
[!] File Not Found /home/hyj/myqiling/rootfs/android_32/vendor/lib/libc.so
open(/system/lib/libc.so, 0xa0000, 0o0) = 3
[+] open(/system/lib/libc.so, O_RDONLY | O_NOFOLLOW | 524288, 0o0) = 3
[+] File Found: /home/hyj/myqiling/rootfs/android_32/system/lib/libc.so
read(3, 0x7ff3cc4c, 0x34) = 52
[+] log mmap2 - mmap2(0x0, 0x1000, 0x1, 0x2, 3, 0)
[+] log mmap2 - mmap2(0x0, 0x1000, PROT_READ, MAP_PRIVATE, 3, 0)
[+] log mmap2 - return addr : 0x774dd000
[+] log mmap2 - addr range  : 0x774dd000 - 0x774de000
[+] log mmap2 - mapping needed
[+] log mem write : 0x1000
[+] log mem mmap2  : /home/hyj/myqiling/rootfs/android_32/system/lib/libc.so
mmap2(0x0, 0x1000, 0x1, 0x2, 3, 0) = 0x774dd000
[+] mmap2_base is 0x774dd000
madvise() = 0
[+] log mmap2 - mmap2(0x0, 0x5b000, 0x0, 0x22, -1, 0)
[+] log mmap2 - mmap2(0x0, 0x5b000, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0)
[+] log mmap2 - return addr : 0x774de000
[+] log mmap2 - addr range  : 0x774de000 - 0x77539000
[+] log mmap2 - mapping needed
mmap2(0x0, 0x5b000, 0x0, 0x22, -1, 0) = 0x774de000
[+] mmap2_base is 0x774de000
madvise() = 0
[+] log mmap2 - mmap2(0x774de000, 0x46ef0, 0x5, 0x12, 3, 0)
[+] log mmap2 - mmap2(0x774de000, 0x46ef0, PROT_READ | PROT_EXEC, MAP_PRIVATE | MAP_FIXED, 3, 0)
[+] log mmap2 - return addr : 0x774de000
[+] log mmap2 - addr range  : 0x774de000 - 0x77525000
[+] log mem write : 0x46ef0
[+] log mem mmap2  : /home/hyj/myqiling/rootfs/android_32/system/lib/libc.so
mmap2(0x774de000, 0x46ef0, 0x5, 0x12, 3, 0) = 0x774de000
[+] mmap2_base is 0x774de000
madvise() = 0
[+] log mmap2 - mmap2(0x77526000, 0x42e8, 0x3, 0x12, 3, 290816)
[+] log mmap2 - mmap2(0x77526000, 0x42e8, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_FIXED, 3, 290816)
[+] log mmap2 - return addr : 0x77526000
[+] log mmap2 - addr range  : 0x77526000 - 0x7752b000
[+] log mem write : 0x42e8
[+] log mem mmap2  : /home/hyj/myqiling/rootfs/android_32/system/lib/libc.so
mmap2(0x77526000, 0x42e8, 0x3, 0x12, 3, 290816) = 0x77526000
[+] mmap2_base is 0x77526000
madvise() = 0
[+] log mmap2 - mmap2(0x7752b000, 0xe000, 0x3, 0x32, -1, 0)
[+] log mmap2 - mmap2(0x7752b000, 0xe000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_FIXED | MAP_ANONYMOUS, -1, 0)
[+] log mmap2 - return addr : 0x7752b000
[+] log mmap2 - addr range  : 0x7752b000 - 0x77539000
mmap2(0x7752b000, 0xe000, 0x3, 0x32, -1, 0) = 0x7752b000
[+] mmap2_base is 0x7752b000
madvise() = 0
close(3) = 0
munmap(0x774dd000, 0x1000) = 0
mprotect(0x77526000, 0x2000, 0x1) = 0
[+] mprotect(0x77526000, 0x2000, PROT_READ) = 0
mprotect(0x774db000, 0x1000, 0x1) = 0
[+] mprotect(0x774db000, 0x1000, PROT_READ) = 0
mprotect(0x56556000, 0x1000, 0x1) = 0
[+] mprotect(0x56556000, 0x1000, PROT_READ) = 0
open(/dev/__properties__, 0xa8000, 0o0) = 3
[+] open(/dev/__properties__, O_RDONLY | O_NOFOLLOW | 557056, 0o0) = 3
[+] File Found: /home/hyj/myqiling/rootfs/android_32/dev/__properties__
fcntl64(3, 2, 1) = 0
fstat64(3, 0x7ff3cc70) = 0
[+] fstat64 write completed
[+] log mmap2 - mmap2(0x0, 0x20000, 0x1, 0x1, 3, 0)
[+] log mmap2 - mmap2(0x0, 0x20000, PROT_READ, MAP_SHARED, 3, 0)
[+] log mmap2 - return addr : 0x77539000
[+] log mmap2 - addr range  : 0x77539000 - 0x77559000
[+] log mmap2 - mapping needed
[+] log mem write : 0x20000
[+] log mem mmap2  : /home/hyj/myqiling/rootfs/android_32/dev/__properties__
mmap2(0x0, 0x20000, 0x1, 0x1, 3, 0) = 0x77539000
[+] mmap2_base is 0x77539000
close(3) = 0
futex(7752a540, 129, 2147483647) = 0
mprotect(0x774c1000, 0xffc, 0x3) = 0
[+] mprotect(0x774c1000, 0xffc, PROT_READ | PROT_WRITE) = 0
mprotect(0x774c1000, 0xffc, 0x3) = 0
[+] mprotect(0x774c1000, 0xffc, PROT_READ | PROT_WRITE) = 0
mprotect(0x774c1000, 0xffc, 0x3) = 0
[+] mprotect(0x774c1000, 0xffc, PROT_READ | PROT_WRITE) = 0
mprotect(0x774c1000, 0xffc, 0x3) = 0
[+] mprotect(0x774c1000, 0xffc, PROT_READ | PROT_WRITE) = 0
mprotect(0x774c1000, 0xffc, 0x3) = 0
[+] mprotect(0x774c1000, 0xffc, PROT_READ | PROT_WRITE) = 0
clock_gettime()
mprotect(0x774c1000, 0xffc, 0x3) = 0
[+] mprotect(0x774c1000, 0xffc, PROT_READ | PROT_WRITE) = 0
mprotect(0x774c1000, 0xffc, 0x1) = 0
[+] mprotect(0x774c1000, 0xffc, PROT_READ) = 0
[+] log mmap2 - mmap2(0x0, 0x1000, 0x3, 0x22, -1, 0)
[+] log mmap2 - mmap2(0x0, 0x1000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0)
[+] log mmap2 - return addr : 0x77559000
[+] log mmap2 - addr range  : 0x77559000 - 0x7755a000
[+] log mmap2 - mapping needed
mmap2(0x0, 0x1000, 0x3, 0x22, -1, 0) = 0x77559000
[+] mmap2_base is 0x77559000
madvise() = 0
mprotect(0x77559000, 0x1000, 0x1) = 0
[+] mprotect(0x77559000, 0x1000, PROT_READ) = 0
fstat64(1, 0x7ff3c758) = 0
[+] fstat64 write completed
gettimeofday(7ff3c780, 0) = 0
brk(0x0)
[+] brk return(0x5655a000)
brk(0x5655a000)
[+] brk return(0x5655a000)
brk(0x5655b000)
[+] brk return(0x5655b000)
brk(0x5655c000)
[+] brk return(0x5655c000)
mprotect(0x77559000, 0x1000, 0x3) = 0
[+] mprotect(0x77559000, 0x1000, PROT_READ | PROT_WRITE) = 0
mprotect(0x77559000, 0x1000, 0x1) = 0
[+] mprotect(0x77559000, 0x1000, PROT_READ) = 0
close(0) = 0
write(1,5655a020,12) = 0
close(1) = 0
hello world!
```

windows下日志：
```
[+] Enable ARM VFP
[+] Set init_kernel_get_tls
[+] load 0x56555000 - 0x56556000
[+] load 0x56556000 - 0x56558000
[+] mem_start: 0x0 mem_end: 0x3000
[+] interp is : rootfs/android_32/system/bin/linker
[+] interp_mem_size is : 0x12000
[+] interp_address is : 0x47ba000
[+] mmap_address is : 0x774bf000
[+] rel name b'__stack_chk_guard'
[+] rel name b'__libc_init'
[+] rel name b'__cxa_atexit'
[+] rel name b'printf'
[+] rel name b'__stack_chk_fail'
mprotect(0x47c9000, 0x1000, 0x1) = 0
[+] mprotect(0x47c9000, 0x1000, PROT_READ) = 0
ugetrlimit(3, 0x7ff3cda8) = 0
gettid() = 1996
settls(0x47caf24)
[+] log mmap2 - mmap2(0x0, 0x2000, 0x3, 0x22, 0, 0)
[+] log mmap2 - mmap2(0x0, 0x2000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap2 - return addr : 0x774bf000
[+] log mmap2 - addr range  : 0x774bf000 - 0x774c1000
[+] log mmap2 - mapping needed
mmap2(0x0, 0x2000, 0x3, 0x22, 0, 0) = 0x774bf000
[+] mmap2_base is 0x774bf000
madvise() = 0
[!] 0x47c2944: syscall ql_syscall_sigaltstack number = 0xba(186) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[!] 0x47beb18: syscall ql_syscall_sigaction number = 0x43(67) not implemented
[+] log mmap2 - mmap2(0x0, 0xffc, 0x3, 0x22, 0, 0)
[+] log mmap2 - mmap2(0x0, 0xffc, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0)
[+] log mmap2 - return addr : 0x774c1000
[+] log mmap2 - addr range  : 0x774c1000 - 0x774c2000
[+] log mmap2 - mapping needed
mmap2(0x0, 0xffc, 0x3, 0x22, 0, 0) = 0x774c1000
[+] mmap2_base is 0x774c1000
madvise() = 0
open(\vendor\lib\libm.so, 0x8002, 0o0) = -2
[+] open(\vendor\lib\libm.so, O_RDONLY | O_RDWR | 32768, 0o0) = -2
[!] File Not Found D:\my_project\myqiling\rootfs\android_32\vendor\lib\libm.so
open(\system\lib\libm.so, 0x8002, 0o0) = 3
[+] open(\system\lib\libm.so, O_RDONLY | O_RDWR | 32768, 0o0) = 3
[+] File Found: D:\my_project\myqiling\rootfs\android_32\system\lib\libm.so
read(3, 0x7ff3cd14, 0x34) = 52
[+] log mmap2 - mmap2(0x0, 0x1000, 0x1, 0x2, 3, 0)
[+] log mmap2 - mmap2(0x0, 0x1000, PROT_READ, MAP_PRIVATE, 3, 0)
[+] log mmap2 - return addr : 0x774c2000
[+] log mmap2 - addr range  : 0x774c2000 - 0x774c3000
[+] log mmap2 - mapping needed
[+] log mem write : 0x1000
[+] log mem mmap2  : D:\my_project\myqiling\rootfs\android_32\system\lib\libm.so
mmap2(0x0, 0x1000, 0x1, 0x2, 3, 0) = 0x774c2000
[+] mmap2_base is 0x774c2000
madvise() = 0
[+] log mmap2 - mmap2(0x0, 0x1a000, 0x0, 0x22, -1, 0)
[+] log mmap2 - mmap2(0x0, 0x1a000, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0)
[+] log mmap2 - return addr : 0x774c3000
[+] log mmap2 - addr range  : 0x774c3000 - 0x774dd000
[+] log mmap2 - mapping needed
mmap2(0x0, 0x1a000, 0x0, 0x22, -1, 0) = 0x774c3000
[+] mmap2_base is 0x774c3000
madvise() = 0
[+] log mmap2 - mmap2(0x774c3000, 0x17ee4, 0x5, 0x12, 3, 0)
[+] log mmap2 - mmap2(0x774c3000, 0x17ee4, PROT_READ | PROT_EXEC, MAP_PRIVATE | MAP_FIXED, 3, 0)
[+] log mmap2 - return addr : 0x774c3000
[+] log mmap2 - addr range  : 0x774c3000 - 0x774db000
[+] log mem write : 0x17ee4
[+] log mem mmap2  : D:\my_project\myqiling\rootfs\android_32\system\lib\libm.so
mmap2(0x774c3000, 0x17ee4, 0x5, 0x12, 3, 0) = 0x774c3000
[+] mmap2_base is 0x774c3000
madvise() = 0
[+] log mmap2 - mmap2(0x774db000, 0x106c, 0x3, 0x12, 3, 94208)
[+] log mmap2 - mmap2(0x774db000, 0x106c, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_FIXED, 3, 94208)
[+] log mmap2 - return addr : 0x774db000
[+] log mmap2 - addr range  : 0x774db000 - 0x774dd000
[+] log mem write : 0x106c
[+] log mem mmap2  : D:\my_project\myqiling\rootfs\android_32\system\lib\libm.so
mmap2(0x774db000, 0x106c, 0x3, 0x12, 3, 94208) = 0x774db000
[+] mmap2_base is 0x774db000
madvise() = 0
close(3) = 0
munmap(0x774c2000, 0x1000) = 0
open(\vendor\lib\libc.so, 0x8002, 0o0) = -2
[+] open(\vendor\lib\libc.so, O_RDONLY | O_RDWR | 32768, 0o0) = -2
[!] File Not Found D:\my_project\myqiling\rootfs\android_32\vendor\lib\libc.so
open(\system\lib\libc.so, 0x8002, 0o0) = 3
[+] open(\system\lib\libc.so, O_RDONLY | O_RDWR | 32768, 0o0) = 3
[+] File Found: D:\my_project\myqiling\rootfs\android_32\system\lib\libc.so
read(3, 0x7ff3cc4c, 0x34) = 52
[+] log mmap2 - mmap2(0x0, 0x1000, 0x1, 0x2, 3, 0)
[+] log mmap2 - mmap2(0x0, 0x1000, PROT_READ, MAP_PRIVATE, 3, 0)
[+] log mmap2 - return addr : 0x774dd000
[+] log mmap2 - addr range  : 0x774dd000 - 0x774de000
[+] log mmap2 - mapping needed
[+] log mem write : 0x1000
[+] log mem mmap2  : D:\my_project\myqiling\rootfs\android_32\system\lib\libc.so
mmap2(0x0, 0x1000, 0x1, 0x2, 3, 0) = 0x774dd000
[+] mmap2_base is 0x774dd000
madvise() = 0
[+] log mmap2 - mmap2(0x0, 0x5b000, 0x0, 0x22, -1, 0)
[+] log mmap2 - mmap2(0x0, 0x5b000, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS, -1, 0)
[+] log mmap2 - return addr : 0x774de000
[+] log mmap2 - addr range  : 0x774de000 - 0x77539000
[+] log mmap2 - mapping needed
mmap2(0x0, 0x5b000, 0x0, 0x22, -1, 0) = 0x774de000
[+] mmap2_base is 0x774de000
madvise() = 0
[+] log mmap2 - mmap2(0x774de000, 0x46ef0, 0x5, 0x12, 3, 0)
[+] log mmap2 - mmap2(0x774de000, 0x46ef0, PROT_READ | PROT_EXEC, MAP_PRIVATE | MAP_FIXED, 3, 0)
[+] log mmap2 - return addr : 0x774de000
[+] log mmap2 - addr range  : 0x774de000 - 0x77525000
[+] log mem write : 0x46ef0
[+] log mem mmap2  : D:\my_project\myqiling\rootfs\android_32\system\lib\libc.so
mmap2(0x774de000, 0x46ef0, 0x5, 0x12, 3, 0) = 0x774de000
[+] mmap2_base is 0x774de000
madvise() = 0
[+] log mmap2 - mmap2(0x77526000, 0x42e8, 0x3, 0x12, 3, 290816)
[+] log mmap2 - mmap2(0x77526000, 0x42e8, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_FIXED, 3, 290816)
[+] log mmap2 - return addr : 0x77526000
[+] log mmap2 - addr range  : 0x77526000 - 0x7752b000
[+] log mem write : 0x42e8
[+] log mem mmap2  : D:\my_project\myqiling\rootfs\android_32\system\lib\libc.so
mmap2(0x77526000, 0x42e8, 0x3, 0x12, 3, 290816) = 0x77526000
[+] mmap2_base is 0x77526000
madvise() = 0
[+] log mmap2 - mmap2(0x7752b000, 0xe000, 0x3, 0x32, -1, 0)
[+] log mmap2 - mmap2(0x7752b000, 0xe000, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_FIXED | MAP_ANONYMOUS, -1, 0)
[+] log mmap2 - return addr : 0x7752b000
[+] log mmap2 - addr range  : 0x7752b000 - 0x77539000
mmap2(0x7752b000, 0xe000, 0x3, 0x32, -1, 0) = 0x7752b000
[+] mmap2_base is 0x7752b000
madvise() = 0
close(3) = 0
munmap(0x774dd000, 0x1000) = 0
mprotect(0x77526000, 0x2000, 0x1) = 0
[+] mprotect(0x77526000, 0x2000, PROT_READ) = 0
mprotect(0x774db000, 0x1000, 0x1) = 0
[+] mprotect(0x774db000, 0x1000, PROT_READ) = 0
mprotect(0x56556000, 0x1000, 0x1) = 0
[+] mprotect(0x56556000, 0x1000, PROT_READ) = 0
open(\dev\__properties__, 0x8002, 0o0) = 3
[+] open(\dev\__properties__, O_RDONLY | O_RDWR | 32768, 0o0) = 3
[+] File Found: D:\my_project\myqiling\rootfs\android_32\dev\__properties__
fcntl64(3, 2, 1) = 0
fstat64(3, 0x7ff3cc70) = 0
[+] fstat64 write completed
close(3) = 0
[!] Emulation Error


[-] r0	:	 0x7751dbe9
[-] r1	:	 0x2e
[-] r2	:	 0x7751dbe3
[-] r3	:	 0x7751dbea
[-] r4	:	 0x7751dbe4
[-] r5	:	 0x5
[-] r6	:	 0x80
[-] r7	:	 0x0
[-] r8	:	 0x0
[-] r9	:	 0x12
[-] r10	:	 0x7751dbe9
[-] r11	:	 0x1
[-] r12	:	 0x1000000
[-] sp	:	 0x7ff3cc20
[-] lr	:	 0x7750c2d7
[-] pc	:	 0x7750c2fa
[-] cpsr	:	 0x200d01f3
[-] c1_c0_2	:	 0xf00000
[-] c13_c0_3	:	 0x47caf24
[-] fpexc	:	 0x40000000


[+] PC = 0x7750c2fa

[+] Start      End        Perm.  Path
[+] 047ba000 - 047cc000 - rwx    D:\my_project\myqiling\rootfs\android_32\system\bin\linker
[+] 56555000 - 56556000 - r-x    D:\my_project\myqiling\bin\hello_world (D:\my_project\myqiling\bin\hello_world)
[+] 56556000 - 56558000 - rw-    D:\my_project\myqiling\bin\hello_world (D:\my_project\myqiling\bin\hello_world)
[+] 56558000 - 5655a000 - rwx    [hook_mem] (D:\my_project\myqiling\bin\hello_world)
[+] 774bf000 - 774c1000 - rwx    [syscall_mmap2]
[+] 774c1000 - 774c2000 - rwx    [syscall_mmap2]
[+] 774c3000 - 774db000 - rwx    [mmap2] D:\my_project\myqiling\rootfs\android_32\system\lib\libm.so
[+] 774db000 - 774dd000 - rwx    [mmap2] D:\my_project\myqiling\rootfs\android_32\system\lib\libm.so
[+] 774de000 - 77525000 - rwx    [mmap2] D:\my_project\myqiling\rootfs\android_32\system\lib\libc.so
[+] 77525000 - 77526000 - rwx    [syscall_mmap2]
[+] 77526000 - 7752b000 - rwx    [mmap2] D:\my_project\myqiling\rootfs\android_32\system\lib\libc.so
[+] 7752b000 - 77539000 - rwx    [syscall_mmap2]
[+] 7ff0d000 - 7ff3d000 - rwx    [stack]
[+] ffff0000 - ffff1000 - rwx    [arm_tls]
[+] ['0x33', '0x69', '0xb', '0xb1', '0x30', '0x69', '0x25', '0xe0']


[+] 0x7750c2fa     33 69 0b b1 30 69 25 e0 00 2f 5e d0 06 f1 10 02 20 46 29 46 ff f7 b7 ff 06 46 00 28 55 d0 02 78 95 42 09 d3 13 d8 20 46 06 f1 14 01 2a 46 0b f0 b2 fd 00 28 18 d0 0a da b3 68 0b b1 b0 68 09 e0 ldr r3, [r6, #0x10]
cbz r3, #0x7750c302
ldr r0, [r6, #0x10]
b #0x7750c34e
cmp r7, #0
beq #0x7750c3c4
add.w r2, r6, #0x10
mov r0, r4
mov r1, r5
bl #0x7750c280
mov r6, r0
cmp r0, #0
beq #0x7750c3c4
ldrb r2, [r0]
cmp r5, r2
blo #0x7750c332
bhi #0x7750c348
mov r0, r4
add.w r1, r6, #0x14
mov r2, r5
bl #0x77517e90
cmp r0, #0
beq #0x7750c362
bge #0x7750c348
ldr r3, [r6, #8]
cbz r3, #0x7750c33a
ldr r0, [r6, #8]
b #0x7750c34e
Traceback (most recent call last):
  File "D:/my_project/myqiling/test.py", line 23, in <module>
    my_sandbox(["bin/hello_world"], "rootfs/android_32")
  File "D:/my_project/myqiling/test.py", line 20, in my_sandbox
    ql.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\qiling-1.2.dev0-py3.8.egg\qiling\core.py", line 199, in run
    self.os.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\qiling-1.2.dev0-py3.8.egg\qiling\os\linux\linux.py", line 121, in run
    self.ql.emu_start(self.ql.loader.entry_point, self.ql.loader.elf_entry, self.ql.timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\qiling-1.2.dev0-py3.8.egg\qiling\core.py", line 258, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\unicorn\unicorn.py", line 317, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)

```
对应的地址在ida中如下：
![捕获](https://user-images.githubusercontent.com/57795174/101432940-c0321880-3944-11eb-9642-01530fb6580c.PNG)
查找引用后，我发现需要先执行在执行这一段代码时直接调用了close()
![捕获2](https://user-images.githubusercontent.com/57795174/101432958-c7592680-3944-11eb-85d3-f7d414877c7c.PNG)
而在liunx下有futex进行控制使得程序可以继续运行。
这是由什么原因造成的呢？

**Comment by wtdcode** [comment]
post一下脚本和二进制文件？

**Comment by Hho-hyj** [comment]
我使用的脚本及二进制文件如下：
[https://cowtransfer.com/s/0e67d3a134a44c](url)

**Comment by wtdcode** [comment]
哦，原来是安卓。安卓的futex实现用的是linux的，写的比较烂，我正好在改这附近的版本，预计Qiling2.0能跑。见 #599

**Comment by Hho-hyj** [comment]
我在两台相同配置的电脑，相同版本的Linux下运行相同的脚本和二进制文件，一个可以正常运行通过futex()调用，另一个会出现与Windows下运行相同的情况，没有进行futex()调用。

**Comment by wtdcode** [comment]
linux的多线程模拟是公平时间片调度，有一定随机性的，不过我不确定是不是这个原因。

**Comment by Hho-hyj** [comment]
谢谢您的指导，我再看看代码。有微信吗，可以和您加个微信吗？

**Comment by wtdcode** [comment]
> 谢谢您的指导，我再看看代码。有微信吗，可以和您加个微信吗？

telegram上找你了。
