### ISSUE TITLE
qiling.exception.QlErrorFileNotFound: [!] Target binary not found   一直是这样,我已经按照文档配置了

### ISSUE THREAD

**Issue by Invincible-World** [qilingframework/qiling#603]
[INFO][qilingida:1047] Rootfs: C:\Users\yht\Downloads\rootfs\arm_android
[INFO][qilingida:1048] Custom user script: C:\Users\yht\Downloads\ql.py
[INFO][qilingida:1056] Qiling is initialized successfully.
Traceback (most recent call last):
  File "C:/Users/yht/AppData/Roaming/Python/Python39/site-packages/qiling/extensions/idaplugin/qilingida.py", line 812, in activate
    self.action_handler.ql_handle_menu_action(self.action_type)
  File "C:/Users/yht/AppData/Roaming/Python/Python39/site-packages/qiling/extensions/idaplugin/qilingida.py", line 2078, in ql_handle_menu_action
    [x.handler() for x in self.menuitems if x.action == action]
  File "C:/Users/yht/AppData/Roaming/Python/Python39/site-packages/qiling/extensions/idaplugin/qilingida.py", line 2078, in <listcomp>
    [x.handler() for x in self.menuitems if x.action == action]
  File "C:/Users/yht/AppData/Roaming/Python/Python39/site-packages/qiling/extensions/idaplugin/qilingida.py", line 1051, in ql_start
    self.qlemu.start()
  File "C:/Users/yht/AppData/Roaming/Python/Python39/site-packages/qiling/extensions/idaplugin/qilingida.py", line 909, in start
    self.ql = Qiling(argv=[self.path], rootfs=self.rootfs, output="debug", *args, **kwargs)
  File "C:\Users\yht\AppData\Roaming\Python\Python39\site-packages\qiling\core.py", line 114, in __init__
    raise QlErrorFileNotFound("[!] Target binary not found")
qiling.exception.QlErrorFileNotFound: [!] Target binary not found

**Comment by wtdcode** [comment]
文件没找到，一般是没解压。

**Comment by Invincible-World** [comment]
> 文件没找到，一般是没解压。

解压什么呢 不是按照官网pip install qiling就可以了吗

**Comment by wtdcode** [comment]
哦，你这是配IDA插件呢，怎么设置的路径？

**Comment by Invincible-World** [comment]
> 哦，你这是配IDA插件呢，怎么设置的路径？

插件启动的路径和脚本我是直接把官网例子的fs下载下载选择了

**Comment by wtdcode** [comment]
> > 哦，你这是配IDA插件呢，怎么设置的路径？
> 
> 插件启动的路径和脚本我是直接把官网例子的fs下载下载选择了

有点奇怪，你能把测试binary发上来吗？不方便的话可以发到我邮箱。

**Comment by kabeor** [comment]
@Invincible-World 需要先把文件拖进ida分析，插件是直接读取IDA内获取到的文件路径的

**Comment by Invincible-World** [comment]
> @ Invincible-World需要先把文件拖进ida分析，插件是直接读取IDA内获取到的文件路径的

我的文件就在ida内呀

**Comment by kabeor** [comment]
> > @ Invincible-World需要先把文件拖进ida分析，插件是直接读取IDA内获取到的文件路径的
> 
> 我的文件就在ida内呀

有没有加QQ或者tg群组，方便我帮你解决

**Comment by Invincible-World** [comment]
> > > @ Invincible-World需要先把文件拖进ida分析，插件是直接读取IDA内获取到的文件路径的
> > 
> > 
> > 我的文件就在ida内呀
> 
> 有没有加QQ或者tg群组，方便我帮你解决
我的qq:1967064046,麻烦您了

**Comment by kabeor** [comment]
Solved

**Comment by kotori2** [comment]
> @Invincible-World 需要先把文件拖进ida分析，插件是直接读取IDA内获取到的文件路径的

感觉他并不是这么可靠……尤其是当你在不同的系统上使用IDA的时候。
One way to fix: `set_root_filename("path/to/your/binary")`
