### ISSUE TITLE
QlErrorSyscallError getattrlist?

### ISSUE THREAD

**Issue by asgmeonerandom** [qilingframework/qiling#634]
***Describe the bug**

```
[=] [syscall.py:232]	getattrlist(0x7ffd099fe7b0, 0x50007f8b8, 0x7ffd099fe350, 0x41c, 0x1)
qiling.exception.QlErrorSyscallError: Error File Not Exist
[=] [posix.py:182]	[!] Syscall ERROR: ql_syscall_getattrlist DEBUG: Error File Not Exist
```

**Sample Code**
```python
import sys
sys.path.append("..")
from qiling import *

if __name__ == "__main__":
    ql = Qiling(["rootfs/x8664_macos/bin/x8664_hello"], "rootfs/x8664_macos", output = "debug")
    ql.run()
```

**Expected behavior**
the program should not crash

**Additional context**
How to fix this error? [It seems it's exist](https://github.com/qilingframework/qiling/blob/dev/qiling/os/macos/map_syscall.py#L201) then why it's crashing?

**Comment by xwings** [comment]
I dont think we every finish implementing 32bit macos, that is the reason why it doesnt work. Due to one major reason. Mac dont have 32bit platform for a long time.

But, if you want. you can always work on it :)

**Comment by asgmeonerandom** [comment]
> I dont think we every finish implementing 32bit macos
what do you mean ? The program is 64 bit macos


> , that is the reason why it doesnt work. Due to one major reason. Mac dont have 32bit platform for a long time.
> 
> But, if you want. you can always work on it :)

**Comment by xwings** [comment]
Sorry, I read it wrongly. But 64bit helloworld should work. Check travis-CI with the latest build.

https://travis-ci.com/github/qilingframework/qiling/builds/211482275

**Comment by asgmeonerandom** [comment]
> Sorry, I read it wrongly. But 64bit helloworld should work. Check travis-CI with the latest build.
> 
> https://travis-ci.com/github/qilingframework/qiling/builds/211482275

I can't find how to download from travis-CI, but this is the error I'm getting running the program and I am using latest version on dev

```

[+] [syscall.py:394]	real_path: rootfs/x8664_macos/System/iOSSupport/System/Library/Frameworks/ContactsUI.framework/ContactsUI
[=] [syscall.py:433]	stat64(/System/iOSSupport/System/Library/Frameworks/ContactsUI.framework/ContactsUI, 0x7ffd099fe180) = -1
[+] [syscall.py:438]	[!] stat64 read/write fail
[+] [syscall.py:394]	real_path: rootfs/x8664_macos/System/Library/Frameworks/ContactsUI.framework/ContactsUI
[=] [syscall.py:433]	stat64(/System/Library/Frameworks/ContactsUI.framework/ContactsUI, 0x7ffd099fe510) = -1
[+] [syscall.py:438]	[!] stat64 read/write fail
[+] [syscall.py:394]	real_path: rootfs/x8664_macos/
[=] [syscall.py:433]	stat64(/, 0x7ffd099fc4e0) = 0
[+] [syscall.py:436]	[+] stat64 write completed
[=] [syscall.py:232] getattrlist(0x7ffd099fe290, 0x50007f8b8, 0x7ffd099fde30, 0x41c, 0x1)
[+] [syscall.py:236] getattrlist(path: 0x7ffd099fe290, alist: 0x50007f8b8, attributeBuffer: 0x7ffd099fde30, bufferSize: 0x41c, options: 0x1)
[+] [syscall.py:249] [+] bitmapcount: 0x5, reserved: 0x0, commonattr: 0x2b, volattr: 0x0, dirattr: 0x0, fileattr: 0x0, forkattr: 0x0

[+] [syscall.py:252] [+] path str: /System

[+] [syscall.py:258] Error File Not Exist: /System
[x] [posix.py:181] 
Traceback (most recent call last):
  File "/Users/usr/Desktop/qiling/qiling/os/posix/posix.py", line 171, in load_syscall
    ret = self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "/Users/usr/Desktop/qiling/qiling/os/macos/syscall.py", line 259, in ql_syscall_getattrlist
    raise QlErrorSyscallError("Error File Not Exist")
qiling.exception.QlErrorSyscallError: Error File Not Exist
[=] [posix.py:182] [!] Syscall ERROR: ql_syscall_getattrlist DEBUG: Error File Not Exist
Traceback (most recent call last):
  File "/Users/usr/Desktop/r6_string_print_x8664_mac_disasm.py", line 77, in <module>
    ql.run()
  File "/Users/usr/Desktop/qiling/qiling/core.py", line 769, in run
    self.os.run()
  File "/Users/usr/Desktop/qiling/qiling/os/macos/macos.py", line 204, in run
    self.ql.emu_start(self.ql.loader.entry_point, self.exit_point, self.ql.timeout, self.ql.count)
  File "/Users/usr/Desktop/qiling/qiling/core.py", line 1001, in emu_start
    raise self._internal_exception
  File "/Users/usr/Desktop/qiling/qiling/utils.py", line 155, in wrapper
    return func(*args, **kw)
  File "/Users/usr/Desktop/qiling/qiling/core_hooks.py", line 133, in _hook_insn_cb
    ret = h.call(ql, *args[ : -1])
  File "/Users/usr/Desktop/qiling/qiling/core_hooks.py", line 35, in call
    return self.callback(ql, *args)
  File "/Users/usr/Desktop/qiling/qiling/os/macos/macos.py", line 162, in hook_syscall
    return self.load_syscall()
  File "/Users/usr/Desktop/qiling/qiling/os/posix/posix.py", line 183, in load_syscall
    raise e
  File "/Users/usr/Desktop/qiling/qiling/os/posix/posix.py", line 171, in load_syscall
    ret = self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "/Users/usr/Desktop/qiling/qiling/os/macos/syscall.py", line 259, in ql_syscall_getattrlist
    raise QlErrorSyscallError("Error File Not Exist")
qiling.exception.QlErrorSyscallError: Error File Not Exist
```

**Comment by xwings** [comment]
Check the link, there is a execution log. Which it able to run.

**Comment by asgmeonerandom** [comment]
After running: https://github.com/qilingframework/qiling/blob/master/examples/scripts/dylibcollector.sh it fixes the error above, but now I'm getting a different error ..
