### ISSUE TITLE
unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)

### ISSUE THREAD

**Issue by baptistapedro** [qilingframework/qiling#637]
**Script**
```python

def my_strncpy(ql):
    dst = ql.os.function_arg[0];
    src = ql.os.funtion_arg[1]
    print("src(%s)" % ql.mem.string(src))
​
​
if __name__ == "__main__":
    ql = Qiling(
        ["bin.mbn"],
        "examples/rootfs/arm_linux",
        output = "debug"
    )
​
    ql.set_api('strncpy', my_strncpy)
    ql.run()
```

**Error**
```
$ python3 file1.py 
[+] [arm.py:82]	[+] Enable ARM VFP
[+] [utils.py:24]	[+] Set init_kernel_get_tls
[+] [elf.py:243]	[+] load 0x56555000 - 0x565f2000
[+] [elf.py:243]	[+] load 0x565f2000 - 0x565f3000
[+] [elf.py:243]	[+] load 0x565f3000 - 0x567ad000
[+] [elf.py:267]	[+] mem_start: 0x0 mem_end: 0x258000
[+] [elf.py:312]	[+] mmap_address is : 0x774bf000
[x] [os.py:95]	
​
[x] [os.py:101]	r0	:	 0x0
[x] [os.py:101]	r1	:	 0x0
[x] [os.py:101]	r2	:	 0x0
[x] [os.py:101]	r3	:	 0x0
[x] [os.py:101]	r4	:	 0x0
[x] [os.py:101]	r5	:	 0x0
[x] [os.py:101]	r6	:	 0x0
[x] [os.py:101]	r7	:	 0x0
[x] [os.py:101]	r8	:	 0x0
[x] [os.py:101]	r9	:	 0x0
[x] [os.py:101]	r10	:	 0x0
[x] [os.py:101]	r11	:	 0x0
[x] [os.py:101]	r12	:	 0x0
[x] [os.py:101]	sp	:	 0x7ff3cf34
[x] [os.py:101]	lr	:	 0x5678a008
[x] [os.py:101]	pc	:	 0x0
[x] [os.py:101]	cpsr	:	 0x400001d3
[x] [os.py:101]	c1_c0_2	:	 0xf00000
[x] [os.py:101]	c13_c0_3	:	 0x0
[x] [os.py:101]	fpexc	:	 0x40000000
[x] [os.py:103]	
​
[x] [os.py:104]	PC = 0x0
[=] [os.py:110]	
​
[=] [memory.py:133]	[+] Start      End        Perm.  Path
[=] [memory.py:139]	[+] 56555000 - 565f2000 - r-x    /home/nasa/Desktop/qiling/bin.mbn (/home/nasa/Desktop/qiling/bin.mbn)
[=] [memory.py:139]	[+] 565f2000 - 565f3000 - r--    /home/nasa/Desktop/qiling/bin.mbn (/home/nasa/Desktop/qiling/bin.mbn)
[=] [memory.py:139]	[+] 565f3000 - 567ad000 - rw-    /home/nasa/Desktop/qiling/bin.mbn (/home/nasa/Desktop/qiling/bin.mbn)
[=] [memory.py:139]	[+] 567ad000 - 567af000 - rwx    [hook_mem]
[=] [memory.py:139]	[+] 7ff0d000 - 7ff3d000 - rwx    [stack]
[=] [memory.py:139]	[+] ffff0000 - ffff1000 - rwx    [arm_tls]
[x] [os.py:120]	Error: PC(0x0) Unreachable
Traceback (most recent call last):
  File "file1.py", line 18, in <module>
    ql.run()
  File "/home/nasa/Desktop/qiling/qiling/core.py", line 765, in run
    self.os.run()
  File "/home/nasa/Desktop/qiling/qiling/os/linux/linux.py", line 145, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/nasa/Desktop/qiling/qiling/core.py", line 994, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/home/nasa/.local/lib/python3.8/site-packages/unicorn/unicorn.py", line 318, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory fetch (UC_ERR_FETCH_UNMAPPED)
```

**Comment by xwings** [comment]
I guess we solved this during telegram session :)
