### ISSUE TITLE
AttributeError: ql_file object has no attribute fcntl

### ISSUE THREAD

**Issue by cq674350529** [qilingframework/qiling#642]
**Describe the bug**
When trying to run `xz -d <file>`, an error occurred.
```shell
Traceback (most recent call last):
  File "qiling_demo.py", line 780, in <module>
    qiling_test()
  File "qiling_demo.py", line 771, in qiling_test
    ql.run()
  File "/home/cq/workspace/git/qiling/qiling/core.py", line 765, in run
    self.os.run()
  File "/home/cq/workspace/git/qiling/qiling/os/linux/linux.py", line 149, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/cq/workspace/git/qiling/qiling/core.py", line 957, in emu_start
    raise self._internal_exception
  File "/home/cq/workspace/git/qiling/qiling/utils.py", line 157, in wrapper
    return func(*args, **kw)
  File "/home/cq/workspace/git/qiling/qiling/core_hooks.py", line 119, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "/home/cq/workspace/git/qiling/qiling/core_hooks.py", line 35, in call
    return self.callback(ql, *args)
  File "/home/cq/workspace/git/qiling/qiling/os/linux/linux.py", line 71, in hook_syscall
    return self.load_syscall(intno)
  File "/home/cq/workspace/git/qiling/qiling/os/posix/posix.py", line 183, in load_syscall
    raise e
  File "/home/cq/workspace/git/qiling/qiling/os/posix/posix.py", line 171, in load_syscall
    ret = self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "/home/cq/workspace/git/qiling/qiling/os/posix/syscall/fcntl.py", line 121, in ql_syscall_fcntl64
    ql.os.fd[fcntl_fd].fcntl(fcntl_cmd, fcntl_arg)
AttributeError: 'ql_file' object has no attribute 'fcntl'
```

**Sample Code**
```python
rootfs_path = "/home/cq/Desktop/qiling_tmp"
bin_path = "xz"
tar_path = "hello.txt.xz"

ql = Qiling([os.path.join(rootfs_path, bin_path), "-d", tar_path], rootfs_path, console=False, output='debug', verbose=5)
ql.run()
```

After investigating `fcntl.py`, just remove the `ql.os.fd[fcntl_fd].fcntl(fcntl_cmd, fcntl_arg)` and it works. I'm not familiar with `fcntl`, so I don't know if it has any side effect.
> PS: Sometimes, the decompressed file has `000` permission.
```python
def ql_syscall_fcntl(ql, fcntl_fd, fcntl_cmd, *args, **kw):
    F_SETFD = 2
    F_GETFL = 3
    F_SETFL = 4
    regreturn = 0
    if fcntl_cmd == F_SETFD:
        regreturn = 0
    elif fcntl_cmd == F_GETFL:
        regreturn = 2
    elif fcntl_cmd == F_SETFL:
        regreturn = 0

    logging.info("fcntl(%d, %d) = %d" % (fcntl_fd, fcntl_cmd, regreturn))
    return regreturn


def ql_syscall_fcntl64(ql, fcntl_fd, fcntl_cmd, fcntl_arg, *args, **kw):

    F_GETFD = 1
    F_SETFD = 2
    F_GETFL = 3
    F_SETFL = 4

    if fcntl_cmd == F_GETFL:
        regreturn = 2
    elif fcntl_cmd == F_SETFL:
        # ql.os.fd[fcntl_fd].fcntl(fcntl_cmd, fcntl_arg)    <=== remove this
        regreturn = 0
    elif fcntl_cmd == F_GETFD:
        regreturn = 2
    elif fcntl_cmd == F_SETFD:
        regreturn = 0
    else:
        regreturn = 0

    logging.info("fcntl64(%d, %d, %d) = %d" % (fcntl_fd, fcntl_cmd, fcntl_arg, regreturn))
    return regreturn
```

The related files are attached.
[qiling_tmp.zip](https://github.com/qilingframework/qiling/files/5819444/qiling_tmp.zip)

**Comment by xwings** [comment]
Send in the patch and see if travis fail ?

**Comment by cq674350529** [comment]
Since `fcntl()` can be used to set  the file status flags, I add a `fcntl()` method for `ql_file`, similar to `ql_socket`.

https://github.com/qilingframework/qiling/blob/5ddb8d68cc9ea518902d4c9fccf9d49a57c186b3/qiling/os/posix/filestruct.py#L54-L60
