### ISSUE TITLE
Syscall posix/clone is broken: ql.os.thread_management is None

### ISSUE THREAD

**Issue by PeterStolz** [qilingframework/qiling#643]
**Describe the bug**
Running a program that uses the posix/clone syscall crashes with the following Exception. Tested with the example usage program from the clone manpage (see attachments) on x64 and a httpd server on MIPS32.

```
[x] [posix.py:181]	
Traceback (most recent call last):
  File "/home/peter/Envs/qiling/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 171, in load_syscall
    ret = self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "/home/peter/Envs/qiling/lib/python3.8/site-packages/qiling/os/posix/syscall/sched.py", line 54, in ql_syscall_clone
    f_th = ql.os.thread_management.cur_thread
AttributeError: 'NoneType' object has no attribute 'cur_thread'
[=] [posix.py:182]	[!] Syscall ERROR: ql_syscall_clone DEBUG: 'NoneType' object has no attribute 'cur_thread'
Traceback (most recent call last):
  File "tendaac1518_httpd.py", line 109, in <module>
    my_sandbox([rootfs + "/usr/bin/httpd"], rootfs)
  File "tendaac1518_httpd.py", line 105, in my_sandbox
    ql.run()
  File "/home/peter/Envs/qiling/lib/python3.8/site-packages/qiling/core.py", line 765, in run
    self.os.run()
  File "/home/peter/Envs/qiling/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 149, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/peter/Envs/qiling/lib/python3.8/site-packages/qiling/core.py", line 957, in emu_start
    raise self._internal_exception
  File "/home/peter/Envs/qiling/lib/python3.8/site-packages/qiling/utils.py", line 157, in wrapper
    return func(*args, **kw)
  File "/home/peter/Envs/qiling/lib/python3.8/site-packages/qiling/core_hooks.py", line 119, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "/home/peter/Envs/qiling/lib/python3.8/site-packages/qiling/core_hooks.py", line 35, in call
    return self.callback(ql, *args)
  File "/home/peter/Envs/qiling/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 71, in hook_syscall
    return self.load_syscall(intno)
  File "/home/peter/Envs/qiling/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 183, in load_syscall
    raise e
  File "/home/peter/Envs/qiling/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 171, in load_syscall
    ret = self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "/home/peter/Envs/qiling/lib/python3.8/site-packages/qiling/os/posix/syscall/sched.py", line 54, in ql_syscall_clone
    f_th = ql.os.thread_management.cur_thread	
AttributeError: 'NoneType' object has no attribute 'cur_thread'
```

**Sample Code**
```python
ql = Qiling(["a.out", "test"], "/", output = "dump")
ql.run()
```
[Binary used and source code](https://github.com/qilingframework/qiling/files/5824290/programs.zip)

**Expected behavior**
The variable ql.os.thread_management should be set accordingly. It is set here:
 >qiling/os/linux/thread.py:247:            self.ql.os.thread_management.cur_thread = self
 >qiling/os/linux/linux.py:102:                    self.ql.os.thread_management = thread_management

but apparantly these lines are not hit, or set the value to None.

**Comment by xwings** [comment]
yup. 

as of now is broken as mention in https://github.com/qilingframework/qiling/blob/master/ChangeLog

we are writing a new one based on a more proper method.

**Comment by xwings** [comment]
should be fixed. please open a new "issue" if you face the same problem
