### ISSUE TITLE
Ubuntu1804下的所有windows的crame例子都无法运行

### ISSUE THREAD

**Issue by 23R3F** [qilingframework/qiling#656]
Ubuntu1804下的所有windows的crame例子都无法运行，报错如下

-------------------------------------------------------------------------------
qiling/examples$ python3 crackme_x86_windows.py 
Traceback (most recent call last):
  File "crackme_x86_windows.py", line 75, in <module>
    solve()
  File "crackme_x86_windows.py", line 55, in solve
    base = get_count(prefix + flag)
  File "crackme_x86_windows.py", line 39, in get_count
    ql = Qiling(["rootfs/x86_windows/bin/crackme.exe"], "rootfs/x86_windows", output="off")
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/core.py", line 211, in __init__
    self.loader.run()
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/loader/pe.py", line 396, in run
    self.ql.os.setupComponents()
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/windows/windows.py", line 63, in setupComponents
    self.registry_manager = RegistryManager(self.ql)
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/windows/registry.py", line 45, in __init__
    raise QlErrorFileNotFound(f"Error: Registry files not found in '{self.hive}'!")
qiling.exception.QlErrorFileNotFound: Error: Registry files not found in 'rootfs/x86_windows/Windows/registry'!

-------------------------------------------------------------------------------
~/qiling/examples$ python3 crackme_x86_windows_auto.py 
Traceback (most recent call last):
  File "crackme_x86_windows_auto.py", line 60, in <module>
    our_sandbox(["rootfs/x86_windows/bin/Easy_CrackMe.exe"], "rootfs/x86_windows")
  File "crackme_x86_windows_auto.py", line 51, in our_sandbox
    ql = Qiling(path, rootfs)
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/core.py", line 211, in __init__
    self.loader.run()
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/loader/pe.py", line 396, in run
    self.ql.os.setupComponents()
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/windows/windows.py", line 63, in setupComponents
    self.registry_manager = RegistryManager(self.ql)
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/windows/registry.py", line 45, in __init__
    raise QlErrorFileNotFound(f"Error: Registry files not found in '{self.hive}'!")
qiling.exception.QlErrorFileNotFound: Error: Registry files not found in 'rootfs/x86_windows/Windows/registry'!

-------------------------------------------------------------------------------
~/qiling/examples$ python3 crackme_x86_windows_unpatch.py 
Traceback (most recent call last):
  File "crackme_x86_windows_unpatch.py", line 33, in <module>
    our_sandbox(["rootfs/x86_windows/bin/Easy_CrackMe.exe"], "rootfs/x86_windows")
  File "crackme_x86_windows_unpatch.py", line 26, in our_sandbox
    ql = Qiling(path, rootfs)
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/core.py", line 211, in __init__
    self.loader.run()
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/loader/pe.py", line 396, in run
    self.ql.os.setupComponents()
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/windows/windows.py", line 63, in setupComponents
    self.registry_manager = RegistryManager(self.ql)
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/windows/registry.py", line 45, in __init__
    raise QlErrorFileNotFound(f"Error: Registry files not found in '{self.hive}'!")
qiling.exception.QlErrorFileNotFound: Error: Registry files not found in 'rootfs/x86_windows/Windows/registry'!

-------------------------------------------------------------------------------
~/qiling/examples$ python3 crackme_x86_windows_setcallback.py 
Traceback (most recent call last):
  File "crackme_x86_windows_setcallback.py", line 39, in <module>
    my_sandbox(["rootfs/x86_windows/bin/Easy_CrackMe.exe"], "rootfs/x86_windows")
  File "crackme_x86_windows_setcallback.py", line 28, in my_sandbox
    ql = Qiling(path, rootfs)
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/core.py", line 211, in __init__
    self.loader.run()
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/loader/pe.py", line 396, in run
    self.ql.os.setupComponents()
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/windows/windows.py", line 63, in setupComponents
    self.registry_manager = RegistryManager(self.ql)
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/windows/registry.py", line 45, in __init__
    raise QlErrorFileNotFound(f"Error: Registry files not found in '{self.hive}'!")
qiling.exception.QlErrorFileNotFound: Error: Registry files not found in 'rootfs/x86_windows/Windows/registry'!

我寻思GitHub项目上压根也没有rootfs/x86_windows/Windows/registry这个文件啊，是不是少安装了啥东西？？

**Comment by cq674350529** [comment]
Copy from qiling doc, please refer to https://docs.qiling.io/en/latest/install/#important-note-on-windows-dlls-and-registry

> Due to distribution restriction, Qiling Framework will not bundle Microsoft Windows DLL files and registry. Please copy respective DLLs and registry from Microsoft Windows System. For Windows 10 usually found in C:\Windows\system32 (64bit dll) and C:\Windows\SysWOW64 (32bits dll) and place them in $rootfs/dlls
We also included a dlls "collector" script, copy into Windows and it will start to collect dlls and registrty

**Comment by 23R3F** [comment]
@cq674350529  get it ，thx
