### ISSUE TITLE
socket_type = socket_type_mapping(socket_type, ql.arch) issue

### ISSUE THREAD

**Issue by xwings** [qilingframework/qiling#68]
@ucgJhe looks like we got arm screwd, can u take a look

`
[!] SYSCALL ERROR:  ql_syscall_socket
Traceback (most recent call last):
  File "../qiling/os/linux/arm.py", line 62, in hook_syscall
    LINUX_SYSCALL_FUNC(ql, param0, param1, param2, param3, param4, param5)
  File "../qiling/os/posix/syscall.py", line 1249, in ql_syscall_socket
    socket_type = socket_type_mapping(socket_type, ql.arch)
  File "../qiling/os/posix/constant.py", line 116, in socket_type_mapping
    }.get(arch)(t)
TypeError: 'NoneType' object is not callable
`

**Comment by ucgJhe** [comment]
missing mapping function for arm should be fixed by #70
