### ISSUE TITLE
64bit host emulate 32bit exception

### ISSUE THREAD

**Issue by fr0zenrain** [qilingframework/qiling#71]
finally i installed ok now. when i emulate a mips elf image, it seems not ok.
the reason may be my system is 64bit, and target is 32bit. but stat.st_ino is not a 32bit value, it's overflow.

[+] load 0x400000 - 0x405c60
[+] load 0x415fc8 - 0x41615f
[+] mem_start: 0x400000 mem_end: 0x417000
[+] interp is : Downloads/rootfs/lib/ld-uClibc.so.0
[+] interp_mem_size is : 18000
[+] interp_base is : 0x47ba000
[+] mmap_start is : 0x7fbef000
[+] Currently running pid is: 76384; tid is: 77384 
[!] 0x47bdd24: syscall number = 0x10ca(4298) not implement
[+] log mmap - mmap(0x0, 4096, 0x3, 0x802, -1, 0)
[+] log mmap - return addr : 0x7fbef000
[+] log mmap - addr range  : 0x7fbef000 - 0x7fbf0000
[+] log mmap - mapping needed
[+] mmap_base is 0x7fbef000
stat(/etc/ld.so.cache, 0x7ff3cad8) = -1
[!] stat() read/write fail
open(/lib/libubox.so, 0x0, 0x0) = 3
[+] File Found: /lib/libubox.so
[!] SYSCALL ERROR:  ql_syscall_fstat
[+] Currently running pid is: 76384; tid is: 77384 
Traceback (most recent call last):
  File "PycharmProjects/dht/dht.py", line 12, in <module>
    my_sandbox(["Downloads/https/rootfs/mtd"], "/Users/fr0zenrain/Downloads/https/rootfs")
  File "PycharmProjects/dht/dht.py", line 8, in my_sandbox
    ql.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qiling-0.9-py3.7.egg/qiling/core.py", line 210, in run
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qiling-0.9-py3.7.egg/qiling/os/linux/mips32el.py", line 259, in runner
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qiling-0.9-py3.7.egg/qiling/core.py", line 23, in wrapper
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qiling-0.9-py3.7.egg/qiling/core.py", line 280, in _callback
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/qiling-0.9-py3.7.egg/qiling/os/linux/mips32el.py", line 39, in hook_syscall
qiling.exception.QlErrorExecutionStop: [!] got interrupt 0x14 ???

fstat_buf += ql.pack32(fstat_info.st_ino)

so can qiling run as 32bit platform? thanks!

**Comment by xwings** [comment]
yes. we will emulate 32bits mips. 

maybe you can check the netgear example

**Comment by fr0zenrain** [comment]
i think may be use 32bit python will resolve this issue.

**Comment by xwings** [comment]
Nope. we are all using 64bit. the error code seems to be mips issue.

can you pull the latest code and try ?

**Comment by fr0zenrain** [comment]
it's also not ok. i think it's hard to cheat the binary with real file info.in 64bit host some field is 64bit, i can be set to fstat32 struct.

**Comment by xwings** [comment]
all the test we run for mips is in 32bits, on a 64bit system. unless you got the wrong .so maybe ? can you post file info of the .so ?

**Comment by fr0zenrain** [comment]
https://drive.google.com/file/d/1dYbm7sk4K3egG41J9pD4YwtVoZ0Rsnw0/view?usp=sharing

**Comment by xwings** [comment]
hi,

1. i mean run file command againt all the .so 
2. turn on disasm mode and see why it stops

**Comment by fr0zenrain** [comment]
the binary is not shared library, it's an executable file, it's from my mips router. i think it can't be fix, it will auto fix with python32 environment.

**Comment by xwings** [comment]
Sorry,

I guess i dont understand. I been running mips32el in X86_64bit system.
