### ISSUE TITLE
[Errno 32] Broken pipe when emulating Tenda AC15

### ISSUE THREAD

**Issue by andreia-oca** [qilingframework/qiling#726]
***Describe the bug**
I am trying to emulate Tenda AC15 15.03 firmware and I receive `Broken pipe` error when I am accessing `127.0.0.1:8080` from the browser.
Testing with `curl 127.0.0.1:8080` works just fine. 

***Detailed issue**
I have downloaded the Tenda AC15 15.03 firmware from [here](https://down.tenda.com.cn/uploadfile/AC15/US_AC15V1.0BR_V15.03.05.19_multi_TD01.zip).

When I am using `binwalk` to decompress the firmware, some of the symbolic links are broken and I am restoring them manually. So, I ruled out the problem of missing files.

I am using the following script to emulate Tenda:
```
import os, socket, sys, threading
from qiling import *

sys.path.append("..")

def nvram_listener():
    server_address = 'rootfs/var/cfm_socket'
    data = ""
    
    try:  
        os.unlink(server_address)  
    except OSError:  
        if os.path.exists(server_address):  
            raise  

    # Create UDS socket  
    sock = socket.socket(socket.AF_UNIX,socket.SOCK_STREAM)  
    sock.bind(server_address)  
    sock.listen(1)  
  
    while True:  
        connection, client_address = sock.accept()  
        try:  
            while True:  
                data += str(connection.recv(1024))
        
                if "lan.webiplansslen" in data:  
                    connection.send('192.168.170.169'.encode())  
                else: 
                    break  
                data = ""
        finally:  
                connection.close() 

def patcher(ql):
    br0_addr = ql.mem.search("br0".encode() + b'\x00')
    for addr in br0_addr:
        ql.mem.write(addr, b'lo\x00')


def my_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, output="debug", verbose=5)
    ql.add_fs_mapper("/dev/urandom","/dev/urandom")
    ql.hook_address(patcher, ql.loader.elf_entry)
    ql.run()

if __name__ == "__main__":
    nvram_listener_thread =  threading.Thread(target=nvram_listener, daemon=True)
    nvram_listener_thread.start()
    my_sandbox(["rootfs/bin/httpd"], "rootfs")
```

If I am sending HTTP queries over the command line with `curl 127.0.0.1:8080`, everything works fine.

When I am trying to access `127.0.0.1:8080` in a browser, it fails with the following error:
```
[=]	<class 'BrokenPipeError'>
[x]	
Traceback (most recent call last):
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 191, in load_syscall
    ret = self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/os/posix/syscall/socket.py", line 268, in ql_syscall_send
    regreturn = ql.os.fd[send_sockfd].send(bytes(tmp_buf), send_flags)
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/os/posix/filestruct.py", line 103, in send
    return self.__socket.send(send_buf, send_flags)
BrokenPipeError: [Errno 32] Broken pipe
[=]	Syscall ERROR: ql_syscall_send DEBUG: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "tenda_ac15_httpd.py", line 62, in <module>
    my_sandbox(["rootfs/bin/httpd"], "rootfs")
  File "tenda_ac15_httpd.py", line 57, in my_sandbox
    ql.run()
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/core.py", line 756, in run
    self.os.run()
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 118, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/core.py", line 900, in emu_start
    raise self._internal_exception
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/utils.py", line 156, in wrapper
    return func(*args, **kw)
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/core_hooks.py", line 118, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/core_hooks.py", line 34, in call
    return self.callback(ql, *args)
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 72, in hook_syscall
    return self.load_syscall()
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 206, in load_syscall
    raise e
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 191, in load_syscall
    ret = self.syscall_map(self.ql, self.get_func_arg()[0], self.get_func_arg()[1], self.get_func_arg()[2], self.get_func_arg()[3], self.get_func_arg()[4], self.get_func_arg()[5])
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/os/posix/syscall/socket.py", line 268, in ql_syscall_send
    regreturn = ql.os.fd[send_sockfd].send(bytes(tmp_buf), send_flags)
  File "/home/andreia/.local/lib/python3.8/site-packages/qiling/os/posix/filestruct.py", line 103, in send
    return self.__socket.send(send_buf, send_flags)
BrokenPipeError: [Errno 32] Broken pipe

``` 

I found out you had a similar issue #89 with Netgear Emulation. I've tried to use the workaround proposed there i.e added `my_syscall_write` to the script:

```
def my_syscall_write(ql, write_fd, write_buf, write_count, *rest):
    if write_fd is 2 and ql.file_des[2].__class__.__name__ == 'ql_pipe':
        ql_definesyscall_return(ql, -1)
    else:
        syscall.ql_syscall_write(ql, write_fd, write_buf, write_count, *rest)
```

With the workaround, the script triggers the following error:

```
[+]	bytearray(b'init_core_dump 1816: rlim_cur = 0, rlim_max = -1\ninit_core_dump 1825: open core dump success\ninit_core_dump 1834: rlim_cur = 5242880, rlim_max = 5242880\n\n\nYes:\n\n      ****** WeLoveLinux****** \n\n Welcome to ...\nConnect to server failed.\nconnect cfm failed!')
init_core_dump 1816: rlim_cur = 0, rlim_max = -1
init_core_dump 1825: open core dump success
init_core_dump 1834: rlim_cur = 5242880, rlim_max = 5242880


Yes:

      ****** WeLoveLinux****** 

 Welcome to ...
Connect to server failed.
connect cfm failed![+]	write() = 0xff
```
I am working on the `dev` branch.

I am stuck at this point. Can you give some guidelines on how to fix the errors and display the html pages within the browser?

**Comment by andreia-oca** [comment]
The error is on my side. I did not install the proper qiling version with `pip3`. I have updated with the latest dev version and everything works fine:
```
pip3 install --user https://github.com/qilingframework/qiling/archive/dev.zip
```
Now, everything works just fine. Sorry for creating this extra issue.
