### ISSUE TITLE
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)

### ISSUE THREAD

**Issue by PDX4N6** [qilingframework/qiling#736]
Same error after running 2 samples (windows x86 binaries):

Traceback (most recent call last):
  File "/usr/local/bin//qltool", line 300, in <module>
    ql.run(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/qiling/core.py", line 756, in run
    self.os.run()
  File "/usr/local/lib/python3.9/site-packages/qiling/os/windows/windows.py", line 149, in run
    self.ql.emu_start(self.ql.loader.entry_point, self.exit_point, self.ql.timeout, self.ql.count)
  File "/usr/local/lib/python3.9/site-packages/qiling/core.py", line 897, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/usr/local/lib/python3.9/site-packages/unicorn/unicorn.py", line 318, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)

**Comment by wtdcode** [comment]
which sample did you run?

**Comment by PDX4N6** [comment]
samples I working (malware)

**Comment by PDX4N6** [comment]
QBOT

**Comment by xwings** [comment]
https://docs.qiling.io/en/latest/faq/#uc_err_fetch_unmapped-uc_err_write_unmapped-and-related-issues

**Comment by PDX4N6** [comment]
thank you for the link I will troubleshoot it, you can close this out.

cheers

**Comment by KA2010** [comment]
Could you please share how you solve this issue?
I have same one
