### ISSUE TITLE
Getting error on running qltool example 'UC_X86_REG_FS_BASE' is not defined

### ISSUE THREAD

**Issue by majodu** [qilingframework/qiling#761]
***Describe the bug**
After installation, getting error when trying to run qltool example.

**Sample Code**
```
 ./qltool run -f examples/rootfs/mips32el_linux/bin/mips32el_hello --rootfs examples/rootfs/mips32el_linux
```

**Additional context**
Ubuntu 20.04.2.0
Traceback (most recent call last):
  File "./qltool", line 240, in <module>
    ql = Qiling(argv=[options.filename] + options.args, rootfs=options.rootfs, profile=options.profile,
  File "/home/r66/projects/WR940N/qiling/qiling/core.py", line 220, in __init__
    self._os = os_setup(self.archtype, self.ostype, self)
  File "/home/r66/projects/WR940N/qiling/qiling/utils.py", line 467, in os_setup
    return ql_get_module_function(f"qiling.os.{ostype_str.lower()}.{ostype_str.lower()}", function_name)(ql)
  File "/home/r66/projects/WR940N/qiling/qiling/utils.py", line 235, in ql_get_module_function
    imp_module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/r66/projects/WR940N/qiling/qiling/os/linux/linux.py", line 9, in <module>
    from qiling.arch.x86_const import UC_X86_INS_SYSCALL
  File "/home/r66/projects/WR940N/qiling/qiling/arch/x86_const.py", line 110, in <module>
    "fsbase" : UC_X86_REG_FS_BASE,
NameError: name 'UC_X86_REG_FS_BASE' is not defined

**Comment by majodu** [comment]
Updated unicorn and it worked
