### ISSUE TITLE
ql_syscall_mmap2 DEBUG: Memory Mapped

### ISSUE THREAD

**Issue by kr1tzy** [qilingframework/qiling#763]
Anyone run into anything similar to this? I've checked the arguments to mmap2, the permissions, and the memory size. 

**Logged output**
[q.log](https://github.com/qilingframework/qiling/files/6277961/q.log)

**The exception**
```
Traceback (most recent call last):
  File "run.py", line 334, in <module>
    my_sandbox(
  File "run.py", line 330, in my_sandbox
    ql.run()
  File "/home/user/.pyenv/versions/QILING_NEW/lib/python3.8/site-packages/qiling/core.py", line 754, in run
    self.os.run()
  File "/home/user/.pyenv/versions/QILING_NEW/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 132, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/user/.pyenv/versions/QILING_NEW/lib/python3.8/site-packages/qiling/core.py", line 898, in emu_start
    raise self._internal_exception
  File "/home/user/.pyenv/versions/QILING_NEW/lib/python3.8/site-packages/qiling/utils.py", line 157, in wrapper
    return func(*args, **kw)
  File "/home/user/.pyenv/versions/QILING_NEW/lib/python3.8/site-packages/qiling/core_hooks.py", line 65, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "/home/user/.pyenv/versions/QILING_NEW/lib/python3.8/site-packages/qiling/core_hooks_types.py", line 23, in call
    return self.callback(ql, *args)
  File "/home/user/.pyenv/versions/QILING_NEW/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 87, in hook_syscall
    return self.load_syscall()
  File "/home/user/.pyenv/versions/QILING_NEW/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 298, in load_syscall
    raise e
  File "/home/user/.pyenv/versions/QILING_NEW/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 282, in load_syscall
    ret = syscall_hook(self.ql, *arg_values)
  File "/home/user/.pyenv/versions/QILING_NEW/lib/python3.8/site-packages/qiling/os/posix/syscall/mman.py", line 249, in ql_syscall_mmap2
    ql.mem.map(mmap_base, ((mmap2_length + 0x1000 - 1) // 0x1000) * 0x1000, info="[syscall_mmap2]")
  File "/home/user/.pyenv/versions/QILING_NEW/lib/python3.8/site-packages/qiling/os/memory.py", line 416, in map
    raise QlMemoryMappedError("Memory Mapped")    
qiling.exception.QlMemoryMappedError: Memory Mapped
```

**Comment by 0xPhoeniX** [comment]
There are several issues with mapped memory address checks. 
That PR (https://github.com/qilingframework/qiling/pull/725) hopefully should fix that.
