### ISSUE TITLE
Ida plugin crash on deflate.

### ISSUE THREAD

**Issue by NULL0B** [qilingframework/qiling#771]
The plugin is coloring the graph well. but when i pick the deflate option to commit it just crash. Ida 7.5 python 3.9.4 installed dev branch from this moment.
Here is the traceback:
```
[INFO][qilingida:1632] Thumb detected, enable it.
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.5/plugins/qilingida.py", line 818, in activate
    self.action_handler.ql_handle_menu_action(self.action_type)
  File "C:/Program Files/IDA 7.5/plugins/qilingida.py", line 2105, in ql_handle_menu_action
    [x.handler() for x in self.menuitems if x.action == action]
  File "C:/Program Files/IDA 7.5/plugins/qilingida.py", line 2105, in <listcomp>
    [x.handler() for x in self.menuitems if x.action == action]
  File "C:/Program Files/IDA 7.5/plugins/qilingida.py", line 1849, in ql_deflat
    if not self._search_path():
  File "C:/Program Files/IDA 7.5/plugins/qilingida.py", line 1633, in _search_path
    self.deflatqlemu.start(archtype=QL_ARCH.ARM_THUMB)
  File "C:/Program Files/IDA 7.5/plugins/qilingida.py", line 916, in start
    self.ql = Qiling(argv=self.path, rootfs=self.rootfs, verbose=QL_VERBOSE.DEBUG, env=self.env, log_plain=True, *args, **kwargs)
  File "C:\Users\Username\AppData\Roaming\Python\Python39\site-packages\qiling\core.py", line 143, in __init__
    if not os.path.exists(str(self._argv[0])):
TypeError: 'NoneType' object is not subscriptable
```

**Comment by wtdcode** [comment]
Looks like the plugin fail to get the path to the input file. Do you setup the plugin before deflating?

**Comment by NULL0B** [comment]
> Looks like the plugin fail to get the path to the input file. Do you setup the plugin before deflating?

yes i already set the project rootfs only to the same folder wich contain the binary

**Comment by wtdcode** [comment]
Sorry for the late reply. Could you upload the test binary?

**Comment by LBJ-the-GOAT** [comment]
@wtdcode  Hi, I got this same error, and have a test file updated.

**Comment by wtdcode** [comment]
Hi, I fixed some related bugs. Could you have a retry?

**Comment by xwings** [comment]
Will you be able to try the latest version of Qiling and see if you still face same issue. There is lots of rework since 2021. Feel free to open a new issue if you have any similar problem.
