### ISSUE TITLE
can't run example scripts crackme_x86_linux.py 

### ISSUE THREAD

**Issue by 23R3F** [qilingframework/qiling#780]
~/qiling/examples$ python3 crackme_x86_linux.py 
Traceback (most recent call last):
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/os/posix/posix.py", line 282, in load_syscall
    ret = syscall_hook(self.ql, *arg_values)
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/os/posix/syscall/stat.py", line 884, in ql_syscall_fstat64
    fstat64_buf = pack_stat64_struct(ql, fstat64_info)
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/os/posix/syscall/stat.py", line 811, in pack_stat64_struct
    stat64.__setattr__(field, int(info[field]))
TypeError: tuple indices must be integers or slices, not str
Traceback (most recent call last):
  File "crackme_x86_linux.py", line 96, in <module>
    solve()
  File "crackme_x86_linux.py", line 76, in solve
    prev_ic = run_one_round(bytes(flag))
  File "crackme_x86_linux.py", line 65, in run_one_round
    ql.run()
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/core.py", line 724, in run
    self.os.run()
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/os/linux/linux.py", line 132, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/core.py", line 868, in emu_start
    raise self._internal_exception
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/utils.py", line 157, in wrapper
    return func(*args, **kw)
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/core_hooks.py", line 118, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/core_hooks.py", line 34, in call
    return self.callback(ql, *args)
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/os/linux/linux.py", line 87, in hook_syscall
    return self.load_syscall()
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/os/posix/posix.py", line 298, in load_syscall
    raise e
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/os/posix/posix.py", line 282, in load_syscall
    ret = syscall_hook(self.ql, *arg_values)
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/os/posix/syscall/stat.py", line 884, in ql_syscall_fstat64
    fstat64_buf = pack_stat64_struct(ql, fstat64_info)
  File "/home/aaa/.local/lib/python3.6/site-packages/qiling/os/posix/syscall/stat.py", line 811, in pack_stat64_struct
    stat64.__setattr__(field, int(info[field]))
TypeError: tuple indices must be integers or slices, not str

my env info:
pip show qiling
Name: qiling
Version: 1.2.3
Summary: Qiling is an advanced binary emulation framework that cross-platform-architecture
Home-page: http://qiling.io
Author: None
Author-email: None
License: GPLv2
Location: /home/aaa/.local/lib/python3.6/site-packages
Requires: unicorn, gevent, pefile, pyelftools, keystone-engine, python-registry, capstone
Required-by: 

------------------------------------------------------------------------
i dont change anything in  crackme_x86_linux.py  or rootfs/x86_linux/bin/crackme_linux
is there has something error in python code?

**Comment by xwings** [comment]
can you please check the in test and compare ?
If there is a different, maybe a PR

**Comment by 23R3F** [comment]
> 
> 
> can you please check the in test and compare ?
> If there is a different, maybe a PR

has check ，the content of crackme_x86_linux.py  in my env  is the same with GitHub

**Comment by xwings** [comment]
i mean this
https://github.com/qilingframework/qiling/blob/a5e7f9a10b14374ad718cba35865283d6c7307e7/tests/test_elf.py#L754

**Comment by 23R3F** [comment]
@xwings 
yea~you are right，the crackme_x86_linux.py  in example is different from qiling/tests/test_elf.py
i change something by compare with test_elf.py , and it works
thx!

**Comment by xwings** [comment]
Cool, can you please sent in a pr?

**Comment by 23R3F** [comment]
@xwings get it
