### ISSUE TITLE
Error when running idapy plugin on windows

### ISSUE THREAD

**Issue by warsang** [qilingframework/qiling#812]
On Windows I get the following error:

```
Traceback (most recent call last):
  File "C:/Users/warsa/OneDrive/Documents/tools/idapro/plugins/qiling.py", line 818, in activate
    self.action_handler.ql_handle_menu_action(self.action_type)
  File "C:/Users/warsa/OneDrive/Documents/tools/idapro/plugins/qiling.py", line 2117, in ql_handle_menu_action
    [x.handler() for x in self.menuitems if x.action == action]
  File "C:/Users/warsa/OneDrive/Documents/tools/idapro/plugins/qiling.py", line 2117, in <listcomp>
    [x.handler() for x in self.menuitems if x.action == action]
  File "C:/Users/warsa/OneDrive/Documents/tools/idapro/plugins/qiling.py", line 1059, in ql_start
    self.qlemu.start()
  File "C:/Users/warsa/OneDrive/Documents/tools/idapro/plugins/qiling.py", line 916, in start
    self.ql = Qiling(argv=self.path, rootfs=self.rootfs, verbose=QL_VERBOSE.DEBUG, env=self.env, log_plain=True, *args, **kwargs)
  File "C:\Users\warsa\AppData\Roaming\Python\Python39\site-packages\qiling\core.py", line 223, in __init__
    self.loader.run()
  File "C:\Users\warsa\AppData\Roaming\Python\Python39\site-packages\qiling\loader\elf.py", line 154, in run
    self.load_with_ld(stack_address + stack_size, argv=self.argv, env=self.env)
  File "C:\Users\warsa\AppData\Roaming\Python\Python39\site-packages\qiling\loader\elf.py", line 311, in load_with_ld
    interp = ELFParse(self.ql.rootfs + interp_path, self.ql)
  File "C:\Users\warsa\AppData\Roaming\Python\Python39\site-packages\qiling\loader\elf.py", line 64, in __init__
    self.f = open(path, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\warsa\\OneDrive\\Documents\\tools\\qiling\\rootfs/lib64/ld-linux-x86-64.so.2'
```

I'm not sure where and if I should try getting the ld-linux-x86-64.so.2 on my windows host. Would downloading it fix this?

**Comment by kabeor** [comment]
@warsang Hi, looks like you set a wrong rootfs path, it should be like qiling/rootfs/**x8664_linux**/
