### ISSUE TITLE
continue步骤报错

### ISSUE THREAD

**Issue by xunbu7** [qilingframework/qiling#854]
***Describe the bug**
环境：
win7 sp1 x64
qiling-1.2.4/qiling-1.2.5.dev0
python3.8.6
IDA 7.5 SP3

环境：
win10 20h2
qiling-1.2.4/qiling-1.2.5.dev0
python3.8.10
IDA 7.5 SP3

问题：
成功导入麒麟ida插件后，设置好setup，均正常。但是当我点击continue的时候，报错如下：

[+]	mprotect(0x47c6000, 0x1000, PROT_READ) = 0
[+]	mprotect() = 0x0
[+]	[+] Received Interupt: 2 Hooked Interupt: 2
[+]	0x047baf14: mmap2(addr = 0x0, length = 0x1000, prot = 0x3, flags = 0x22, fd = 0xffffffff, pgoffset = 0x0)
[+]	mmap2(0x0, 0x1000, PROT_READ | PROT_WRITE (0x3), MAP_PRIVATE | MAP_ANONYMOUS (0x22), ffffffff, 0x0)
[+]	mmap2 - mapping needed for 0x0
[+]	mmap2 - addr range  0x774c2000 - 0x774c2fff: 
[+]	mmap2(0x0, 0x1000, 0x3, 0x22, -1, 0x0) = 0x774c2000
[+]	mmap2() = 0x774c2000
[+]	[+] Received Interupt: 2 Hooked Interupt: 2
[+]	0x047bb084: write(fd = 0x2, buf = 0x774c2000, count = 0x0)
[x]	
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\qiling\os\posix\posix.py", line 281, in load_syscall
    ret = syscall_hook(self.ql, *arg_values)
  File "C:\Python38\lib\site-packages\qiling\os\posix\syscall\unistd.py", line 266, in ql_syscall_write
    ql.os.fd[write_fd].write(buf)
  File "C:\IDA Pro 7.5 SP3\python\3\init.py", line 63, in write
    ida_kernwin.msg(text)
  File "C:\IDA Pro 7.5 SP3\python\3\ida_kernwin.py", line 236, in msg
    return _ida_kernwin.msg(*args)
TypeError: A string expected
[=]	Syscall ERROR: ql_syscall_write DEBUG: A string expected
Traceback (most recent call last):
  File "C:/Python38/Lib/site-packages/qiling/extensions/idaplugin/qilingida.py", line 818, in activate
    self.action_handler.ql_handle_menu_action(self.action_type)
  File "C:/Python38/Lib/site-packages/qiling/extensions/idaplugin/qilingida.py", line 2117, in ql_handle_menu_action
    [x.handler() for x in self.menuitems if x.action == action]
  File "C:/Python38/Lib/site-packages/qiling/extensions/idaplugin/qilingida.py", line 2117, in <listcomp>
    [x.handler() for x in self.menuitems if x.action == action]
  File "C:/Python38/Lib/site-packages/qiling/extensions/idaplugin/qilingida.py", line 1097, in ql_continue
    self.qlemu.run()
  File "C:/Python38/Lib/site-packages/qiling/extensions/idaplugin/qilingida.py", line 934, in run
    self.ql.run(begin, end)
  File "C:\Python38\lib\site-packages\qiling\core.py", line 755, in run
    self.os.run()
  File "C:\Python38\lib\site-packages\qiling\os\linux\linux.py", line 142, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "C:\Python38\lib\site-packages\qiling\core.py", line 899, in emu_start
    raise self._internal_exception
  File "C:\Python38\lib\site-packages\qiling\utils.py", line 158, in wrapper
    return func(*args, **kw)
  File "C:\Python38\lib\site-packages\qiling\core_hooks.py", line 65, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "C:\Python38\lib\site-packages\qiling\core_hooks_types.py", line 23, in call
    return self.callback(ql, *args)
  File "C:\Python38\lib\site-packages\qiling\os\linux\linux.py", line 94, in hook_syscall
    return self.load_syscall()
  File "C:\Python38\lib\site-packages\qiling\os\posix\posix.py", line 297, in load_syscall
    raise e
  File "C:\Python38\lib\site-packages\qiling\os\posix\posix.py", line 281, in load_syscall
    ret = syscall_hook(self.ql, *arg_values)
  File "C:\Python38\lib\site-packages\qiling\os\posix\syscall\unistd.py", line 266, in ql_syscall_write
    ql.os.fd[write_fd].write(buf)
  File "C:\IDA Pro 7.5 SP3\python\3\init.py", line 63, in write
    ida_kernwin.msg(text)
  File "C:\IDA Pro 7.5 SP3\python\3\ida_kernwin.py", line 236, in msg
    return _ida_kernwin.msg(*args)
TypeError: A string expected

**Comment by xwings** [comment]
Discussion moved to PM
