### ISSUE TITLE
AttributeError: 'QlOsUefi' object has no attribute 'read_wstring': when run/os/uefi/rt.py

### ISSUE THREAD

**Issue by PangPangpeng** [qilingframework/qiling#864]
***Describe the bug**
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/qiling/os/uefi/uefi.py", line 182, in run
    self.ql.emu_start(self.ql.loader.entry_point, self.exit_point, self.ql.timeout, self.ql.count)
  File "/usr/local/lib/python3.9/site-packages/qiling/core.py", line 900, in emu_start
    raise self._internal_exception
  File "/usr/local/lib/python3.9/site-packages/qiling/utils.py", line 158, in wrapper
    return func(*args, **kw)
  File "/usr/local/lib/python3.9/site-packages/qiling/core_hooks.py", line 165, in _hook_addr_cb
    ret = h.call(ql, addr, size)
  File "/usr/local/lib/python3.9/site-packages/qiling/core_hooks_types.py", line 35, in call
    return self.callback(ql)
  File "/usr/local/lib/python3.9/site-packages/qiling/os/uefi/fncc.py", line 21, in wrapper
    return ql.os.call(pc, f, params, onenter, onexit)
  File "/usr/local/lib/python3.9/site-packages/qiling/os/os.py", line 133, in call
    targs, retval, retaddr = self.fcall.call(func, proto, args, onenter, onexit, passthru)
  File "/usr/local/lib/python3.9/site-packages/qiling/os/fcall.py", line 144, in call
    retval = func(ql, pc, params)
  File "/usr/local/lib/python3.9/site-packages/qiling/os/uefi/rt.py", line 102, in hook_GetNextVariableName
    last_name = ql.os.read_wstring(var_name)
AttributeError: 'QlOsUefi' object has no attribute 'read_wstring'

**Sample Code**
```python
#!/usr/bin/env python3
# 
# Cross Platform and Multi Architecture Advanced Binary Emulation Framework
#

import pickle
import sys
sys.path.append("..")

from qiling import Qiling
from qiling.const import QL_INTERCEPT, QL_VERBOSE
from qiling.os.uefi.const import EFI_SUCCESS, EFI_INVALID_PARAMETER
from qiling.os.uefi.utils import check_and_notify_protocols, signal_event

def force_notify_RegisterProtocolNotify(ql: Qiling, address: int, params):
    event_id = params['Event']

    if event_id in ql.loader.events:
        # let's force notify
        event = ql.loader.events[event_id]
        event['Guid'] = params["Protocol"]
        event["Set"] = False

        signal_event(ql, event_id)
        check_and_notify_protocols(ql, True)

        return EFI_SUCCESS

    return EFI_INVALID_PARAMETER

def my_onenter(ql: Qiling, address: int, params):
    print(f'[onenter] CopyMem : params = {params}')

    return address, params

def hook_inner_func(ql: Qiling, address, size):
    #ql.log.info("Run code at address {}".format(hex(address)))
    if address != 0x1002a5:
        md = ql.create_disassembler()
        buf = ql.mem.read(address, size)
        for i in md.disasm(buf, address):
            #ql.log.info(":: 0x%x:\t%s\t%s" %(i.address, i.mnemonic, i.op_str))
            #hook protocol
            if i.mnemonic == 'call' and i.op_str == 'qword ptr [r9]' :
                ql.reg.rax = 1
                ql.reg.eip += 3
    
    
    if address == 0x1005B3: # hook HOB LIST checl
        ql.log.info("Jump HOB list\n")
        ql.reg.eip += 0x9e
    
    elif address == 0x10e8fe: # hook NewPackageList
        ql.log.info("Jump NewPackageList\n")
        ql.reg.eip += size
    
    elif address == 0x100DF6:
        ql.log.info("Jump NewPackageList\n")
        ql.reg.eip += 0x11
    
    elif address == 0x115A24: # hook assert
        pFilePath = ql.reg.rcx
        iLine = ql.reg.edx
        pErrorInfo = ql.reg.r8
        strFilePath = ql.mem.string(pFilePath)
        strErrorInfo = ql.mem.string(pErrorInfo)
        ql.log.info("Error Found: {}, code at {}:{}".format(strErrorInfo, strFilePath, iLine))
        #ql.log.info("pFilePath = {}, iLine = {}, pErrorInfo = {}".format(pFilePath, iLine, pErrorInfo))
        ql.reg.eip += 0x14d
    
    elif address == 0x115760: #hook DebugVPrint
        pErrorNum = ql.reg.ecx
        pFilePath = ql.reg.edx
        iLine = ql.reg.r8
        strFilePath = ql.mem.string(pFilePath)
        ql.log.info("Error Num is {}, Eerror Message: {}".format(hex(pErrorNum), strFilePath))
        #ql.log.info("pFilePath = {}, iLine = {}, pErrorInfo = {}".format(pFilePath, iLine, pErrorNum))
        ql.reg.eip += 0x20
    
    elif address == 0x1100F4: #hook Zeromem
        pBuf = ql.reg.rax
        Length = ql.reg.rdx
        # ql.log.info("{} {}".format(hex(pBuf), hex(Length)))
        if pBuf != 0 and Length != 0:
            ql.mem.write(pBuf, bytes(0)*Length)
            ql.reg.eip += 0x6d
    elif address == 0x10bcc8: # hook ConsoleLoggerEnableCursor
        ql.reg.rax = 0
        ql.reg.eip += 0x2e
    # hook protocol
    elif address == 0x120250:
        ql.reg.rax = 1
        ql.reg.eip += 2
    elif address == 0x100d0a:
        ql.reg.rax = 1
        ql.reg.eip += 3
    elif address == 0x10bd77:
        ql.reg.rax = 0
        ql.reg.eip +=4
    

    return EFI_SUCCESS

def hook_uart_print(ql: Qiling):
    ql.log.info("Hook DebugVPrint Sucess!\n")
    return EFI_SUCCESS

if __name__ == "__main__":
    with open("rootfs/rom2_nvar.pickel", 'rb') as f:
        env = pickle.load(f)

    ql = Qiling(["rootfs/bin/Section_PE32_image_UefiShellFileGuid_Shell_body.efi"], "rootfs/", env=env, verbose=QL_VERBOSE.DEBUG)

    ql.set_api("RegisterProtocolNotify", force_notify_RegisterProtocolNotify)
    ql.set_api("CopyMem", my_onenter, QL_INTERCEPT.ENTER)
    ql.hook_code(hook_inner_func)
    #set cs register
    #ql.reg.cs = 0x100000
    
    #ql.debugger = True

    # set some data
    buf = [0x00] * 0x78
    ql.mem.map(0x00, 0x1000) 
    ql.mem.write(0x00,bytes(buf))

    #set gRT
    buf = ql.mem.read(0x780001f0,0x88)
    ql.mem.write(0x1E0A40,bytes(buf))
    
    buf = ql.mem.read(0x780001f0,0x88)
    ql.log.info(buf)
    buf = ql.mem.read(0x1E0A40,0x88)
    ql.log.info(buf)
    ql.run()
```

**Expected behavior**
It seems that QlOsUefi object don't have read_wstring.

**Additional context**
I read the source code, and I found that the QlOs code has change since 1.2.4.1 and the `read_wstring` api have moved to `self.utils`, so I change "/usr/local/lib/python3.9/site-packages/qiling/os/uefi/rt.py: 102 from `ql.os.read_wstring` to ql.os.utils.read_wstring` and I sovle this error. I think this should be changed in the master bracnch.

**Comment by elicn** [comment]
Thanks for reporting this.
The fix was actually in my pipeline for UEFI along with some other changes.. it will be committed soon, hopefully.

**Comment by PangPangpeng** [comment]
OK, waiting for the new version. ☆▽☆
