### ISSUE TITLE
Failed binary in PR #874

### ISSUE THREAD

**Issue by xwings** [qilingframework/qiling#875]
Hi @rootkiter 

Seems like i am getting the blow error msg for test_armoabi_eb_linux_syscall_elf_static

```
(256)$ python3 ./qltool run -f examples/rootfs/armeb_linux/bin/posix_syscall_msb.armoabi --rootfs ../examples/rootfs/a
rmeb_linux
[x]

[x]     r0      :        0x4890000
[x]     r1      :        0x7ff3cf0c
[x]     r2      :        0x90830100
[x]     r3      :        0x94800000
[x]     r4      :        0x94830100
[x]     r5      :        0x0
[x]     r6      :        0x7ff3cf0c
[x]     r7      :        0x0
[x]     r8      :        0x0
[x]     r9      :        0x0
[x]     r10     :        0x1000000
[x]     r11     :        0x0
[x]     r12     :        0x83f3cf10
[x]     sp      :        0x7ff3ce88
[x]     lr      :        0x4000000
[x]     pc      :        0xa3a8
[x]     msp     :        0x7ff3ce88
[x]     psp     :        0x0
[x]     xpsr    :        0x80000000
[x]     apsr    :        0x80000000
[x]     ipsr    :        0x0
[x]     epsr    :        0x0
[x]     primask :        0x0
[x]     faultmask       :        0x0
[x]     basepri :        0x0
[x]     control :        0x0
[x]     f0      :        0x0
[x]     f1      :        0x0
[x]     f2      :        0x0
[x]     f3      :        0x0
[x]     f4      :        0x0
[x]     f5      :        0x0
[x]     f6      :        0x0
[x]     f7      :        0x0
[x]     fps     :        0x0
[x]     cpsr    :        0x800001d3
[x]     c1_c0_2 :        0x0
[x]     c13_c0_3        :        0x0
[x]     fpexc   :        0x40000000
[x]

[x]     PC = 0xa3a8
[x]      (/home/xwings/projects/qiling_mcu/examples/rootfs/armeb_linux/bin/posix_syscall_msb.armoabi+0xa3a8)
[=]     Start      End        Perm    Label          Image
[=]     00008000 - 0000f000   r-x     /home/xwings/projects/qiling_mcu/examples/rootfs/armeb_linux/bin/posix_syscall_msb.armoabi   /home/xwings/projects/qiling_mcu/examples/rootfs/armeb_linux/bin/posix_syscall_msb.armoabi
[=]     00016000 - 00019000   rw-     /home/xwings/projects/qiling_mcu/examples/rootfs/armeb_linux/bin/posix_syscall_msb.armoabi   /home/xwings/projects/qiling_mcu/examples/rootfs/armeb_linux/bin/posix_syscall_msb.armoabi
[=]     00019000 - 0001b000   rwx     [hook_mem]
[=]     7ff0d000 - 7ff3d000   rwx     [stack]
[=]     ffff0000 - ffff1000   rwx     [arm_tls]
[x]     ['0xe1', '0xa0', '0x60', '0x2', '0xe2', '0x82', '0xc0', '0x4']
[=]

[x]     Error: PC(0xa3a8) Unreachable
Traceback (most recent call last):
  File "./qltool", line 257, in <module>
    ql.run(timeout=options.timeout)
  File "/home/xwings/projects/qiling_mcu/qiling/core.py", line 771, in run
    self.os.run()
  File "/home/xwings/projects/qiling_mcu/qiling/os/linux/linux.py", line 139, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/xwings/projects/qiling_mcu/qiling/core.py", line 918, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/usr/local/lib/python3.8/dist-packages/unicorn-2.0.0-py3.8.egg/unicorn/unicorn.py", line 426, in emu_start
unicorn.unicorn.UcError: Invalid memory write (UC_ERR_WRITE_UNMAPPED)
```

**Comment by rootkiter** [comment]
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/6734184/128480416-dd323fc3-7850-40ba-a5ad-343fb388859d.png">

It seems no problem.

**Comment by rootkiter** [comment]
<img width="937" alt="image" src="https://user-images.githubusercontent.com/6734184/128480953-c9014724-095b-44b0-8ddc-ad1c4a809744.png">
Is that the problem

**Comment by xwings** [comment]
> <img alt="image" width="937" src="https://user-images.githubusercontent.com/6734184/128480953-c9014724-095b-44b0-8ddc-ad1c4a809744.png">
> 
> Is that the problem

can u check the test_elf.py

**Comment by xwings** [comment]
Seems like still having the same issue

![image](https://user-images.githubusercontent.com/463553/129161264-c2a750ad-0715-4006-8b59-162a601d9a64.png)
