### ISSUE TITLE
Invalid memory read (UC_ERR_READ_UNMAPPED) while running a Windows PE

### ISSUE THREAD

**Issue by thelumberjhack** [qilingframework/qiling#88]
## Description of the issue

I am trying to unpack some kkrunchy packed binary (kkrunchy itself) as a way to test the framework. 

(I can run all the PE examples from the project perfectly fine.)

But I ran into the following issue:

```shell
python kkrunchy.py
[+] SET_THREAD_AREA selector : 0x73
[+] SET_THREAD_AREA selector : 0x7b
[+] SET_THREAD_AREA selector : 0x83
[+] SET_THREAD_AREA selector : 0x8b
[+] SET_THREAD_AREA selector : 0x90
[+] Windows Registry PATH: /home/yannick/workspace/projects/qiling/examples/rootfs/x86_windows/Windows/registry
[+] Loading /home/yannick/workspace/projects/qiling/examples/rootfs/x86_windows/bin/kkrunchy_023a.exe to 0x5e0000
[+] PE entry point at 0x5e9a7a
[+] Initiate stack address at 0xfffdd000 
[+] TEB addr is 0x6000
[+] PEB addr is 0x6044
[+] Loading /home/yannick/workspace/projects/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/kernel32.dll to 0x10000000
[+] Done with loading /home/yannick/workspace/projects/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/kernel32.dll
[+] Done with loading /home/yannick/workspace/projects/qiling/examples/rootfs/x86_windows/bin/kkrunchy_023a.exe
0x100149d7: LoadLibraryA(lpLibFileName = "KERNEL32.dll") = 0x10000000
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "OutputDebugStringA") = 0x1003b2b7
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "WriteFile") = 0x10011282
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetStdHandle") = 0x100151b3
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "CloseHandle") = 0x10011410
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "ReadFile") = 0x10013ed3
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetFileSize") = 0x1001196e
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "CreateFileA") = 0x100153c6
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetTickCount") = 0x1001110c
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "ExitProcess") = 0x10017a10
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetProcAddress") = 0x10011222
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "LoadLibraryA") = 0x100149d7
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "VirtualProtect") = 0x1001435f
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetLocaleInfoA") = 0x1002d5e5
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "HeapSize") = 0x100c9bce
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetSystemTimeAsFileTime") = 0x10013509
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetCurrentProcessId") = 0x100111f8
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetCurrentThreadId") = 0x10011450
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "QueryPerformanceCounter") = 0x10011725
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "LCMapStringW") = 0x100117b9
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "HeapAlloc") = 0x100c9ba0
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "HeapFree") = 0x100114c9
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "HeapReAlloc") = 0x100c9bb6
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetLastError") = 0x100111c0
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "MultiByteToWideChar") = 0x1001192e
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetModuleHandleA") = 0x10011245
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetCommandLineA") = 0x100151a1
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetVersionExA") = 0x10013519
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "HeapDestroy") = 0x100135b7
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "HeapCreate") = 0x10014a2d
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "VirtualFree") = 0x1001186e
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "VirtualAlloc") = 0x10011856
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "TerminateProcess") = 0x1002d802
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetCurrentProcess") = 0x10011809
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetModuleFileNameA") = 0x100114b1
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "UnhandledExceptionFilter") = 0x1003772f
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "FreeEnvironmentStringsA") = 0x1001e349
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetEnvironmentStrings") = 0x1001e361
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "FreeEnvironmentStringsW") = 0x100151cb
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "WideCharToMultiByte") = 0x1001170d
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetEnvironmentStringsW") = 0x100151e3
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "SetHandleCount") = 0x1001cb29
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetFileType") = 0x10013531
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetStartupInfoA") = 0x10010e00
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetACP") = 0x1001179c
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetOEMCP") = 0x1003d1a1
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetCPInfo") = 0x10015189
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "RtlUnwind") = 0x1003d1c3
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "InterlockedExchange") = 0x10011462
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "VirtualQuery") = 0x1001445a
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetStringTypeA") = 0x10038266
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetStringTypeW") = 0x10011946
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "LCMapStringA") = 0x1003bc39
0x10011222: GetProcAddress(hModule = 0x10000000, lpProcName = "GetSystemInfo") = 0x100149ca
[+] Loading /home/yannick/workspace/projects/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/ole32.dll to 0x1010b000
[+] Done with loading /home/yannick/workspace/projects/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/ole32.dll
0x100149d7: LoadLibraryA(lpLibFileName = "ole32.dll") = 0x1010b000
0x10011222: GetProcAddress(hModule = 0x1010b000, lpProcName = "CoCreateInstance") = 0x10154d0b
0x10011222: GetProcAddress(hModule = 0x1010b000, lpProcName = "CoUninitialize") = 0x101536d3
0x10011222: GetProcAddress(hModule = 0x1010b000, lpProcName = "CoInitialize") = 0x10126636
[+] Loading /home/yannick/workspace/projects/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/oleaut32.dll to 0x10267000
[+] Done with loading /home/yannick/workspace/projects/qiling/examples/rootfs/x86_windows/Windows/SysWOW64/oleaut32.dll
0x100149d7: LoadLibraryA(lpLibFileName = "OLEAUT32.dll") = 0x10267000
[!] GetProcAddress Exception Found
Traceback (most recent call last):
  File "/home/yannick/.local/share/virtualenvs/qiling-Z14cQecd/lib/python3.8/site-packages/qiling-0.9-py3.8.egg/qiling/os/windows/x86.py", line 45, in hook_winapi
  File "/home/yannick/.local/share/virtualenvs/qiling-Z14cQecd/lib/python3.8/site-packages/qiling-0.9-py3.8.egg/qiling/os/windows/fncc.py", line 186, in wrapper
  File "/home/yannick/.local/share/virtualenvs/qiling-Z14cQecd/lib/python3.8/site-packages/qiling-0.9-py3.8.egg/qiling/os/windows/fncc.py", line 145, in x86_stdcall
  File "/home/yannick/.local/share/virtualenvs/qiling-Z14cQecd/lib/python3.8/site-packages/qiling-0.9-py3.8.egg/qiling/os/windows/fncc.py", line 130, in __x86_cc
  File "/home/yannick/.local/share/virtualenvs/qiling-Z14cQecd/lib/python3.8/site-packages/qiling-0.9-py3.8.egg/qiling/os/windows/fncc.py", line 95, in set_function_params
  File "/home/yannick/.local/share/virtualenvs/qiling-Z14cQecd/lib/python3.8/site-packages/qiling-0.9-py3.8.egg/qiling/os/utils.py", line 470, in read_cstring
  File "/home/yannick/.local/share/virtualenvs/qiling-Z14cQecd/lib/python3.8/site-packages/unicorn/unicorn.py", line 394, in mem_read
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory read (UC_ERR_READ_UNMAPPED)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kkrunchy.py", line 32, in <module>
    my_sandbox([binary], rootfs)
  File "kkrunchy.py", line 25, in my_sandbox
    ql.run()
  File "/home/yannick/.local/share/virtualenvs/qiling-Z14cQecd/lib/python3.8/site-packages/qiling-0.9-py3.8.egg/qiling/core.py", line 212, in run
  File "/home/yannick/.local/share/virtualenvs/qiling-Z14cQecd/lib/python3.8/site-packages/qiling-0.9-py3.8.egg/qiling/os/windows/x86.py", line 172, in runner
  File "/home/yannick/.local/share/virtualenvs/qiling-Z14cQecd/lib/python3.8/site-packages/qiling-0.9-py3.8.egg/qiling/core.py", line 23, in wrapper
  File "/home/yannick/.local/share/virtualenvs/qiling-Z14cQecd/lib/python3.8/site-packages/qiling-0.9-py3.8.egg/qiling/core.py", line 265, in _callback
  File "/home/yannick/.local/share/virtualenvs/qiling-Z14cQecd/lib/python3.8/site-packages/qiling-0.9-py3.8.egg/qiling/os/windows/x86.py", line 48, in hook_winapi
qiling.exception.QlErrorSyscallError: [!] Windows API Implementation Error
```

kkrunchy.py script:

```python
import os
from unicorn import *
from unicorn.x86_const import *

from qiling import *

def dump_bin(ql):
    ql.nprint("Found unpacked binary")
    ql.uc.emu.stop()


def my_sandbox(path, rootfs):
    ql = Qiling(
        path, rootfs, libcache=True, output="debug"
    )

    # print(f"Stack addr: 0x{ql.stack_address:08x}")
    # print(f"Stack size: 0x{ql.stack_size:08x}")
    # print(f"mmap start: 0x{ql.mmap_start:08x}")

    # Hooking final return address
    ql.hook_address(dump_bin, 0x005f09b5)

    # Run
    ql.run()


if __name__ == "__main__":
    binary = os.path.join(os.getcwd(), "rootfs/x86_windows/bin/kkrunchy_023a.exe")
    rootfs = os.path.join(os.getcwd(), "rootfs/x86_windows")

    my_sandbox([binary], rootfs)
```

Analyzed binary > http://www.farbrausch.de/~fg/kkrunchy/kkrunchy_023a.zip (from [ryg's homepage](http://www.farbrausch.de/~fg/kkrunchy/))

## Execution environment

- Ubuntu 18.04 `Linux rick 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- python packages:

```shell
pipenv run pip freeze
capstone==4.0.1
enum-compat==0.0.3
future==0.18.2
keystone-engine==0.9.1.post3
pefile==2019.4.18
python-registry==1.3.1
qiling==0.9
unicodecsv==0.14.1
unicorn==1.0.1
```

- Qiling commit 9bdd096e19aa5b627591d2b5ca0a00c2c731cb53

## Question

Is there a way to configure Qiling so that I don't run into this issue?

Thanks

**Comment by xwings** [comment]
hi, 

there are still tons of Windows API is not being implemented. will you be able to help ?

**Comment by yformaggio** [comment]
Hi, I can try to do that. I will send you a PR if/when I am done.

Cheers

**Comment by xwings** [comment]
@yformaggio  thanks！

**Comment by xwings** [comment]
ok, i tried with version 2 and it seems we got better luck. Do u want to try ?
![image](https://user-images.githubusercontent.com/463553/79190387-c2e07a80-7e56-11ea-8a61-05a822ef7c58.png)

**Comment by Dliv3** [comment]
fixed in https://github.com/qilingframework/qiling/commit/aaa0edf041c0b53669516c44a7e8ec03ba30ea4c

**Comment by xwings** [comment]
![image](https://user-images.githubusercontent.com/463553/79194264-da236600-7e5e-11ea-9605-4772318f2e35.png)

**Comment by thelumberjhack** [comment]
Thanks @xwings & @Dliv3 ! It's working now 👍 I tried to fix myself but did not really understand the error so I was going the wrong way.
