### ISSUE TITLE
MMU OR TLB? problem in MIPS V1 EL 32bit version

### ISSUE THREAD

**Issue by f10w3r-s** [qilingframework/qiling#883]
After extracting the firmware to emulate the Humax router, it was operated in the Qiling environment.

There was a difference of 0x50000 between the result of debugging on the actual device and the result of debugging on the emulator in the relative address calculation part.

After shoveling, it is speculated that this problem is related to the MMU problem of the embedded device.

The figure below shows the result values ​​operating in the emulator environment. The a1 register will contain the value 0x6f08.

```
Thread 2000	0x77533928 {libc.so.0            + 0x006928}   08 6f a5 24                   addiu $a1, $a1, 0x6f08
Thread 2000	0x77517eb8 {libgcc_s.so.1        + 0x00feb8}   02 00 1c 3c                   lui $gp, 2
Thread 2000	0x77517ebc {libgcc_s.so.1        + 0x00febc}   28 bc 9c 27                   addiu $gp, $gp, -0x43d8
Thread 2000	0x77517ec0 {libgcc_s.so.1        + 0x00fec0}   21 e0 99 03                   addu $gp, $gp, $t9
Thread 2000	0x77517ec4 {libgcc_s.so.1        + 0x00fec4}   d0 80 99 8f                   lw $t9, -0x7f30($gp)
Thread 2000	0x77517ec8 {libgcc_s.so.1        + 0x00fec8}   21 30 00 00                   move $a2, $zero
Thread 2000	0x77517ecc {libgcc_s.so.1        + 0x00fecc}   21 38 00 00                   move $a3, $zero
Thread 2000	0x77517ed0 {libgcc_s.so.1        + 0x00fed0}   08 00 20 03                   jr $t9
Thread 2000	0x77517ed4 {libgcc_s.so.1        + 0x00fed4}   00 00 00 00                   nop 
Thread 2000	0x77517e10 {libgcc_s.so.1        + 0x00fe10}   02 00 1c 3c                   lui $gp, 2
Thread 2000	0x77517e14 {libgcc_s.so.1        + 0x00fe14}   d0 bc 9c 27                   addiu $gp, $gp, -0x4330
Thread 2000	0x77517e18 {libgcc_s.so.1        + 0x00fe18}   21 e0 99 03                   addu $gp, $gp, $t9
Thread 2000	0x77517e1c {libgcc_s.so.1        + 0x00fe1c}   d8 ff bd 27                   addiu $sp, $sp, -0x28
Thread 2000	0x77517e20 {libgcc_s.so.1        + 0x00fe20}   24 00 bf af                   sw $ra, 0x24($sp)
Thread 2000	0x77517e24 {libgcc_s.so.1        + 0x00fe24}   10 00 bc af                   sw $gp, 0x10($sp)
Thread 2000	0x77517e28 {libgcc_s.so.1        + 0x00fe28}   21 00 80 50                   beql $a0, $zero, 0x77517eb0
Thread 2000	0x77517e30 {libgcc_s.so.1        + 0x00fe30}   00 00 82 8c                   lw $v0, ($a0)
Thread 2000	0x77517e34 {libgcc_s.so.1        + 0x00fe34}   1d 00 40 10                   beqz $v0, 0x77517eac
Thread 2000	0x77517e38 {libgcc_s.so.1        + 0x00fe38}   ff ff 02 24                   addiu $v0, $zero, -1
Thread 2000	0x77517e3c {libgcc_s.so.1        + 0x00fe3c}   21 18 00 00                   move $v1, $zero
Thread 2000	0x77517e40 {libgcc_s.so.1        + 0x00fe40}   c4 50 43 7c                   ins $v1, $v0, 3, 8
Thread 2000	0x77517e44 {libgcc_s.so.1        + 0x00fe44}   00 00 a2 ac                   sw $v0, ($a1)
Thread 2000	hook! 0x77533000-0x7752d000 bytearray(b'_setdetachstate\x00pthr')
Thread 2000	0x77533f08

Thread 2000	zero	:	 0x0
Thread 2000	at	:	 0x0
Thread 2000	v0	:	 0xffffffff
Thread 2000	v1	:	 0x7f8
Thread 2000	a0	:	 0x77533000
Thread 2000	a1	:	 0x77533f08
Thread 2000	a2	:	 0x0
Thread 2000	a3	:	 0x0
Thread 2000	t0	:	 0x775316dc
Thread 2000	t1	:	 0x7752e66c
Thread 2000	t2	:	 0x0
Thread 2000	t3	:	 0xffffffff
Thread 2000	t4	:	 0xf0000000
Thread 2000	t5	:	 0x1
Thread 2000	t6	:	 0x47d1154
Thread 2000	t7	:	 0x1
Thread 2000	s0	:	 0x3
Thread 2000	s1	:	 0x774bf050
Thread 2000	s2	:	 0x47ca000
Thread 2000	s3	:	 0x0
Thread 2000	s4	:	 0x1
Thread 2000	s5	:	 0x4
Thread 2000	s6	:	 0x47d1190
Thread 2000	s7	:	 0x774bf82f
Thread 2000	t8	:	 0xc
Thread 2000	t9	:	 0x77517e10
Thread 2000	k0	:	 0x0
Thread 2000	k1	:	 0x0
Thread 2000	gp	:	 0x77533ae0
Thread 2000	sp	:	 0x7ff3caa0
Thread 2000	s8	:	 0x7ff3cba8
Thread 2000	ra	:	 0x7753392c
Thread 2000	status	:	 0x0
Thread 2000	lo	:	 0x0
Thread 2000	hi	:	 0x0
Thread 2000	badvaddr	:	 0x0
Thread 2000	cause	:	 0x0
Thread 2000	pc	:	 0x77517e44
Thread 2000	cp0_config3	:	 0x2000 0x77533f08
Thread 2000	cp0_userlocal	:	 0x77590440  0x77533f08
Thread 2000	

Thread 2000	PC = 0x77517e44
Thread 2000	

Thread 2000	Start      End        Perm    Label          Image
Thread 2000	00400000 - 00481000   r-x     /shared/rootfs/bin/boa   /shared/rootfs/bin/boa
Thread 2000	00491000 - 004aa000   rw-     /shared/rootfs/bin/boa   /shared/rootfs/bin/boa
Thread 2000	004aa000 - 004ac000   rwx     [hook_mem]     
Thread 2000	047ba000 - 047d0000   rwx     /shared/rootfs/lib/ld-uClibc.so.0   
Thread 2000	047d0000 - 047d1000   r--     [mprotect]     
Thread 2000	047d1000 - 047d2000   rwx     /shared/rootfs/lib/ld-uClibc.so.0   
Thread 2000	774bf000 - 774c0000   rwx     [syscall_mmap]   
Thread 2000	774c1000 - 774c2000   rwx     [mmap] /shared/rootfs/lib/libmtdapi.so   
Thread 2000	774c2000 - 774d1000   rwx     [syscall_mmap]   
Thread 2000	774d1000 - 774d2000   rwx     [mmap] /shared/rootfs/lib/libmtdapi.so   
Thread 2000	774d3000 - 774e1000   rwx     [mmap] /shared/rootfs/lib/libapmib.so   
Thread 2000	774e1000 - 774f0000   rwx     [syscall_mmap]   
Thread 2000	774f0000 - 77506000   rwx     [mmap] /shared/rootfs/lib/libapmib.so   
Thread 2000	77506000 - 77507000   rwx     [syscall_mmap]   
Thread 2000	77508000 - 7751c000   rwx     [mmap] /shared/rootfs/lib/libgcc_s.so.1   
Thread 2000	7751c000 - 7752b000   rwx     [syscall_mmap]   
Thread 2000	7752b000 - 7752c000   rwx     [mmap] /shared/rootfs/lib/libgcc_s.so.1   
Thread 2000	7752d000 - 77573000   rwx     [mmap] /shared/rootfs/lib/libc.so.0   
Thread 2000	77573000 - 77583000   rwx     [syscall_mmap]   
Thread 2000	77583000 - 77584000   rwx     [mmap] /shared/rootfs/lib/libc.so.0   
Thread 2000	77584000 - 77589000   rwx     [syscall_mmap]   
Thread 2000	77589000 - 7758a000   rwx     [syscall_mmap]   
Thread 2000	7ff0d000 - 7ff3d000   rwx     [stack]        
Thread 2000	['0x0', '0x0', '0xa2', '0xac', '0x4', '0x81', '0x82', '0x8f']
Thread 2000	

Thread 2000	0x77517e44 {libgcc_s.so.1        + 0x00fe44}   00 00 a2 ac 04 81 82 8f 04 00 a6 ac 08 00 a7 ac 0c 00 a4 ac 08 00 40 10 10 00 a3 ac 18 80 84 8f 6c 80 99 8f 18 00 a5 af 09 f8 20 03 20 3d 84 24 10 00 bc 8f 18 00 a5 8f 18 80 82 8f 48 3d 43 8c sw $v0, ($a1)
> lw $v0, -0x7efc($gp)
> sw $a2, 4($a1)
> sw $a3, 8($a1)
> sw $a0, 0xc($a1)
> beqz $v0, 0x77517e7c
> sw $v1, 0x10($a1)
> lw $a0, -0x7fe8($gp)
> lw $t9, -0x7f94($gp)
> sw $a1, 0x18($sp)
> jalr $t9
> addiu $a0, $a0, 0x3d20
> lw $gp, 0x10($sp)
> lw $a1, 0x18($sp)
> lw $v0, -0x7fe8($gp)
> lw $v1, 0x3d48($v0)
Thread 2000	
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/qiling/os/linux/thread.py", line 248, in _run
    self.ql.emu_start(start_address, self.exit_point, count=30000)
  File "/usr/local/lib/python3.8/dist-packages/qiling/core.py", line 896, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn.py", line 341, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Write to write-protected memory (UC_ERR_WRITE_PROT)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/usr/local/lib/python3.8/dist-packages/qiling/os/linux/thread.py", line 252, in _run
    raise e
  File "/usr/local/lib/python3.8/dist-packages/qiling/os/linux/thread.py", line 248, in _run
    self.ql.emu_start(start_address, self.exit_point, count=30000)
  File "/usr/local/lib/python3.8/dist-packages/qiling/core.py", line 896, in emu_start
    self.uc.emu_start(begin, end, timeout, count)
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn.py", line 341, in emu_start
    raise UcError(status)
unicorn.unicorn.UcError: Write to write-protected memory (UC_ERR_WRITE_PROT)
2021-08-09T18:18:31Z <QlLinuxMIPS32Thread at 0x7f51b9b30150: _run> failed with UcError

```

But on a real device, the a1 register contained the address the library was mapped to + 0x50000 + the actual offset value.

It is implemented in a way that only 0x6f08 value is put in the actual binary, but 0x56f08 value is actually entered.

![image](https://user-images.githubusercontent.com/41041924/129161007-02cd5cf5-ee25-4ade-9aa2-55168a26e911.png)

![image](https://user-images.githubusercontent.com/41041924/129161040-137f607a-ea97-4498-89b7-25686ca63d87.png)

**Comment by xwings** [comment]
To be honest, MIPS always acts funny :(

There might a bug here. Appreciate if you can push in PR if you mange to fix it.

**Comment by xwings** [comment]
Will you be able to try the latest version of Qiling and see if you still face same issue. There is lots of rework since 2021. Feel free to open a new issue if you have any similar problem.
