### ISSUE TITLE
idaplugin generate error: 'Syscall ERROR: ql_syscall_writev DEBUG: A string expected'

### ISSUE THREAD

**Issue by b1gcat** [qilingframework/qiling#888]
I use latest plugin in ida7.5. After setting up successfully, I use 'execute till' and get errors:

```python
[INFO][qilingida:2085] ['E:\\fuck\\fck', '11111111']
[INFO][qilingida:1054] Rootfs: E:\fuck
[INFO][qilingida:1055] Custom user script: None
[INFO][qilingida:1056] Custom env: {}
[+]	Profile: Default
[+]	Map GDT at 0x30000 with GDT_LIMIT=4096
[+]	Write to 0x30018 for new entry b'\x00\xf0\x00\x00\x00\xfeO\x00'
[+]	Write to 0x30028 for new entry b'\x00\xf0\x00\x00\x00\x96O\x00'
[+]	load 0x8048000 - 0x8049000
[+]	load 0x8049000 - 0x804b000
[+]	mem_start: 0x8048000 mem_end: 0x804b000
[+]	interp is : E:\fuck/lib/ld-linux.so.2
[+]	interp_mem_size is : 0x2c000
[+]	interp_address is : 0x47ba000
[+]	mmap_address is : 0x774bf000
[+]	rel name b'__gmon_start__'
[+]	rel name b'__errno_location'
[+]	rel name b'sprintf'
[+]	rel name b'__gmon_start__'
[+]	rel name b'__libc_start_main'
[+]	rel name b'free'
[+]	rel name b'memcpy'
[+]	rel name b'strcpy'
[+]	rel name b'printf'
[+]	rel name b'fwrite'
[+]	rel name b'malloc'
[+]	rel name b'puts'
[+]	rel name b'rand'
[+]	rel name b'strcmp'
[+]	rel name b'exit'
[INFO][qilingida:1064] Qiling is initialized successfully.
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	brk return(0x804d000)
[+]	0x047d5357: brk(input = 0x0) = 0x804d000
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	0x047d6c4d: uname(address = 0x7ff3ca72) = 0x0
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	access(\etc\ld.so.nohwcap, 0x0) = -1 
[+]	No such file or directory
[+]	0x047ca0da: access(path = 0x47d9bef, mode = 0x0) = -0x1 (EPERM)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	access(\etc\ld.so.preload, 0x4) = -1 
[+]	No such file or directory
[+]	0x047d670b: access(path = 0x47db530, mode = 0x4) = -0x1 (EPERM)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /etc/ld.so.cache, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x47d9faa, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/i386-linux-gnu/tls/i686/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/i386-linux-gnu/tls/i686/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/i386-linux-gnu/tls/i686/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/i386-linux-gnu/tls/i686", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/i386-linux-gnu/tls/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/i386-linux-gnu/tls/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/i386-linux-gnu/tls/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/i386-linux-gnu/tls", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/i386-linux-gnu/i686/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/i386-linux-gnu/i686/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/i386-linux-gnu/i686/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/i386-linux-gnu/i686", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/i386-linux-gnu/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/i386-linux-gnu/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/i386-linux-gnu/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/i386-linux-gnu", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/i386-linux-gnu/tls/i686/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/i386-linux-gnu/tls/i686/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/i386-linux-gnu/tls/i686/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/i386-linux-gnu/tls/i686", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/i386-linux-gnu/tls/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/i386-linux-gnu/tls/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/i386-linux-gnu/tls/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/i386-linux-gnu/tls", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/i386-linux-gnu/i686/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/i386-linux-gnu/i686/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/i386-linux-gnu/i686/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/i386-linux-gnu/i686", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/i386-linux-gnu/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/i386-linux-gnu/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/i386-linux-gnu/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/i386-linux-gnu", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/tls/i686/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/tls/i686/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/tls/i686/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/tls/i686", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/tls/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/tls/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/tls/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/tls", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/i686/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/i686/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/i686/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/i686", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /lib/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/lib", 0x7ff3c318) write completed
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = 0x0
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/tls/i686/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/tls/i686/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/tls/i686/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/tls/i686", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/tls/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/tls/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/tls/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/tls", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/i686/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/i686/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/i686/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/i686", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/sse2/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib/sse2", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	openat(fd = 4294967196, path = /usr/lib/libc.so.6, flags = O_RDONLY, mode = 0o0) = -2
[+]	0x047d692a: openat(fd = 0xffffff9c, path = 0x7ff3c2a0, flags = 0x88000, mode = 0x0) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	stat64("/usr/lib", 0x7ff3c318) read/write fail
[+]	0x047d654b: stat64(path = 0x7ff3c2a0, buf_ptr = 0x7ff3c318) = -0x2 (ENOENT)
[+]	[+] Received Interupt: 128 Hooked Interupt: 128
[+]	writev() CONTENT:
[+]	bytearray(b'E:\\fuck\\fck')
[x]	
Traceback (most recent call last):
  File "C:\***\AppData\Roaming\Python\Python38\site-packages\qiling\os\posix\posix.py", line 186, in load_syscall
    retval = syscall_hook(self.ql, *params)
  File "C:\***\AppData\Roaming\Python\Python38\site-packages\qiling\os\posix\syscall\uio.py", line 29, in ql_syscall_writev
    ql.os.fd[writev_fd].write(buf)
  File "E:\reverse\IDA7_5\python\3\init.py", line 63, in write
    ida_kernwin.msg(text)
  File "E:\reverse\IDA7_5\python\3\ida_kernwin.py", line 236, in msg
    return _ida_kernwin.msg(*args)
TypeError: A string expected
[=]	Syscall ERROR: ql_syscall_writev DEBUG: A string expected
Traceback (most recent call last):
  File "E:/reverse/IDA7_5/plugins/qilingida.py", line 818, in activate
    self.action_handler.ql_handle_menu_action(self.action_type)
  File "E:/reverse/IDA7_5/plugins/qilingida.py", line 2117, in ql_handle_menu_action
    [x.handler() for x in self.menuitems if x.action == action]
  File "E:/reverse/IDA7_5/plugins/qilingida.py", line 2117, in <listcomp>
    [x.handler() for x in self.menuitems if x.action == action]
  File "E:/reverse/IDA7_5/plugins/qilingida.py", line 1160, in ql_run_to_here
    self.qlemu.run(end=curr_addr+self.qlemu.baseaddr-get_imagebase())
  File "E:/reverse/IDA7_5/plugins/qilingida.py", line 934, in run
    self.ql.run(begin, end)
  File "C:\***\AppData\Roaming\Python\Python38\site-packages\qiling\core.py", line 755, in run
    self.os.run()
  File "C:\***\AppData\Roaming\Python\Python38\site-packages\qiling\os\linux\linux.py", line 133, in run
    self.ql.emu_start(self.ql.loader.entry_point, entry_address, self.ql.timeout)
  File "C:\***\AppData\Roaming\Python\Python38\site-packages\qiling\core.py", line 899, in emu_start
    raise self._internal_exception
  File "C:\***\AppData\Roaming\Python\Python38\site-packages\qiling\utils.py", line 158, in wrapper
    return func(*args, **kw)
  File "C:\***\AppData\Roaming\Python\Python38\site-packages\qiling\core_hooks.py", line 65, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "C:\***\AppData\Roaming\Python\Python38\site-packages\qiling\core_hooks_types.py", line 23, in call
    return self.callback(ql, *args)
  File "C:\***\AppData\Roaming\Python\Python38\site-packages\qiling\os\linux\linux.py", line 94, in hook_syscall
    return self.load_syscall()
  File "C:\***\AppData\Roaming\Python\Python38\site-packages\qiling\os\posix\posix.py", line 205, in load_syscall
    raise e
  File "C:\***\AppData\Roaming\Python\Python38\site-packages\qiling\os\posix\posix.py", line 186, in load_syscall
    retval = syscall_hook(self.ql, *params)
  File "C:\***\AppData\Roaming\Python\Python38\site-packages\qiling\os\posix\syscall\uio.py", line 29, in ql_syscall_writev
    ql.os.fd[writev_fd].write(buf)
  File "E:\reverse\IDA7_5\python\3\init.py", line 63, in write
    ida_kernwin.msg(text)
  File "E:\reverse\IDA7_5\python\3\ida_kernwin.py", line 236, in msg
    return _ida_kernwin.msg(*args)
TypeError: A string expected
```

**Comment by xwings** [comment]
I think there are few issue which known for now.

1. "Unlicensed" IDA pro, it seems we had some issue with it
2. IDA pro in Windows. Due to priority on others components, we might take a look later.

**Comment by xwings** [comment]
Will you be able to try the latest version of Qiling and see if you still face same issue. There is lots of rework since 2021. Feel free to open a new issue if you have any similar problem.
