### ISSUE TITLE
syscall mprotect error with PROT_GROWSDOWN

### ISSUE THREAD

**Issue by dark-lbp** [qilingframework/qiling#889]
***Describe the bug***
Some arm router call `mprotect` with `prot=0x1000007` which should be `PROT_READ | PROT_WRITE | PROT_EXEC | PROT_GROWSDOWN`,  but looks like unicorn not support `PROT_GROWSDOWN`?

Below is the error log.
```python
[+]	[+] Received Interupt: 2 Hooked Interupt: 2
[+]	mprotect(0x7ff6c000, 0x1000, PROT_READ | PROT_WRITE | PROT_EXEC | 16777216) = 0
[+]	Invalid argument (UC_ERR_ARG)
[x]	
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/qiling-1.2.5.dev0-py3.8.egg/qiling/os/posix/syscall/mman.py", line 61, in ql_syscall_mprotect
    ql.mem.protect(start, mlen, prot)
  File "/usr/local/lib/python3.8/dist-packages/qiling-1.2.5.dev0-py3.8.egg/qiling/os/memory.py", line 450, in protect
    self.ql.uc.mem_protect(aligned_address, aligned_size, perms)
  File "/usr/local/lib/python3.8/dist-packages/unicorn-1.0.3-py3.8-linux-x86_64.egg/unicorn/unicorn.py", line 493, in mem_protect
    raise UcError(status)
unicorn.unicorn.UcError: Invalid argument (UC_ERR_ARG)

During handling of the above exception, another exception occurred:
```

**Comment by dark-lbp** [comment]
Example without Qiling, so should we add an prot mask in qiling or open an issue to unicorn?
```python
# !/usr/bin/env python3
# coding=utf-8
from unicorn import *

uc = Uc(UC_ARCH_ARM, UC_MODE_ARM + UC_MODE_LITTLE_ENDIAN)
mapping_start_address = 0x7ff6c000
ram_size = 0x1000
uc.mem_map(address=mapping_start_address, size=ram_size, perms=UC_PROT_ALL)
perms = 0x1000007
uc.mem_protect(mapping_start_address, 0x1000, perms)
>>
Traceback (most recent call last):
  File "/opt/pycharm_project_734/unicorn_mprotect_test.py", line 10, in <module>
    uc.mem_protect(mapping_start_address, 0x1000, perms)
  File "/usr/local/lib/python3.8/dist-packages/unicorn-1.0.3-py3.8-linux-x86_64.egg/unicorn/unicorn.py", line 493, in mem_protect
    raise UcError(status)
unicorn.unicorn.UcError: Invalid argument (UC_ERR_ARG)

```

**Comment by elicn** [comment]
Hey @dark-lbp,
Can you pull the latest changes from `dev` and verify the problem was fixed?

**Comment by dark-lbp** [comment]
> Hey @dark-lbp,
> Can you pull the latest changes from `dev` and verify the problem was fixed?

@elicn  Thanks, the problem is fixed.
