### ISSUE TITLE
error parameter `lseek_offset` value in lseek method of ql_file class when emulate ARM 32 program

### ISSUE THREAD

**Issue by zrax-x** [qilingframework/qiling#922]
### test code

```python
from qiling import *

def run_sandbox(path, rootfs):
    ql = Qiling(path, rootfs, console=True, log_file="./log.txt")
    ql.run()

if __name__ == "__main__":
    run_sandbox(["./atoi_test"], "./qiling/examples/rootfs/arm_linux")
```

#### code of atoi_test.c

```c
//arm-linux-gnueabihf-gcc atoi_test.c -o atoi_test
#include <stdlib.h>
#include <stdio.h>

int foo()
{
    char buf[10];
    scanf("%s", buf);
    printf("%d", atoi(buf));
    return 0;
}

int main(int argc, char **argv)
{
    return foo();
}
```

complie in ubuntu20.04 x86_64: `arm-linux-gnueabihf-gcc atoi_test.c -o atoi_test `

error log：

```
[=]     brk(input = 0x0) = 0x56569000
[=]     uname(address = 0x7ff3cb20) = 0x0
[=]     access(path = 0x47d8f64, mode = 0x0) = -0x1 (EPERM)
[=]     mmap2(addr = 0x0, length = 0x3000, prot = 0x3, flags = 0x22, fd = 0xffffffff, pgoffset = 0x0) = 0x774bf000
[=]     access(path = 0x47d7fb8, mode = 0x4) = -0x1 (EPERM)
[=]     open(filename = 0x47d9df0, flags = 0x80000, mode = 0x1) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = -0x2 (ENOENT)
[=]     stat64(path = 0x7ff3c6b0, buf_ptr = 0x7ff3c748) = -0x2 (ENOENT)
[=]     open(filename = 0x7ff3c6b0, flags = 0x80000, mode = 0x47eb960) = 0x3
[=]     read(fd = 0x3, buf = 0x7ff3c820, len = 0x200) = 0x200
[=]     lseek(fd = 0x3, ofset = 0x12cbcc, origin = 0x0) = 0x12cbcc
[=]     read(fd = 0x3, buf = 0x7ff3baa8, len = 0xb40) = 0xb40
[=]     lseek(fd = 0x3, ofset = 0x12bdfc, origin = 0x0) = 0x12bdfc
[=]     read(fd = 0x3, buf = 0x7ff3ba70, len = 0x2f) = 0x2f
[=]     fstat64(fd = 0x3, buf_ptr = 0x7ff3c748) = 0x0
[=]     mmap2(addr = 0x0, length = 0x13e540, prot = 0x5, flags = 0x802, fd = 0x3, pgoffset = 0x0) = 0x774c2000
[=]     mprotect(start = 0x775eb000, mlen = 0x10000, prot = 0x0) = 0x0
[=]     mmap2(addr = 0x775fb000, length = 0x3000, prot = 0x3, flags = 0x812, fd = 0x3, pgoffset = 0x129) = 0x775fb000
[=]     mmap2(addr = 0x775fe000, length = 0x2540, prot = 0x3, flags = 0x32, fd = 0xffffffff, pgoffset = 0x0) = 0x775fe000
[=]     close(fd = 0x3) = 0x0
[=]     set_tls(address = 0x774c17d0)
[=]     mprotect(start = 0x775fb000, mlen = 0x2000, prot = 0x1) = 0x0
[=]     mprotect(start = 0x56565000, mlen = 0x1000, prot = 0x1) = 0x0
[=]     mprotect(start = 0x47ea000, mlen = 0x1000, prot = 0x1) = 0x0
[=]     fstat64(fd = 0x0, buf_ptr = 0x7ff3c6d0) = 0x0
[=]     brk(input = 0x0) = 0x56569000
[=]     brk(input = 0x5658a000) = 0x5658a000
123
[=]     read(fd = 0x0, buf = 0x56569008, len = 0x400) = 0x4
[=]     fstat64(fd = 0x1, buf_ptr = 0x7ff3c7d8) = 0x0
123[=]  write(fd = 0x1, buf = 0x56569410, count = 0x3) = 0x3
[x]
Traceback (most recent call last):
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 186, in load_syscall
    retval = syscall_hook(self.ql, *params)
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/os/posix/syscall/unistd.py", line 159, in ql_syscall__llseek
    ret = ql.os.fd[fd].lseek(offset, origin)
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/os/filestruct.py", line 49, in lseek
    return os.lseek(self.__fd, lseek_offset, lseek_origin)
OverflowError: Python int too large to convert to C long
[=]     Syscall ERROR: ql_syscall__llseek DEBUG: Python int too large to convert to C long
Traceback (most recent call last):
  File "load_atoi_test.py", line 8, in <module>
    run_sandbox(["./atoi_test"], "/home/qinmdai/qiling/qiling/examples/rootfs/arm_linux")
  File "load_atoi_test.py", line 5, in run_sandbox
    ql.run()
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/core.py", line 755, in run
    self.os.run()
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 139, in run
    self.ql.emu_start(self.ql.loader.elf_entry, self.exit_point, self.ql.timeout, self.ql.count)
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/core.py", line 899, in emu_start
    raise self._internal_exception
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/utils.py", line 158, in wrapper
    return func(*args, **kw)
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/core_hooks.py", line 65, in _hook_intr_cb
    ret = h.call(ql, intno)
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/core_hooks_types.py", line 23, in call
    return self.callback(ql, *args)
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/os/linux/linux.py", line 94, in hook_syscall
    return self.load_syscall()
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 205, in load_syscall
    raise e
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/os/posix/posix.py", line 186, in load_syscall
    retval = syscall_hook(self.ql, *params)
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/os/posix/syscall/unistd.py", line 159, in ql_syscall__llseek
    ret = ql.os.fd[fd].lseek(offset, origin)
  File "/home/qinmdai/.local/lib/python3.8/site-packages/qiling/os/filestruct.py", line 49, in lseek
    return os.lseek(self.__fd, lseek_offset, lseek_origin)
OverflowError: Python int too large to convert to C long
```

it seems that in file qiling/os/filestruct.py, the parameter lseek_offset of method lseek of class ql_file is 0xffffffffffffffff while our emulation environment is ARM 32.

**Comment by zrax-x** [comment]
Well, it does work, but i can't get the object ql, so i replace ql.unpack64s with struct.pack currently and the `ENDIAN` is fixed to little endian.

**Comment by elicn** [comment]
Oh, I realize I wasn't clear about the exact location to patch.
You should patch the `ql_syscall__llseek` method at `qiling/os/posix/syscall/unistd.py`.
Its first line should be replaced with the one I specified above.

**Comment by zrax-x** [comment]
fine, thanks.

**Comment by elicn** [comment]
Great; I'll create a patch to fix it.

**Comment by elicn** [comment]
@zrax-x ,
The fix is merged now. Would you be able to give your test another spin (with new `dev`) and close the issue if it was fixed?
